export const EXERCISES = [
  // ─── CHEST ───────────────────────────────────────────────────────────────
  {
    name: 'Barbell Bench Press',
    muscleGroup: 'Chest',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'The cornerstone chest movement. Builds overall pressing strength and chest mass.',
    tips: [
      'Retract and depress your shoulder blades before unracking — keep this position throughout.',
      'Lower the bar to your lower chest (nipple line), not your neck.',
      'Flare elbows 45–75° — not fully tucked, not flared straight out.',
      '"Bend the bar" outward as you press to activate your lats for a stable base.',
      'Drive your feet into the floor hard to create full-body tension.',
    ],
  },
  {
    name: 'Incline Barbell Bench Press',
    muscleGroup: 'Chest',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Emphasises the upper (clavicular) head of the pecs and anterior delts.',
    tips: [
      'Set the bench to 30–45°. Higher angles recruit more front delt and less upper chest.',
      'The bar should touch your upper chest near your clavicle, not your neck.',
      'Same scapular setup as flat bench — blades retracted and tucked down.',
      'Slightly narrower grip than flat bench feels more natural here.',
    ],
  },
  {
    name: 'Decline Barbell Bench Press',
    muscleGroup: 'Chest',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Targets the lower sternal fibres and allows heavier loading than flat bench for many lifters.',
    tips: [
      'Bar touches the lower sternum — below the nipple line.',
      'Keep shoulder blades retracted. Avoid losing upper back tightness.',
      'People with shoulder issues often find this variation more comfortable.',
      'Use a spotter — the decline makes re-racking trickier.',
    ],
  },
  {
    name: 'Dumbbell Bench Press',
    muscleGroup: 'Chest',
    equipment: 'Dumbbells',
    type: 'Compound',
    description: 'Greater range of motion than barbell. Fixes strength imbalances and allows a more natural pressing path.',
    tips: [
      'At the bottom, let elbows drop slightly below shoulder level for a full stretch.',
      'Bring the dumbbells together at the top for a peak contraction squeeze.',
      'Neutral or angled grip both work — angled (45°) is more natural for most wrists.',
      'Control the descent. Don\'t let the dumbbells crash down.',
    ],
  },
  {
    name: 'Incline Dumbbell Press',
    muscleGroup: 'Chest',
    equipment: 'Dumbbells',
    type: 'Compound',
    description: 'Best upper chest isolation with the full ROM advantage of dumbbells.',
    tips: [
      '30–45° incline. Above 45° shifts load almost entirely to anterior delts.',
      'Keep elbows slightly in front of your body at the top to maintain chest tension.',
      'Don\'t let dumbbells drift wide apart at the bottom — stay controlled.',
      'Slight external rotation of the wrists as you press creates a better chest stretch.',
    ],
  },
  {
    name: 'Decline Dumbbell Press',
    muscleGroup: 'Chest',
    equipment: 'Dumbbells',
    type: 'Compound',
    description: 'Hits lower chest with a natural path and is easier on the shoulder than barbell decline for some.',
    tips: [
      'Touch dumbbells slightly below your lower chest.',
      'Full ROM — elbows go slightly below the bench at the bottom.',
      'Great finishing exercise after heavy barbell work.',
    ],
  },
  {
    name: 'Cable Flyes (Low to High)',
    muscleGroup: 'Chest',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'Cables at floor level, hands sweep up and together. Targets upper chest with constant tension.',
    tips: [
      'Maintain a slight, fixed bend in your elbows throughout — never fully lock or pull with arms.',
      'Imagine you\'re hugging a barrel. The motion is an arc, not a press.',
      'Lean forward slightly into the movement for more stretch.',
      'Cables provide constant tension unlike dumbbells — capitalise on this with slow eccentrics.',
    ],
  },
  {
    name: 'Cable Flyes (High to Low)',
    muscleGroup: 'Chest',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'Cables at shoulder or above height, hands sweep down and together. Targets lower/sternal chest.',
    tips: [
      'Great for developing the lower chest sweep.',
      'Arms meet at hip height at the bottom of the movement.',
      'Squeeze for 1–2 seconds at the peak contraction.',
      'Slightly stagger your stance for better stability.',
    ],
  },
  {
    name: 'Dumbbell Flyes',
    muscleGroup: 'Chest',
    equipment: 'Dumbbells',
    type: 'Isolation',
    description: 'An isolation arc movement that stretches the chest and builds the mind-muscle connection.',
    tips: [
      'Think "hugging a tree" — a wide arc, not a press.',
      'Keep a slight, consistent bend in the elbows to protect the joint.',
      'Let the dumbbells stretch your chest at the bottom, but don\'t hyperextend.',
      'Use lighter weight than pressing. This is about the stretch, not load.',
    ],
  },
  {
    name: 'Push Ups',
    muscleGroup: 'Chest',
    equipment: 'Bodyweight',
    type: 'Compound',
    description: 'Foundational pushing pattern. Scalable and highly effective for chest, triceps, and core.',
    tips: [
      'Hands slightly wider than shoulder-width, fingers angled outward slightly.',
      'Maintain a straight line from head to heels — squeeze glutes and brace core.',
      'Lead with your chest to the floor, not your hips first.',
      'Tuck elbows at 45° to protect shoulders.',
      'Decline push ups (feet elevated) target upper chest. Diamond push ups hit triceps.',
    ],
  },
  {
    name: 'Chest Dips',
    muscleGroup: 'Chest',
    equipment: 'Bodyweight',
    type: 'Compound',
    description: 'Lean forward to shift the emphasis from triceps to lower chest.',
    tips: [
      'Lean your torso forward 20–30° to bias the chest.',
      'Use a wider grip (parallel bars, not close) to open your chest more.',
      'Lower until you feel a strong chest stretch, then drive back up.',
      'Add weight with a dip belt once bodyweight becomes easy.',
      'If chest dips hurt your shoulders, skip them — they\'re not worth injury.',
    ],
  },
  {
    name: 'Pec Deck / Chest Fly Machine',
    muscleGroup: 'Chest',
    equipment: 'Machine',
    type: 'Isolation',
    description: 'Machine version of the fly — great for beginners or as a finishing burnout.',
    tips: [
      'Adjust the seat so your arms are parallel to the floor at mid-range.',
      'Don\'t slam the weight stack — control the eccentric on the way back.',
      'Squeeze the pads together and hold for 1 second at the peak.',
      'Great for the pump at the end of a chest workout.',
    ],
  },
  {
    name: 'Machine Chest Press',
    muscleGroup: 'Chest',
    equipment: 'Machine',
    type: 'Compound',
    description: 'Stable pressing movement. Ideal for beginners and for going to failure safely.',
    tips: [
      'Adjust the seat so handles are at mid-chest height.',
      'Keep shoulders back and down, same as barbell bench.',
      'Try single-arm work to address imbalances.',
      'Great for high-rep burnout sets at the end of your session.',
    ],
  },
  {
    name: 'Floor Press',
    muscleGroup: 'Chest',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'ROM is limited by the floor — great for lockout strength and shoulder-friendly pressing.',
    tips: [
      'Triceps rest on the floor at the bottom — eliminates leg drive.',
      'Great option if shoulder impingement limits your regular bench.',
      'Explosive off the floor, control on the way down.',
      'Excellent accessory lift for bench press competition prep.',
    ],
  },
  {
    name: 'Landmine Press',
    muscleGroup: 'Chest',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Arc-shaped press using a landmine setup. Shoulder-friendly and great for upper chest.',
    tips: [
      'Use one hand and press the end of the barbell up in a slight arc.',
      'The arc naturally targets the upper chest better than flat pressing.',
      'Very shoulder-friendly — a great alternative if flat bench irritates you.',
      'Stagger your stance and brace your core for stability.',
    ],
  },

  {
    name: 'Single Arm Pec Deck',
    muscleGroup: 'Chest',
    equipment: 'Machine',
    type: 'Isolation',
    description: 'Unilateral pec deck fly. Work each side of the chest independently to fix imbalances.',
    tips: [
      'Use one arm at a time on the pec deck machine.',
      'Brace your free hand on the machine or your thigh for stability.',
      'Cross your working hand slightly past the midline for a deeper contraction.',
      'Start with your weaker side first.',
    ],
  },
  {
    name: 'Single Arm Cable Fly',
    muscleGroup: 'Chest',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'Unilateral cable fly allowing independent work on each side with a deeper cross-body squeeze.',
    tips: [
      'Stand in the centre of a cable station, use one handle at a time.',
      'Cross your hand past the midline of your body for peak contraction.',
      'Great for fixing chest imbalances between left and right.',
      'Use your free hand on your working pec to build the mind-muscle connection.',
    ],
  },
  {
    name: 'Cable Crossover',
    muscleGroup: 'Chest',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'Mid-height cable fly with handles at shoulder level. Targets the mid-chest with constant tension.',
    tips: [
      'Set cables at shoulder height for mid-chest emphasis.',
      'Step forward slightly to pre-stretch the chest.',
      'Hands meet in front of your chest — squeeze and hold for 1 second.',
      'Great for pump and isolation at the end of a chest session.',
    ],
  },
  {
    name: 'Smith Machine Bench Press',
    muscleGroup: 'Chest',
    equipment: 'Machine',
    type: 'Compound',
    description: 'Fixed bar path bench press. Allows heavier loading and is safer for training to failure alone.',
    tips: [
      'The fixed path removes stabiliser demand — focus purely on pushing.',
      'Great for training to failure without a spotter.',
      'Can adjust bench angle for incline or decline variations.',
      'Line up so the bar touches your mid-chest at the bottom.',
    ],
  },
  {
    name: 'Incline Machine Press',
    muscleGroup: 'Chest',
    equipment: 'Machine',
    type: 'Compound',
    description: 'Machine press at an incline angle. Targets upper chest safely with no spotter needed.',
    tips: [
      'Adjust the seat so handles align with your upper chest.',
      'Press smoothly without locking out to keep tension on the chest.',
      'Great for high-rep burnout sets after heavy barbell work.',
      'Try single-arm pressing to address left-right imbalances.',
    ],
  },
  {
    name: 'Single Arm Machine Chest Press',
    muscleGroup: 'Chest',
    equipment: 'Machine',
    type: 'Compound',
    description: 'Unilateral machine press that isolates each side of the chest independently.',
    tips: [
      'Press with one arm at a time to identify and fix strength imbalances.',
      'Brace your core to prevent rotation during the press.',
      'Start with your weaker side first.',
      'Great for bodybuilders focusing on symmetry.',
    ],
  },

  // ─── BACK ─────────────────────────────────────────────────────────────────
  {
    name: 'Deadlift',
    muscleGroup: 'Back',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'The ultimate full-body compound lift. Trains the entire posterior chain.',
    tips: [
      'Set up with the bar directly over your midfoot, about 1 inch from your shins.',
      'Hip-width stance, toes slightly out. Take a big breath and brace your core like a vise.',
      'Push the floor away — don\'t think of it as pulling the bar up.',
      'Bar should drag up your shins and thighs (wear long socks to avoid skin tears).',
      'At lockout: hips through, glutes squeezed — but don\'t hyperextend your lower back.',
      'Lower back should remain neutral throughout — not rounded, not excessively arched.',
    ],
  },
  {
    name: 'Romanian Deadlift',
    muscleGroup: 'Hamstrings',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Hip hinge movement that stretches and strengthens the hamstrings. Starts from the top, not the floor.',
    tips: [
      'Start standing with the bar at hip height. Push hips back while keeping a slight knee bend.',
      'Feel the stretch in your hamstrings — that\'s the cue to stop lowering.',
      'Keep the bar close to your legs the whole way down.',
      'Hip hinge, NOT a squat. Knees should barely move.',
      'Drive your hips forward to stand back up, squeezing glutes at the top.',
    ],
  },
  {
    name: 'Barbell Row',
    muscleGroup: 'Back',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'The primary upper back builder. Trains the entire posterior chain from a hinge position.',
    tips: [
      'Hinge forward until your torso is around 45–70° parallel to the floor.',
      'Pull to your belly button for more lat involvement.',
      'Pull to your lower chest for more upper back and rhomboid activation.',
      'Brace your core like a deadlift — you\'re in a similar position.',
      'Squeeze your shoulder blades together and hold for 1 second at the top.',
    ],
  },
  {
    name: 'Pendlay Row',
    muscleGroup: 'Back',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Strict row where the bar returns to the floor between reps. Builds explosive back strength.',
    tips: [
      'Torso is nearly horizontal (more so than regular barbell row).',
      'Bar starts on the floor each rep — no cheating with momentum.',
      'Explosive pull from a dead stop — builds power and strength simultaneously.',
      'Keep your lower back flat; the horizontal position makes this harder.',
    ],
  },
  {
    name: 'Dumbbell Row',
    muscleGroup: 'Back',
    equipment: 'Dumbbells',
    type: 'Compound',
    description: 'Unilateral row with greater ROM than barbell. Excellent for fixing imbalances.',
    tips: [
      'Support your body with your knee and hand on a bench.',
      'Let the dumbbell hang at full arm extension at the bottom — get that lat stretch.',
      'Row the dumbbell toward your hip (not your armpit) for maximum lat involvement.',
      'Think "elbow to the ceiling" as your primary cue.',
      'Don\'t rotate your torso to heave the weight up.',
    ],
  },
  {
    name: 'Lat Pulldown',
    muscleGroup: 'Back',
    equipment: 'Cable',
    type: 'Compound',
    description: 'Vertical pull that targets the lats for width. Great for those who can\'t do pull ups yet.',
    tips: [
      'Lean back slightly (10–15°) with your chest up.',
      'Think about pulling your elbows down into your back pockets.',
      'At the top of each rep, let your shoulder blades rise to get a full lat stretch.',
      'Don\'t pull behind the neck — it stresses the cervical spine unnecessarily.',
      'Avoid swinging or using momentum — the stretch at the top is half the exercise.',
    ],
  },
  {
    name: 'Pull Ups',
    muscleGroup: 'Back',
    equipment: 'Bodyweight',
    type: 'Compound',
    description: 'The gold standard for lat width. One of the most effective back exercises.',
    tips: [
      'Start from a dead hang with full arm extension every rep.',
      'Grip slightly wider than shoulder-width for maximum lat engagement.',
      'Drive your elbows toward your hips as you pull — not just pulling with your arms.',
      'Aim to get your chest to the bar, not just your chin over it.',
      'Slow the descent — the eccentric is incredibly valuable for strength and growth.',
    ],
  },
  {
    name: 'Chin Ups',
    muscleGroup: 'Back',
    equipment: 'Bodyweight',
    type: 'Compound',
    description: 'Underhand grip pull up — more bicep recruitment, easier for most beginners.',
    tips: [
      'Supinated (palms facing you) grip at shoulder-width.',
      'The underhand grip allows greater supination and therefore more bicep engagement.',
      'Same lat-focus cue applies: drive elbows toward hips.',
      'Great entry point for people building up to overhand pull ups.',
    ],
  },
  {
    name: 'Seated Cable Row',
    muscleGroup: 'Back',
    equipment: 'Cable',
    type: 'Compound',
    description: 'Horizontal pull with constant cable tension. Excellent for back thickness.',
    tips: [
      'Sit tall with a slight forward lean at the start of each rep.',
      'Row to your belly button with elbows tucked close to your torso.',
      'At the stretch position, let your shoulder blades fully protract (come apart).',
      'Squeeze and hold for 1 second at peak contraction.',
      'Don\'t lean back excessively — that\'s your lower back doing the work, not your back.',
    ],
  },
  {
    name: 'T-Bar Row',
    muscleGroup: 'Back',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Landmine or T-bar setup row. Allows heavy loading with a natural grip.',
    tips: [
      'V-handle = neutral grip = more lat. Wide handle = more upper back.',
      'Row to your lower chest for maximum upper back involvement.',
      'Hinge your torso to 45° just like barbell row.',
      'Use a chest-supported T-bar row if your lower back fatigues early.',
    ],
  },
  {
    name: 'Face Pulls',
    muscleGroup: 'Back',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'Essential for shoulder health and rear delt/upper trap development.',
    tips: [
      'Set the cable at or slightly above eye level with a rope attachment.',
      'Pull to your forehead, not your neck — face, not chest.',
      'At the end of the pull, externally rotate: hands go back and out past your ears.',
      'Use light weight with high reps (15–25). This is a health and hypertrophy exercise.',
      'Do these every single session — they\'re the best shoulder health exercise.',
    ],
  },
  {
    name: 'Straight-Arm Pulldown',
    muscleGroup: 'Back',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'Isolates the lat without bicep assistance. Excellent for building the mind-muscle connection.',
    tips: [
      'Arms stay slightly bent and rigid throughout — no elbow flexion.',
      'Focus on the deep lat stretch at the top of each rep.',
      'Pull hands toward hips in a sweeping arc.',
      'Go light and feel every inch of the lat working.',
    ],
  },
  {
    name: 'Chest-Supported Row',
    muscleGroup: 'Back',
    equipment: 'Dumbbells',
    type: 'Compound',
    description: 'Lying face-down on an incline bench removes lower back from the equation entirely.',
    tips: [
      'Set bench to 30–45° incline. Lie prone with chest resting on the pad.',
      'Removes all lower back stress — great if lower back fatigue limits your rows.',
      'Retract shoulder blades fully at the top.',
      'Can use dumbbells, barbell, or cable.',
    ],
  },
  {
    name: 'Rack Pull',
    muscleGroup: 'Back',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Partial deadlift from a raised starting point. Allows heavier loading and targets the lockout.',
    tips: [
      'Set the pins so the bar starts at knee height or just below.',
      'Setup is identical to deadlift — brace hard and push the floor away.',
      'Allows supramaximal loading — great for building lockout strength.',
      'Use straps to ensure grip isn\'t the limiting factor.',
    ],
  },
  {
    name: 'Single-Arm Cable Row',
    muscleGroup: 'Back',
    equipment: 'Cable',
    type: 'Compound',
    description: 'Unilateral cable row that allows full rotation and greater stretch.',
    tips: [
      'Allow a slight torso rotation forward to get a better lat stretch at the bottom.',
      'Row to your hip and rotate back to square at the contracted position.',
      'Great for addressing left-right imbalances.',
      'Can be done seated or standing.',
    ],
  },
  {
    name: 'Meadows Row',
    muscleGroup: 'Back',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Landmine row invented by John Meadows. Excellent for lat and upper back thickness.',
    tips: [
      'Stand perpendicular to the landmine, stagger your stance.',
      'Grip the end of the bar with your outside hand.',
      'Pull the bar toward your hip in an arc.',
      'Great for targeting the lat from a different angle than standard rows.',
    ],
  },

  {
    name: 'Close Grip Lat Pulldown',
    muscleGroup: 'Back',
    equipment: 'Cable',
    type: 'Compound',
    description: 'Lat pulldown with a close neutral grip. Emphasises the lower lats and allows more bicep assistance.',
    tips: [
      'Use a V-handle or close-grip attachment.',
      'Lean back slightly and pull to your lower chest.',
      'Neutral grip is easier on the shoulders than wide overhand.',
      'Great for building lat thickness in the lower portion.',
    ],
  },
  {
    name: 'Reverse Grip Lat Pulldown',
    muscleGroup: 'Back',
    equipment: 'Cable',
    type: 'Compound',
    description: 'Supinated (underhand) grip pulldown. Greater bicep involvement and lower lat emphasis.',
    tips: [
      'Shoulder-width underhand grip on a straight bar.',
      'Pull to your lower chest, squeezing your lats hard at the bottom.',
      'The underhand grip recruits more bicep — use this to your advantage.',
      'Excellent for lower lat development.',
    ],
  },
  {
    name: 'Single Arm Lat Pulldown',
    muscleGroup: 'Back',
    equipment: 'Cable',
    type: 'Compound',
    description: 'Unilateral lat pulldown for addressing imbalances and maximising range of motion.',
    tips: [
      'Use a single D-handle attachment.',
      'Allow a full stretch at the top — let your shoulder blade elevate.',
      'Pull your elbow down and back toward your hip.',
      'Great for fixing left-right lat imbalances.',
    ],
  },
  {
    name: 'Seal Row',
    muscleGroup: 'Back',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Prone row on a high bench. Completely eliminates lower back and momentum from the equation.',
    tips: [
      'Lie face down on a bench high enough for arms to hang fully extended.',
      'Row the barbell or dumbbells straight up, squeezing shoulder blades together.',
      'Zero momentum possible — pure back isolation in a rowing pattern.',
      'One of the most honest rowing exercises you can do.',
    ],
  },
  {
    name: 'Inverted Row',
    muscleGroup: 'Back',
    equipment: 'Bodyweight',
    type: 'Compound',
    description: 'Bodyweight horizontal pull. Great entry point for those building up to pull ups.',
    tips: [
      'Set a barbell in a rack at hip height. Hang underneath with straight legs.',
      'Pull your chest to the bar, squeezing your shoulder blades together.',
      'The more horizontal your body, the harder it is.',
      'Elevate your feet on a bench for added difficulty.',
    ],
  },
  {
    name: 'Machine Row',
    muscleGroup: 'Back',
    equipment: 'Machine',
    type: 'Compound',
    description: 'Plate-loaded or selectorised rowing machine. Stable and allows heavy loading without lower back fatigue.',
    tips: [
      'Adjust the chest pad so your arms can fully extend at the start.',
      'Pull with your elbows, not your hands — think about squeezing your back.',
      'Great option when your lower back is fatigued from deadlifts or squats.',
      'Try single-arm work to address left-right imbalances.',
    ],
  },
  {
    name: 'Wide Grip Seated Cable Row',
    muscleGroup: 'Back',
    equipment: 'Cable',
    type: 'Compound',
    description: 'Seated cable row with a wide grip bar. Shifts emphasis to upper back, rhomboids, and rear delts.',
    tips: [
      'Use a wide lat pulldown bar on the low cable.',
      'Pull to your upper abdomen with elbows flared wider.',
      'Squeeze your shoulder blades together hard at the peak.',
      'Great for upper back thickness and posture.',
    ],
  },

  // ─── SHOULDERS ────────────────────────────────────────────────────────────
  {
    name: 'Barbell Overhead Press',
    muscleGroup: 'Shoulders',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'The premier overhead strength movement. Builds front delts, upper traps, and triceps.',
    tips: [
      'Grip slightly wider than shoulder-width. Elbows slightly forward (in front of the bar).',
      'Move your head back slightly as the bar passes your face, then move it back under.',
      'Press in a slight arc — bar travels slightly back as it rises overhead.',
      'Lock out fully at the top and shrug slightly to engage traps.',
      'Brace your core hard and avoid excessive lower back arch.',
    ],
  },
  {
    name: 'Seated Dumbbell Press',
    muscleGroup: 'Shoulders',
    equipment: 'Dumbbells',
    type: 'Compound',
    description: 'Seated overhead press with dumbbells. Allows a more natural pressing path.',
    tips: [
      'Let the dumbbells rotate naturally — palms face each other at the bottom, forward at the top.',
      'Don\'t lock out fully at the top to keep constant tension on the delts.',
      'Keep your lower back against the bench — don\'t arch excessively.',
      'Don\'t lower dumbbells below ear level — that\'s the bottom of the safe range.',
    ],
  },
  {
    name: 'Arnold Press',
    muscleGroup: 'Shoulders',
    equipment: 'Dumbbells',
    type: 'Compound',
    description: 'Dumbbell press with a rotational component. Hits all three delt heads through the rotation.',
    tips: [
      'Start with palms facing you (like a finished curl), end with palms forward at the top.',
      'The rotation happens as you press — smooth, coordinated movement.',
      'Targets more of the shoulder through a greater range than regular presses.',
      'Use slightly lighter weight than your regular dumbbell press due to the rotation.',
    ],
  },
  {
    name: 'Lateral Raises',
    muscleGroup: 'Shoulders',
    equipment: 'Dumbbells',
    type: 'Isolation',
    description: 'The best exercise for building lateral (medial) delt width. The key to broad shoulders.',
    tips: [
      'Lead with your elbows, not your hands. Think of lifting with the elbows.',
      'Stop at 90° (arms parallel to floor). Going higher shifts load to traps.',
      'Tilt dumbbells so the front edge points slightly down ("pouring a pitcher of water").',
      'Lean forward very slightly to shift emphasis from front delt to medial delt.',
      'Light weight with perfect form — this is a hypertrophy exercise, not a strength one.',
      'Slow eccentrics (3–4 seconds down) maximise time under tension.',
    ],
  },
  {
    name: 'Cable Lateral Raises',
    muscleGroup: 'Shoulders',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'Lateral raise with a cable provides constant tension — especially effective at the bottom of the range.',
    tips: [
      'Set the cable at floor level. Reach across your body to grab it.',
      'The cross-body reach gives a better stretch and pre-load at the bottom.',
      'Cable maintains tension throughout — unlike dumbbells, the hard part isn\'t just at the top.',
      'Great for drop sets and high-rep burnout at the end of shoulder day.',
    ],
  },
  {
    name: 'Front Raises',
    muscleGroup: 'Shoulders',
    equipment: 'Dumbbells',
    type: 'Isolation',
    description: 'Isolates the anterior (front) deltoid. Often overtrained since pressing already hits this heavily.',
    tips: [
      'Raise to eye level (90°) — going higher recruits traps and decreases delt stimulus.',
      'Controlled movement — no swinging or momentum.',
      'Your front delts already get plenty of work from pressing. Prioritise lateral raises instead.',
      'Can use plates, barbell, cables, or dumbbells.',
    ],
  },
  {
    name: 'Rear Delt Flyes',
    muscleGroup: 'Shoulders',
    equipment: 'Dumbbells',
    type: 'Isolation',
    description: 'Targets the posterior (rear) deltoid. Critical for shoulder balance and posture.',
    tips: [
      'Hinge forward until your torso is near horizontal.',
      'Lead with your elbows, keep a slight fixed bend throughout.',
      'Think about squeezing your shoulder blades together at the top.',
      'Use light weight and high reps (15–25). The rear delt is a small muscle.',
      'Can also be done lying face-down on an incline bench for stricter form.',
    ],
  },
  {
    name: 'Upright Rows',
    muscleGroup: 'Shoulders',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Compound movement for lateral delts and traps. Controversial due to shoulder impingement risk.',
    tips: [
      'Use a wide grip (wider than shoulder-width) to reduce impingement risk.',
      'Pull to chin height at most — don\'t need to go higher.',
      'If you feel shoulder impingement pain, switch to face pulls instead.',
      'Cable version can be more shoulder-friendly than barbell.',
    ],
  },
  {
    name: 'Push Press',
    muscleGroup: 'Shoulders',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Overhead press using leg drive to move heavier weight. Builds power and overhead strength.',
    tips: [
      'Slight dip of the knees, then explosive hip extension to generate leg drive.',
      'Once the bar clears your face, press it straight up to lockout.',
      'The leg drive allows 20–30% more weight than strict press — great for overloading.',
      'Lock out fully overhead, control the eccentric on the way back down.',
    ],
  },
  {
    name: 'Machine Shoulder Press',
    muscleGroup: 'Shoulders',
    equipment: 'Machine',
    type: 'Compound',
    description: 'Plate-loaded or selectorised machine press. Stable and great for beginners or high-rep sets.',
    tips: [
      'Adjust the seat so handles are at shoulder height.',
      'Good option for going to failure safely without a spotter.',
      'Try pressing with one arm at a time to identify and fix imbalances.',
    ],
  },

  {
    name: 'Single Arm Rear Delt Cable Fly',
    muscleGroup: 'Shoulders',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'Unilateral rear delt fly using a cable. Constant tension and allows you to work each side independently.',
    tips: [
      'Set the cable at shoulder height. Reach across your body to grab the handle.',
      'Pull the handle out and back in a wide arc, leading with your elbow.',
      'No need for heavy weight — focus on the squeeze and contraction.',
      'Great for fixing rear delt imbalances between sides.',
    ],
  },
  {
    name: 'Reverse Pec Deck',
    muscleGroup: 'Shoulders',
    equipment: 'Machine',
    type: 'Isolation',
    description: 'Machine rear delt fly. Sit facing the pad and push handles back to target the posterior deltoid.',
    tips: [
      'Adjust the seat so your arms are at shoulder height when gripping the handles.',
      'Lead with your elbows and squeeze your shoulder blades together at the end.',
      'Don\'t go too heavy — the rear delt is a small muscle that responds to control.',
      'Pause for 1–2 seconds at peak contraction for maximum effect.',
    ],
  },
  {
    name: 'Single Arm Reverse Pec Deck',
    muscleGroup: 'Shoulders',
    equipment: 'Machine',
    type: 'Isolation',
    description: 'Unilateral reverse pec deck for rear delts. Work each side independently to fix imbalances.',
    tips: [
      'Use one arm at a time on the reverse pec deck machine.',
      'Brace your free hand on the machine for stability.',
      'Focus on slow, controlled reps with a hard squeeze at the back.',
      'Start with your weaker side first.',
    ],
  },
  {
    name: 'Machine Lateral Raise',
    muscleGroup: 'Shoulders',
    equipment: 'Machine',
    type: 'Isolation',
    description: 'Lateral raise on a machine. Provides a fixed path and constant tension throughout the range.',
    tips: [
      'Adjust the seat so the pads sit on your outer arms just above the elbows.',
      'Push outward until arms are parallel to the floor.',
      'The machine path keeps tension on the medial delt throughout.',
      'Great for drop sets — easy to change weight quickly.',
    ],
  },
  {
    name: 'Dumbbell Rear Delt Fly (Incline)',
    muscleGroup: 'Shoulders',
    equipment: 'Dumbbells',
    type: 'Isolation',
    description: 'Rear delt fly lying face down on an incline bench. Eliminates momentum for strict isolation.',
    tips: [
      'Set an incline bench to about 30–45°. Lie face down with chest on the pad.',
      'Arms hang straight down. Raise them out to the sides in a wide arc.',
      'The bench eliminates all swinging — pure rear delt work.',
      'Use light weight and focus on squeezing the shoulder blades together.',
    ],
  },
  {
    name: 'Cable Front Raise',
    muscleGroup: 'Shoulders',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'Front raise using a cable for constant tension. Targets the anterior deltoid.',
    tips: [
      'Cable provides tension at the bottom where dumbbells are weakest.',
      'Raise to eye level — no higher needed.',
      'Can use a straight bar, rope, or single handle attachment.',
      'Front delts get lots of work from pressing — don\'t overdo isolation.',
    ],
  },
  {
    name: 'Single Arm Dumbbell Lateral Raise',
    muscleGroup: 'Shoulders',
    equipment: 'Dumbbells',
    type: 'Isolation',
    description: 'Unilateral lateral raise allowing you to lean away from a support for a greater range of motion.',
    tips: [
      'Hold a post or rack with your free hand and lean away slightly.',
      'The lean increases the range of motion at the bottom of the movement.',
      'Allows you to focus all your attention on one delt at a time.',
      'Great for building the mind-muscle connection with stubborn side delts.',
    ],
  },

  // ─── BICEPS ───────────────────────────────────────────────────────────────
  {
    name: 'Barbell Curl',
    muscleGroup: 'Biceps',
    equipment: 'Barbell',
    type: 'Isolation',
    description: 'Classic and effective bicep mass builder. Allows heavy loading in a stable position.',
    tips: [
      'Keep elbows pinned to your sides throughout the lift — don\'t let them drift forward.',
      'Supinate (rotate your wrists) as you curl for maximum peak contraction.',
      'Control the negative — lower slowly over 2–3 seconds.',
      'Avoid swinging your torso to heave the weight up.',
      'Full ROM: start from dead hang, curl until forearms are past vertical.',
    ],
  },
  {
    name: 'EZ Bar Curl',
    muscleGroup: 'Biceps',
    equipment: 'Barbell',
    type: 'Isolation',
    description: 'Angled grip reduces wrist stress. Still primarily biceps, with more brachialis involvement.',
    tips: [
      'The angled grip is easier on the wrists and elbows than straight bar.',
      'Still targets biceps effectively — use this if straight bar hurts your wrists.',
      'Same cues as barbell curl: elbows in, control the negative.',
    ],
  },
  {
    name: 'Dumbbell Curl',
    muscleGroup: 'Biceps',
    equipment: 'Dumbbells',
    type: 'Isolation',
    description: 'Allows supination through the full range — great for bicep peak development.',
    tips: [
      'Start with palms facing each other, rotate to palms up as you curl.',
      'Can be done alternating or simultaneously.',
      'Alternating allows you to focus on each arm and lift slightly heavier.',
      'Don\'t swing. If you can\'t keep your elbows pinned, reduce the weight.',
    ],
  },
  {
    name: 'Hammer Curls',
    muscleGroup: 'Biceps',
    equipment: 'Dumbbells',
    type: 'Isolation',
    description: 'Neutral grip curl. Heavily targets the brachialis, which sits under the bicep and adds thickness.',
    tips: [
      'Palms face each other (neutral grip) throughout the entire rep.',
      'Targets brachialis and brachioradialis more than regular curls.',
      'Great for arm thickness and elbow joint health.',
      'Can be done simultaneously, alternating, or across the body.',
    ],
  },
  {
    name: 'Preacher Curls',
    muscleGroup: 'Biceps',
    equipment: 'Barbell',
    type: 'Isolation',
    description: 'Bicep curl on a preacher bench — upper arm is braced and cannot swing.',
    tips: [
      'Don\'t fully extend at the bottom — stop just before full lockout to protect the distal tendon.',
      'The preacher bench eliminates momentum — every inch of the rep is pure bicep work.',
      'Slow eccentric (3–4 seconds) on the way down.',
      'EZ bar version is easier on the wrists.',
    ],
  },
  {
    name: 'Cable Curls',
    muscleGroup: 'Biceps',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'Constant tension throughout the full ROM. Excellent finishing movement.',
    tips: [
      'Cable provides tension at the bottom of the movement where dumbbells are weakest.',
      'Use a straight bar or rope attachment — both valid.',
      'Full ROM from full extension to full contraction.',
      'Great for high-rep pump sets at the end of a bicep session.',
    ],
  },
  {
    name: 'Concentration Curls',
    muscleGroup: 'Biceps',
    equipment: 'Dumbbells',
    type: 'Isolation',
    description: 'Complete isolation of the bicep with the elbow braced on your thigh.',
    tips: [
      'Brace your elbow on the inside of your thigh — eliminate ALL cheating.',
      'Slow, full ROM — feel every inch of the contraction.',
      'Squeeze hard at the top for peak contraction.',
      'Great for building the mind-muscle connection with your bicep.',
    ],
  },
  {
    name: 'Incline Dumbbell Curl',
    muscleGroup: 'Biceps',
    equipment: 'Dumbbells',
    type: 'Isolation',
    description: 'Performed on an incline bench. Maximises stretch on the long head of the bicep.',
    tips: [
      'Set the bench to 45–60°. Arms hang back behind your torso.',
      'The stretched position maximally loads the long head (outer peak) of the bicep.',
      'Don\'t swing your arms forward. Let them hang naturally.',
      'One of the best exercises for building the bicep peak.',
    ],
  },
  {
    name: 'Spider Curls',
    muscleGroup: 'Biceps',
    equipment: 'Barbell',
    type: 'Isolation',
    description: 'Prone on an incline bench, arms hang straight down. Eliminates all momentum.',
    tips: [
      'Lie face down on a 45° incline bench. Arms hang straight down.',
      'No way to use momentum — pure bicep isolation.',
      'Full ROM from dead hang to full contraction.',
      'Can use barbell, EZ bar, or dumbbells.',
    ],
  },
  {
    name: 'Reverse Curls',
    muscleGroup: 'Forearms',
    equipment: 'Barbell',
    type: 'Isolation',
    description: 'Overhand grip curl that develops the brachioradialis and forearm extensors.',
    tips: [
      'Overhand (pronated) grip on the barbell.',
      'Elbow stays pinned to the side same as regular curls.',
      'Lighter weight than regular curls is normal — the leverage is significantly different.',
      'Great for forearm development and overall elbow health.',
    ],
  },

  {
    name: 'Bayesian Cable Curl',
    muscleGroup: 'Biceps',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'Cable curl with the arm behind the body. Maximises long head stretch for peak development.',
    tips: [
      'Set the cable low and face away from the machine.',
      'Your arm starts behind your torso — this fully stretches the long head.',
      'Curl forward and up, squeezing at the top.',
      'One of the best exercises for building the bicep peak.',
    ],
  },
  {
    name: 'Cross Body Hammer Curl',
    muscleGroup: 'Biceps',
    equipment: 'Dumbbells',
    type: 'Isolation',
    description: 'Hammer curl across the body rather than straight up. Emphasises the brachialis and forearm.',
    tips: [
      'Neutral grip — curl the dumbbell across your body toward the opposite shoulder.',
      'Keep your elbow pinned to your side throughout.',
      'The cross-body angle hits the brachialis from a different angle than standard hammer curls.',
      'Alternate arms for each rep.',
    ],
  },
  {
    name: 'Machine Bicep Curl',
    muscleGroup: 'Biceps',
    equipment: 'Machine',
    type: 'Isolation',
    description: 'Selectorised or plate-loaded bicep curl machine. Fixed path ensures strict form.',
    tips: [
      'Adjust the seat so your elbows align with the machine\'s pivot point.',
      'The fixed path eliminates all cheating — pure bicep isolation.',
      'Great for drop sets and training to failure safely.',
      'Focus on slow eccentrics for maximum growth stimulus.',
    ],
  },
  {
    name: 'Overhead Cable Curl',
    muscleGroup: 'Biceps',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'Curl with arms extended out to the sides at shoulder height. Classic "front double bicep" pose curl.',
    tips: [
      'Set both cables at shoulder height. Stand in the centre.',
      'Curl the handles toward your ears — like hitting a front double bicep pose.',
      'Keep your elbows fixed at shoulder height throughout.',
      'Great for the peak contraction and bicep shape.',
    ],
  },
  {
    name: 'Single Arm Preacher Curl',
    muscleGroup: 'Biceps',
    equipment: 'Dumbbells',
    type: 'Isolation',
    description: 'Unilateral preacher curl allowing full focus on each arm independently.',
    tips: [
      'Same setup as regular preacher curl but one arm at a time.',
      'Use your free hand to spot yourself if needed on the last few reps.',
      'Great for identifying and fixing bicep strength imbalances.',
      'Don\'t fully extend at the bottom — protect the distal tendon.',
    ],
  },

  // ─── TRICEPS ──────────────────────────────────────────────────────────────
  {
    name: 'Tricep Pushdowns',
    muscleGroup: 'Triceps',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'One of the most popular tricep exercises. The rope attachment allows maximum ROM.',
    tips: [
      'Keep elbows pinned to your sides and stationary throughout.',
      'Use the rope attachment — split the rope apart at the bottom for peak contraction.',
      'Full extension at the bottom, full stretch at the top.',
      'Don\'t lean forward and use bodyweight — keep it strict.',
    ],
  },
  {
    name: 'Skull Crushers',
    muscleGroup: 'Triceps',
    equipment: 'Barbell',
    type: 'Isolation',
    description: 'Heavy tricep isolation with barbell or EZ bar. Excellent for mass building.',
    tips: [
      'Lower the bar toward your forehead or slightly behind your head — not your throat.',
      'Keep elbows pointing straight at the ceiling throughout — don\'t let them flare wide.',
      'EZ bar version is easier on the wrists and elbows.',
      'Slow eccentric (3 seconds down) for maximum tricep time under tension.',
    ],
  },
  {
    name: 'Overhead Tricep Extension',
    muscleGroup: 'Triceps',
    equipment: 'Dumbbells',
    type: 'Isolation',
    description: 'The only position where the long head of the tricep is fully stretched. Critical for full development.',
    tips: [
      'Keep elbows close to your ears throughout — don\'t let them flare wide.',
      'Full ROM is essential: fully extend at the top, deep stretch at the bottom.',
      'The long head is ONLY fully stretched when the arm is overhead — prioritise this.',
      'Can be done with dumbbell, cable, or barbell.',
    ],
  },
  {
    name: 'Tricep Dips',
    muscleGroup: 'Triceps',
    equipment: 'Bodyweight',
    type: 'Compound',
    description: 'Parallel bar dips focused on triceps by keeping the torso upright.',
    tips: [
      'Stay upright (vertical torso) to target triceps over chest.',
      'Elbows stay relatively tucked — don\'t flare them wide.',
      'Full ROM: upper arms parallel to the floor at the bottom.',
      'Add a weight belt once bodyweight becomes easy.',
    ],
  },
  {
    name: 'Close Grip Bench Press',
    muscleGroup: 'Triceps',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Bench press variation with hands inside shoulder-width. Prioritises triceps.',
    tips: [
      'Shoulder-width grip or slightly narrower — not super narrow (which stresses wrists).',
      'Tuck elbows to 45° against your torso throughout.',
      'Same bar path as regular bench, just narrower.',
      'You can overload the triceps significantly with this movement.',
    ],
  },
  {
    name: 'Tricep Kickbacks',
    muscleGroup: 'Triceps',
    equipment: 'Dumbbells',
    type: 'Isolation',
    description: 'Hinge forward and extend the arm back. Isolation movement at peak contraction.',
    tips: [
      'Hinge your torso forward until it\'s nearly parallel to the floor.',
      'Upper arm stays parallel to the floor — only the forearm moves.',
      'Pause and squeeze hard at full extension.',
      'Use light weight — the leverage is very challenging.',
    ],
  },
  {
    name: 'Cable Overhead Tricep Extension',
    muscleGroup: 'Triceps',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'Overhead extension using cable for constant tension. Best for long head development.',
    tips: [
      'Set the cable low or behind you. Face away from the machine.',
      'Hands overhead, elbows close to ears.',
      'Extension and full stretch — the long head needs full overhead position.',
      'Better than dumbbell overhead extension due to consistent tension.',
    ],
  },
  {
    name: 'Diamond Push Ups',
    muscleGroup: 'Triceps',
    equipment: 'Bodyweight',
    type: 'Compound',
    description: 'Push up with hands close together in a diamond shape. Heavy tricep and inner chest emphasis.',
    tips: [
      'Form a diamond/triangle with your thumbs and index fingers under your chest.',
      'Elbows track back toward your torso — not flaring out wide.',
      'Harder than regular push ups — scale with elevated hands if needed.',
      'Great finisher at the end of a tricep session.',
    ],
  },
  {
    name: 'JM Press',
    muscleGroup: 'Triceps',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Hybrid between skull crushers and close grip bench press. Very heavy tricep builder.',
    tips: [
      'Takes a narrow grip on the barbell.',
      'Lower the bar toward your neck/throat while elbows come forward at the bottom.',
      'Elbows flare out slightly as the bar descends — this is intentional.',
      'Advanced movement — master skull crushers and close grip bench first.',
    ],
  },
  {
    name: 'Tate Press',
    muscleGroup: 'Triceps',
    equipment: 'Dumbbells',
    type: 'Isolation',
    description: 'Dumbbells lowered toward the chest with elbows flared. Great inner/lateral head focus.',
    tips: [
      'Lie on a flat bench with dumbbells pressed above your chest.',
      'Lower dumbbells by bending only the elbows — flare them out to the sides.',
      'Touch dumbbells to your chest, then press back up.',
      'Unique movement angle that many tricep exercises miss.',
    ],
  },

  {
    name: 'Single Arm Tricep Pushdown',
    muscleGroup: 'Triceps',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'Unilateral cable pushdown. Allows you to address tricep imbalances and focus on each arm.',
    tips: [
      'Use a single D-handle or no attachment (just the cable ball stop).',
      'Keep your elbow pinned to your side — only your forearm moves.',
      'Full extension at the bottom with a hard squeeze.',
      'Start with your weaker arm first.',
    ],
  },
  {
    name: 'Bench Dips',
    muscleGroup: 'Triceps',
    equipment: 'Bodyweight',
    type: 'Compound',
    description: 'Tricep dip using a bench behind you. Easier to scale than parallel bar dips.',
    tips: [
      'Hands on a bench behind you, feet on the floor (or elevated on another bench).',
      'Lower until your upper arms are parallel to the floor.',
      'Don\'t go too deep — excessive depth stresses the shoulder joint.',
      'Add a plate on your lap for extra resistance.',
    ],
  },
  {
    name: 'Machine Tricep Extension',
    muscleGroup: 'Triceps',
    equipment: 'Machine',
    type: 'Isolation',
    description: 'Selectorised tricep extension machine. Safe and easy to train to failure.',
    tips: [
      'Adjust the seat so your elbows align with the machine\'s pivot point.',
      'Full extension at the bottom, full stretch at the top.',
      'Great for drop sets — easy to change weight quickly.',
      'Focus on slow, controlled reps rather than heavy weight.',
    ],
  },

  // ─── QUADS ────────────────────────────────────────────────────────────────
  {
    name: 'Barbell Back Squat',
    muscleGroup: 'Quads',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'The king of lower body exercises. The most effective movement for overall leg development and strength.',
    tips: [
      'Bar sits on the shelf of your upper traps (high bar) or rear delts (low bar).',
      'Hip-width stance, toes pointed out 15–30°.',
      'Knees track over your toes throughout — don\'t let them cave in.',
      'Squat until your hips are at or below parallel for full quad activation.',
      'Keep your chest up and core braced like you\'re about to be punched.',
      'Drive through your whole foot — don\'t let your heels rise.',
    ],
  },
  {
    name: 'Front Squat',
    muscleGroup: 'Quads',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Quad-dominant squat with the bar on the front of the shoulders. More upright torso than back squat.',
    tips: [
      'Clean grip (fingers under the bar, elbows HIGH) or cross-arm grip — both work.',
      'Elbows must stay high throughout to keep the bar on your front delts.',
      'More upright torso means more direct quad stimulus and less lower back stress.',
      'Harder on wrists at first — work on wrist flexibility alongside this lift.',
    ],
  },
  {
    name: 'Leg Press',
    muscleGroup: 'Quads',
    equipment: 'Machine',
    type: 'Compound',
    description: 'Machine squat variant. Allows heavy loading without the skill requirement of barbell squats.',
    tips: [
      'Don\'t lock your knees at the top — leave a slight bend to protect the joint.',
      'High foot placement (upper part of platform) recruits more glutes and hamstrings.',
      'Low foot placement (lower on platform) = more quad dominant.',
      'Full ROM: lower until your hips start to come off the seat.',
      'Don\'t block out your knees with your hands — let them track naturally.',
    ],
  },
  {
    name: 'Leg Extension',
    muscleGroup: 'Quads',
    equipment: 'Machine',
    type: 'Isolation',
    description: 'Pure quad isolation. Great as a finishing or warm-up movement.',
    tips: [
      'Pause and squeeze hard at the top for 1–2 seconds.',
      'Control the eccentric — lower slowly over 3–4 seconds.',
      'No momentum — smooth, controlled movement throughout.',
      'Single-leg version is great for identifying and fixing imbalances.',
    ],
  },
  {
    name: 'Lunges',
    muscleGroup: 'Quads',
    equipment: 'Dumbbells',
    type: 'Compound',
    description: 'Unilateral leg movement that trains balance, stability, and strength simultaneously.',
    tips: [
      'Long stride = more glute emphasis. Short stride = more quad emphasis.',
      'Front knee should track over your toes — don\'t let it cave inward.',
      'Keep your torso upright throughout — don\'t lean forward excessively.',
      'Walking lunges or stationary reverse lunges are great for beginners.',
    ],
  },
  {
    name: 'Bulgarian Split Squat',
    muscleGroup: 'Quads',
    equipment: 'Dumbbells',
    type: 'Compound',
    description: 'Rear-foot elevated split squat. One of the most effective single-leg exercises.',
    tips: [
      'Rear foot on a bench or box. Front foot far enough forward to allow a full dip.',
      'Torso more upright = more quad. Torso leaning forward = more glute.',
      'Lower your rear knee toward the floor without touching it.',
      'Start light — balance is a skill to develop. Weight can increase significantly over time.',
      'Possibly the most effective exercise for single-leg strength and hypertrophy.',
    ],
  },
  {
    name: 'Hack Squat',
    muscleGroup: 'Quads',
    equipment: 'Machine',
    type: 'Compound',
    description: 'Machine squat that allows a large ROM and significant quad loading without lower back stress.',
    tips: [
      'Go deep — full ROM on the hack squat is highly effective for quads.',
      'Narrow vs wide foot placement changes the emphasis (narrow = more outer quad).',
      'The machine supports your back so you can push your quads harder.',
      'Great alternative to squats if lower back issues limit you.',
    ],
  },
  {
    name: 'Goblet Squat',
    muscleGroup: 'Quads',
    equipment: 'Dumbbells',
    type: 'Compound',
    description: 'Squat while holding a dumbbell or kettlebell at your chest. Perfect for technique and mobility.',
    tips: [
      'Hold the dumbbell vertically by one end at your chest.',
      'The counterbalance helps you sit back and stay upright simultaneously.',
      'Perfect for learning squat mechanics — feel like you\'re squatting around the weight.',
      'Great mobility exercise too — use body weight or very light weight for deep squats.',
    ],
  },
  {
    name: 'Step Ups',
    muscleGroup: 'Quads',
    equipment: 'Dumbbells',
    type: 'Compound',
    description: 'Functional unilateral lower body movement. Builds hip strength and balance.',
    tips: [
      'Use a box height that puts your thigh parallel or slightly above when your foot is on it.',
      'Drive through the heel of the elevated foot — not the back foot pushing off.',
      'Control the descent — don\'t just drop off the box.',
      'Hold dumbbells at your sides for added resistance.',
    ],
  },
  {
    name: 'Sissy Squat',
    muscleGroup: 'Quads',
    equipment: 'Bodyweight',
    type: 'Isolation',
    description: 'Extreme quad isolation movement. Knee goes far forward while hips stay back.',
    tips: [
      'Use a sissy squat machine or hold something for balance.',
      'Lean back as your knees come forward — this is unique to this exercise.',
      'Feel the extreme quad stretch at the bottom.',
      'Advanced movement — build base quad strength first with squats and leg press.',
    ],
  },

  {
    name: 'Smith Machine Squat',
    muscleGroup: 'Quads',
    equipment: 'Machine',
    type: 'Compound',
    description: 'Squat on the Smith machine. Fixed bar path allows you to focus on the quads with less stabiliser demand.',
    tips: [
      'Feet slightly forward of the bar allows a more upright torso and more quad focus.',
      'The fixed path means less stabiliser work — great for isolating quads.',
      'Safe to train to failure without a spotter.',
      'Can also be used for close-stance or wide-stance squat variations.',
    ],
  },
  {
    name: 'Walking Lunges',
    muscleGroup: 'Quads',
    equipment: 'Dumbbells',
    type: 'Compound',
    description: 'Forward-stepping lunges that travel across the floor. Builds leg strength, balance, and conditioning.',
    tips: [
      'Take a long stride and lower your rear knee toward the ground.',
      'Drive through the front heel to step forward into the next rep.',
      'Keep your torso upright — don\'t lean forward excessively.',
      'Hold dumbbells at your sides or a barbell on your back.',
    ],
  },
  {
    name: 'Reverse Lunges',
    muscleGroup: 'Quads',
    equipment: 'Dumbbells',
    type: 'Compound',
    description: 'Step backward into a lunge. Easier on the knees than forward lunges and more glute emphasis.',
    tips: [
      'Step back and lower your rear knee toward the floor.',
      'Front shin stays more vertical than forward lunges — less knee stress.',
      'Drive through the front heel to return to standing.',
      'Great alternative if forward lunges bother your knees.',
    ],
  },
  {
    name: 'Pendulum Squat',
    muscleGroup: 'Quads',
    equipment: 'Machine',
    type: 'Compound',
    description: 'Machine squat with a pendulum arc. Provides constant tension and a unique loading angle for the quads.',
    tips: [
      'The pendulum arc keeps tension on the quads throughout the full range.',
      'Shoulder pads keep you locked in — no balance required.',
      'Go deep for maximum quad stretch and activation.',
      'Great alternative to hack squat with a slightly different feel.',
    ],
  },
  {
    name: 'Belt Squat',
    muscleGroup: 'Quads',
    equipment: 'Machine',
    type: 'Compound',
    description: 'Squat with the load attached to a belt around your hips. Zero spinal compression.',
    tips: [
      'The load hangs from your hips, not your shoulders — no spinal loading.',
      'Perfect for those with back issues who still want to squat heavy.',
      'Can use a dedicated belt squat machine or a landmine setup.',
      'Focus on sitting deep and driving through your heels.',
    ],
  },
  {
    name: 'Single Leg Leg Press',
    muscleGroup: 'Quads',
    equipment: 'Machine',
    type: 'Compound',
    description: 'Unilateral leg press to address strength imbalances between legs.',
    tips: [
      'Use about 40–50% of your normal two-leg weight to start.',
      'Same foot placement rules apply — low for quads, high for glutes.',
      'Great for identifying which leg is weaker.',
      'Control the eccentric — don\'t let the sled drop.',
    ],
  },
  {
    name: 'Single Leg Leg Extension',
    muscleGroup: 'Quads',
    equipment: 'Machine',
    type: 'Isolation',
    description: 'Unilateral leg extension to identify and fix quad strength imbalances.',
    tips: [
      'Same technique as regular leg extensions but one leg at a time.',
      'Start with your weaker leg first.',
      'Pause and squeeze hard at full extension.',
      'Great for rehab and prehab of the knee joint.',
    ],
  },

  // ─── HAMSTRINGS ───────────────────────────────────────────────────────────
  {
    name: 'Stiff Leg Deadlift',
    muscleGroup: 'Hamstrings',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Similar to RDL but the bar starts from the floor. Greater range and lower back involvement.',
    tips: [
      'Legs are nearly straight (not locked) throughout the movement.',
      'Bar starts from the floor — lower back is more involved than RDL.',
      'Feel the hamstring stretch at the bottom as the primary cue.',
      'Keep the bar close to your shins on the way up.',
    ],
  },
  {
    name: 'Lying Leg Curl',
    muscleGroup: 'Hamstrings',
    equipment: 'Machine',
    type: 'Isolation',
    description: 'Prone hamstring curl machine. Excellent isolation with minimal lower back involvement.',
    tips: [
      'Don\'t let your hips rise off the pad at the bottom.',
      'Full ROM: legs almost fully straight to fully curled.',
      'Pause and squeeze at the top for peak contraction.',
      'Slow eccentric — 3–4 seconds lowering for maximum hypertrophy.',
    ],
  },
  {
    name: 'Seated Leg Curl',
    muscleGroup: 'Hamstrings',
    equipment: 'Machine',
    type: 'Isolation',
    description: 'Hamstring curl in a seated position — targets the distal hamstrings near the knee.',
    tips: [
      'Slightly better for the lower hamstrings near the knee than lying curl.',
      'Full ROM and squeeze at peak contraction.',
      'Back pressed firmly against the pad throughout.',
      'Use slow eccentrics for maximum development.',
    ],
  },
  {
    name: 'Good Mornings',
    muscleGroup: 'Hamstrings',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Bar on the back, hip hinge movement. Builds hamstring and lower back strength.',
    tips: [
      'Same hip hinge as RDL but bar is on your upper back.',
      'Start very light — this movement puts significant stress on the lower back.',
      'Keep a neutral spine throughout.',
      'Great supplementary lift for squats and deadlifts.',
    ],
  },
  {
    name: 'Nordic Curl',
    muscleGroup: 'Hamstrings',
    equipment: 'Bodyweight',
    type: 'Compound',
    description: 'Advanced bodyweight hamstring exercise. One of the best for injury prevention.',
    tips: [
      'Kneel with ankles secured (under a barbell, in a machine, or partner holds).',
      'Lower yourself forward as slowly as possible, resisting with your hamstrings.',
      'Use your hands to push up from the floor at the bottom.',
      'Work up to this gradually — most people need band assistance to start.',
      'Studies show this significantly reduces hamstring injury risk in athletes.',
    ],
  },
  {
    name: 'Glute-Ham Raise',
    muscleGroup: 'Hamstrings',
    equipment: 'Machine',
    type: 'Compound',
    description: 'Done on a GHR machine — trains both knee flexion and hip extension simultaneously.',
    tips: [
      'Requires a GHR (glute-ham raise) machine.',
      'Start in a planked position, lower forward and curl back up.',
      'Trains hamstring through both its functions: knee flexion and hip extension.',
      'Very challenging — use band assistance to scale.',
    ],
  },
  {
    name: 'Single-Leg RDL',
    muscleGroup: 'Hamstrings',
    equipment: 'Dumbbells',
    type: 'Compound',
    description: 'Unilateral RDL. Challenges balance, identifies imbalances, and deepens the hamstring stretch.',
    tips: [
      'Hinge on one leg, letting the other leg extend behind for counterbalance.',
      'Keep hips square — don\'t let the hip of your free leg open up.',
      'Hold one or two dumbbells.',
      'Great for correcting left-right hamstring imbalances.',
    ],
  },

  {
    name: 'Dumbbell Romanian Deadlift',
    muscleGroup: 'Hamstrings',
    equipment: 'Dumbbells',
    type: 'Compound',
    description: 'RDL with dumbbells. Allows a more natural hand path and is easier to set up than barbell.',
    tips: [
      'Same hip hinge pattern as barbell RDL — push your hips back.',
      'Dumbbells travel close to your legs, just like a barbell would.',
      'Slightly more freedom of movement than barbell — can rotate wrists naturally.',
      'Great option when barbells are busy or for lighter, high-rep work.',
    ],
  },
  {
    name: 'Standing Leg Curl',
    muscleGroup: 'Hamstrings',
    equipment: 'Machine',
    type: 'Isolation',
    description: 'Single-leg hamstring curl done standing. Allows you to work each leg independently.',
    tips: [
      'Stand on one leg, curl the other leg behind you against the pad.',
      'Brace yourself on the handles and keep your hips square.',
      'Squeeze hard at the top and lower slowly.',
      'Great for fixing left-right hamstring imbalances.',
    ],
  },
  {
    name: 'Cable Leg Curl',
    muscleGroup: 'Hamstrings',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'Hamstring curl using a cable ankle attachment. Constant tension throughout the range of motion.',
    tips: [
      'Attach an ankle strap to a low cable. Face the machine.',
      'Curl your heel toward your glute against the cable resistance.',
      'The cable provides tension at the stretched position where machines often don\'t.',
      'Great for a pump and can be done anywhere there\'s a cable machine.',
    ],
  },

  // ─── GLUTES ───────────────────────────────────────────────────────────────
  {
    name: 'Hip Thrust',
    muscleGroup: 'Glutes',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'The most effective exercise for glute hypertrophy. Loads the glutes through full hip extension.',
    tips: [
      'Shoulders rest on a bench, feet flat on the floor, bar over hips with a foam pad.',
      'At the top: thighs parallel to the floor, knees bent at 90°.',
      'Squeeze your glutes hard at the top — hold for 1 second.',
      'Don\'t hyperextend the lower back at the top. Tuck your pelvis slightly.',
      'Feet farther from your body = more glute. Closer = more quad.',
    ],
  },
  {
    name: 'Glute Bridge',
    muscleGroup: 'Glutes',
    equipment: 'Bodyweight',
    type: 'Compound',
    description: 'Floor-based version of the hip thrust. Beginner-friendly with less ROM.',
    tips: [
      'Lie on your back, knees bent, feet flat on the floor.',
      'Drive your hips up by squeezing your glutes hard.',
      'Hold at the top for 2 seconds.',
      'Single-leg version is a great progression for unilateral strength.',
      'Add a dumbbell or plate across your hips for resistance.',
    ],
  },
  {
    name: 'Cable Kickbacks',
    muscleGroup: 'Glutes',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'Isolated glute extension using a cable machine. Great finisher for glute hypertrophy.',
    tips: [
      'Cable ankle attachment at the low pulley. Hold the frame for support.',
      'Drive your heel back AND slightly upward — glute extension, not just hip extension.',
      'Keep a slight bend in the working knee.',
      'Don\'t rotate your hips — control the movement.',
      'Squeeze the glute hard at full extension.',
    ],
  },
  {
    name: 'Sumo Deadlift',
    muscleGroup: 'Glutes',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Wide stance deadlift. More hip and glute dominant than conventional deadlift.',
    tips: [
      'Stance 2× shoulder-width or wider with significant toe flare.',
      'Grip is narrow — inside your legs, shoulder-width or closer.',
      'Drive your knees out over your toes throughout the pull.',
      'More vertical torso means less lower back stress than conventional.',
      'Great for those with proportions that suit a wider stance.',
    ],
  },
  {
    name: 'Cable Pull-Through',
    muscleGroup: 'Glutes',
    equipment: 'Cable',
    type: 'Compound',
    description: 'Standing hip thrust pattern using a cable. Great teaching tool for hip hinge mechanics.',
    tips: [
      'Face away from the cable, with the cable between your legs.',
      'Hinge at the hips, letting the cable pull your hands back and through your legs.',
      'Drive your hips forward and squeeze your glutes at the top.',
      'Very similar to a kettlebell swing pattern.',
    ],
  },
  {
    name: 'Hip Abduction Machine',
    muscleGroup: 'Glutes',
    equipment: 'Machine',
    type: 'Isolation',
    description: 'Targets glute medius and minimus — essential for hip stability and glute fullness.',
    tips: [
      'Often neglected but important for complete glute development.',
      'Don\'t lean forward or use your torso to move the weight.',
      'Slow controlled movement — feel the outer glute doing the work.',
      'High reps (15–25) work well here.',
    ],
  },

  {
    name: 'Hip Thrust Machine',
    muscleGroup: 'Glutes',
    equipment: 'Machine',
    type: 'Compound',
    description: 'Dedicated hip thrust machine. Easier setup than barbell and consistent resistance.',
    tips: [
      'Adjust the pad so it sits on your hips comfortably.',
      'Same cues as barbell hip thrust: squeeze glutes hard at the top.',
      'Don\'t hyperextend — stop when your hips are fully extended.',
      'Much faster setup than barbell — great for supersets.',
    ],
  },
  {
    name: 'Single Leg Hip Thrust',
    muscleGroup: 'Glutes',
    equipment: 'Bodyweight',
    type: 'Compound',
    description: 'Unilateral hip thrust to address glute imbalances and increase difficulty.',
    tips: [
      'Same setup as regular hip thrust but one foot stays on the floor.',
      'The non-working leg can be held in the air or rested on the working knee.',
      'Start with bodyweight — single leg is much harder than it sounds.',
      'Great for fixing left-right glute imbalances.',
    ],
  },
  {
    name: 'Curtsy Lunge',
    muscleGroup: 'Glutes',
    equipment: 'Dumbbells',
    type: 'Compound',
    description: 'Lunge where the rear foot crosses behind the front leg. Targets the glute medius and outer glute.',
    tips: [
      'Step one foot behind and across your body, like a curtsy.',
      'Lower until your front thigh is near parallel.',
      'The crossover angle hits the glute medius harder than standard lunges.',
      'Hold dumbbells at your sides for added resistance.',
    ],
  },
  {
    name: 'Cable Hip Abduction',
    muscleGroup: 'Glutes',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'Standing hip abduction using a cable ankle strap. Targets the glute medius with constant tension.',
    tips: [
      'Attach an ankle strap to a low cable. Stand sideways to the machine.',
      'Push your outside leg away from the cable in a controlled arc.',
      'Don\'t lean excessively — keep your torso relatively upright.',
      'Great for targeting the outer glute and improving hip stability.',
    ],
  },

  // ─── CORE ─────────────────────────────────────────────────────────────────
  {
    name: 'Plank',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    type: 'Isometric',
    description: 'Foundational core stability exercise. Trains anti-extension and whole-body tension.',
    tips: [
      'Neutral spine — don\'t let your hips sag or pike up.',
      'Squeeze your glutes, brace your abs, and engage your quads.',
      'Breathe normally — holding your breath defeats the purpose.',
      'Focus on quality and perfect tension, not duration.',
      'Progress to harder variations: RKC plank, weighted plank, plank with reach.',
    ],
  },
  {
    name: 'Side Plank',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    type: 'Isometric',
    description: 'Anti-lateral flexion exercise. Targets the obliques and quadratus lumborum.',
    tips: [
      'Stack feet or stagger them for the easier version.',
      'Hip doesn\'t sag — straight line from head to heels.',
      'Reach your top arm toward the ceiling for more activation.',
      'Progress to side plank with hip dips or reach-throughs.',
    ],
  },
  {
    name: 'Crunches',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    type: 'Isolation',
    description: 'Classic abdominal flexion exercise.',
    tips: [
      'Don\'t pull on your neck — fingertips behind your ears, not clasped.',
      'Focus on shortening the distance between your lower ribs and your hips.',
      'Controlled movement — not about speed or momentum.',
      'Exhale forcefully at the top of each rep.',
    ],
  },
  {
    name: 'Leg Raises',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    type: 'Isolation',
    description: 'Targets the lower abs and hip flexors through leg raises.',
    tips: [
      'Keep your lower back pressed firmly into the floor.',
      'Slow, controlled descent — the eccentric is where the work happens.',
      'Bend your knees to make this easier; straight legs is harder.',
      'Stop just before your feet touch the floor to maintain tension.',
    ],
  },
  {
    name: 'Hanging Leg Raises',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    type: 'Isolation',
    description: 'Challenging core exercise from a dead hang. Builds serious abdominal strength.',
    tips: [
      'Dead hang from a bar, then raise legs to perpendicular or above.',
      'No swinging — control the movement with your abs, not momentum.',
      'Tucked knees is the beginner version; straight legs is advanced.',
      'Posterior pelvic tilt at the top for maximum abs contraction.',
    ],
  },
  {
    name: 'Russian Twists',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    type: 'Isolation',
    description: 'Rotational core exercise that targets the obliques.',
    tips: [
      'Feet elevated makes this harder; feet on floor is the easier start.',
      'Rotate from your torso, not just your arms.',
      'Touch the floor (or weight) on each side at the end of every rep.',
      'Add a plate, medicine ball, or dumbbell for resistance.',
    ],
  },
  {
    name: 'Cable Crunches',
    muscleGroup: 'Core',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'Weighted crunch using a cable for resistance. Allows progressive overload on the abs.',
    tips: [
      'Kneel with a rope attachment pulled from above.',
      'Curl/crunch DOWN, rounding your spine — don\'t just pull with your arms.',
      'Let your spine fully stretch and extend at the top of each rep.',
      'This is one of the best ways to progressively overload the abs.',
    ],
  },
  {
    name: 'Ab Wheel Rollout',
    muscleGroup: 'Core',
    equipment: 'Equipment',
    type: 'Compound',
    description: 'Anti-extension core exercise. One of the most challenging and effective ab movements.',
    tips: [
      'Start on your knees. Roll out as far as you can while keeping your lower back from arching.',
      'If your lower back drops, you\'ve gone too far — pull back.',
      'Progress to standing rollouts once knee version is easy.',
      'Builds incredible anti-extension core strength essential for big lifts.',
    ],
  },
  {
    name: 'Dragon Flag',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    type: 'Compound',
    description: 'Advanced full-body core movement. The entire body from shoulders down stays rigid.',
    tips: [
      'Lie on a bench, grip firmly behind your head.',
      'Raise your entire body up on your shoulder blades — only shoulders stay on bench.',
      'Lower slowly in a controlled, straight line.',
      'Work up through progressions (tuck, single-leg, then full).',
    ],
  },
  {
    name: 'Dead Bug',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    type: 'Isolation',
    description: 'Spine-safe core stability exercise. Excellent for building anti-extension control.',
    tips: [
      'Lie on your back, lower back pressed firmly into the floor throughout.',
      'Arms up, knees at 90°. Lower opposite arm and leg toward the floor.',
      'Never let your lower back lose contact with the floor.',
      'Slow, controlled movement — the challenge is maintaining spinal stability.',
    ],
  },
  {
    name: 'Pallof Press',
    muscleGroup: 'Core',
    equipment: 'Cable',
    type: 'Isometric',
    description: 'Anti-rotation core exercise. You resist twisting, building lateral core stability.',
    tips: [
      'Stand sideways to the cable/band. Hold the handle at your chest.',
      'Press straight out from your chest and hold for 2–3 seconds.',
      'The cable tries to rotate you — resist it completely with your core.',
      'Great for athletic carry-over and protecting the spine under load.',
    ],
  },
  {
    name: 'Hollow Body Hold',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    type: 'Isometric',
    description: 'Foundational gymnastics core exercise. Builds deep abdominal tension.',
    tips: [
      'On your back: lower back pressed to floor, arms extended overhead, legs straight and raised.',
      'The lower your legs, the harder the challenge.',
      'Point your toes and keep every muscle tight.',
      'Fundamental to gymnastics — massive carry-over to all lifts.',
    ],
  },

  {
    name: 'Woodchoppers',
    muscleGroup: 'Core',
    equipment: 'Cable',
    type: 'Compound',
    description: 'Rotational core exercise using a cable. Trains the obliques through a powerful chopping motion.',
    tips: [
      'Set the cable high for downward chops or low for upward chops.',
      'Rotate through your torso — your arms are just connecting you to the cable.',
      'Feet stay planted, hips stay relatively stable — the rotation is in your core.',
      'Great for developing rotational power for sports.',
    ],
  },
  {
    name: 'Bicycle Crunches',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    type: 'Isolation',
    description: 'Crunch with a twisting motion and alternating leg movement. Targets both abs and obliques.',
    tips: [
      'Opposite elbow to opposite knee as you crunch and twist.',
      'Fully extend the non-working leg — don\'t let it drop to the floor.',
      'Go slow — this is not about speed, it\'s about contraction.',
      'Keep your lower back pressed into the floor throughout.',
    ],
  },
  {
    name: 'Decline Sit Ups',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    type: 'Isolation',
    description: 'Sit ups on a decline bench. The angle increases the difficulty and range of motion.',
    tips: [
      'Hook your feet under the pads on a decline bench.',
      'Don\'t use momentum — control the movement with your abs.',
      'Hold a plate or dumbbell at your chest for added resistance.',
      'Don\'t go too steep — a moderate decline is plenty challenging.',
    ],
  },

  // ─── CALVES ───────────────────────────────────────────────────────────────
  {
    name: 'Standing Calf Raises',
    muscleGroup: 'Calves',
    equipment: 'Machine',
    type: 'Isolation',
    description: 'Primary calf builder targeting the gastrocnemius. Full stretch is critical for growth.',
    tips: [
      'Full ROM is non-negotiable — a deep stretch at the bottom drives most of the growth.',
      'Calves respond well to high reps (15–25) due to their daily workload.',
      'Pause 1 second at the full stretch AND 1 second at peak contraction.',
      'Single-leg raises are harder and address imbalances effectively.',
    ],
  },
  {
    name: 'Seated Calf Raises',
    muscleGroup: 'Calves',
    equipment: 'Machine',
    type: 'Isolation',
    description: 'Specifically targets the soleus (the deeper calf muscle beneath the gastrocnemius).',
    tips: [
      'The seated position bends the knee, which relaxes the gastroc and isolates the soleus.',
      'Same principles: full stretch at the bottom is essential.',
      'Soleus responds well to heavier weight and slower tempos.',
      'Train both seated and standing to fully develop the calf complex.',
    ],
  },
  {
    name: 'Donkey Calf Raises',
    muscleGroup: 'Calves',
    equipment: 'Machine',
    type: 'Isolation',
    description: 'Hip-hinge position calf raise that creates maximum gastrocnemius stretch.',
    tips: [
      'Hip-hinge forward 90°, toes on a platform, heel drops as low as possible.',
      'The stretched position for the gastrocnemius is maximised in this position.',
      'Can use a specialised machine or have a partner sit on your hips.',
      'Arnold Schwarzenegger famously swore by this for calf development.',
    ],
  },
  {
    name: 'Leg Press Calf Raises',
    muscleGroup: 'Calves',
    equipment: 'Machine',
    type: 'Isolation',
    description: 'Calf raises using the leg press machine. Allows heavy loading and safety.',
    tips: [
      'Use only the balls of your feet on the lower edge of the footplate.',
      'Full ROM — let your heels drop as far as possible at the bottom.',
      'Press through the ball of your foot to rise up.',
      'Easy to use heavy loads safely compared to free weight calf raises.',
    ],
  },
  {
    name: 'Single-Leg Calf Raises',
    muscleGroup: 'Calves',
    equipment: 'Bodyweight',
    type: 'Isolation',
    description: 'Unilateral bodyweight calf raise. Great for progressive bodyweight calf training.',
    tips: [
      'Hold a dumbbell in the same-side hand for extra resistance.',
      'Use a step for full ROM with a deep stretch.',
      'Balance challenge forces more stabiliser recruitment.',
      'Work up to 3 sets of 20+ reps per leg.',
    ],
  },

  // ─── TRAPS ────────────────────────────────────────────────────────────────
  {
    name: 'Barbell Shrugs',
    muscleGroup: 'Traps',
    equipment: 'Barbell',
    type: 'Isolation',
    description: 'Directly targets the upper trapezius. Can be loaded very heavily.',
    tips: [
      'Lift straight UP, hold for 2 seconds, lower slowly.',
      'Do NOT roll your shoulders — circular motion is ineffective and can injure the shoulder.',
      'Use straps to prevent grip from limiting how heavy you go.',
      'Traps respond well to heavy weight — don\'t be afraid to load this up.',
    ],
  },
  {
    name: 'Dumbbell Shrugs',
    muscleGroup: 'Traps',
    equipment: 'Dumbbells',
    type: 'Isolation',
    description: 'Dumbbell version of the shrug with a more natural arm path.',
    tips: [
      'Dumbbells at your sides — lift shoulders straight up.',
      'Pause at the top. Slow descent.',
      'Same principles as barbell: no rolling, just pure elevation.',
    ],
  },
  {
    name: "Farmer's Walk",
    muscleGroup: 'Traps',
    equipment: 'Dumbbells',
    type: 'Compound',
    description: 'Carry heavy weights for distance or time. One of the most functional exercises.',
    tips: [
      'Shoulders back and down, chest up, neutral spine.',
      'Take controlled, deliberate steps.',
      'Targets traps, forearms, core, and almost everything else simultaneously.',
      'Use as much weight as you can while maintaining perfect posture.',
      'One of the most transferable exercises for real-world strength.',
    ],
  },
  {
    name: 'Cable Shrugs',
    muscleGroup: 'Traps',
    equipment: 'Cable',
    type: 'Isolation',
    description: 'Cable provides constant tension through the full ROM of the shrug.',
    tips: [
      'Cable maintains tension at the bottom where dumbbells and barbells don\'t.',
      'Can do from behind your body (low cable) for a unique angle.',
      'Same technique: straight up, hold, slow down.',
    ],
  },

  // ─── FOREARMS ─────────────────────────────────────────────────────────────
  {
    name: 'Wrist Curls',
    muscleGroup: 'Forearms',
    equipment: 'Barbell',
    type: 'Isolation',
    description: 'Targets the wrist flexors on the underside of the forearm.',
    tips: [
      'Forearm rested on your thigh or a bench, wrist hanging off the edge.',
      'Full ROM: let the weight pull your wrist down fully, curl all the way up.',
      'High reps (15–25) work well for forearm development.',
      'Can use barbell or dumbbells.',
    ],
  },
  {
    name: 'Reverse Wrist Curls',
    muscleGroup: 'Forearms',
    equipment: 'Barbell',
    type: 'Isolation',
    description: 'Targets wrist extensors on the top of the forearm. Often neglected and a common culprit for tennis elbow.',
    tips: [
      'Overhand grip, forearm rested on a bench with wrist off the edge.',
      'Curl the wrist upward against the resistance.',
      'Light weight — extensors are much weaker than flexors.',
      'Helps prevent and rehabilitate lateral elbow pain (tennis elbow).',
    ],
  },
  {
    name: 'Plate Pinch',
    muscleGroup: 'Forearms',
    equipment: 'Barbell',
    type: 'Isometric',
    description: 'Pinch grip exercise using weight plates. Builds crushing and pinch grip strength.',
    tips: [
      'Hold two plates back-to-back with your fingers and thumb (pinch grip).',
      'Hold for time (20–60 seconds) or carry for distance.',
      'Start light — pinch grip is usually much weaker than crush grip.',
      'Massive carry-over to deadlifts, rows, and any pulling movement.',
    ],
  },

  // ─── FULL BODY / ATHLETIC ────────────────────────────────────────────────
  {
    name: 'Power Clean',
    muscleGroup: 'Full Body',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Olympic weightlifting movement. Develops explosive power through the entire posterior chain.',
    tips: [
      'Bar starts over your midfoot. Setup like a deadlift.',
      'First pull (floor to knee): like a deadlift — stay over the bar.',
      'Second pull (knee to hip): explosive hip extension as the bar passes your hip.',
      'High elbows as the bar rises. Drop under and catch in a quarter-front-squat.',
      'Very technical — learn progressions (hang clean, block clean) before floor clean.',
    ],
  },
  {
    name: 'Hang Clean',
    muscleGroup: 'Full Body',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Power clean starting from a hang position above the knee. Great entry point to Olympic lifting.',
    tips: [
      'Start standing with the bar in your hands at hip height.',
      'Hinge to lower the bar to just above the knee, then explosively drive your hips.',
      'High elbows as the bar rises — catch in a front rack position.',
      'Great for learning the explosive second pull without floor setup.',
    ],
  },
  {
    name: 'Power Snatch',
    muscleGroup: 'Full Body',
    equipment: 'Barbell',
    type: 'Compound',
    description: 'Olympic lift where the bar goes from the floor to overhead in one explosive movement.',
    tips: [
      'Wide overhand grip (snatch grip). Same setup as power clean.',
      'More explosive hip extension than the clean — bar needs to travel higher.',
      'Catch the bar overhead with arms locked, in a partial squat.',
      'Extremely technical — focus on hang snatch before floor snatch.',
    ],
  },
  {
    name: 'Kettlebell Swing',
    muscleGroup: 'Full Body',
    equipment: 'Equipment',
    type: 'Compound',
    description: 'Hip hinge ballistic movement. Builds explosive power and conditioning simultaneously.',
    tips: [
      'This is a HIP HINGE — not a squat. Sit back, not down.',
      'The kettlebell goes between your legs (not below your knees).',
      'Explosive hip extension sends the bell forward — your arms are just a connection.',
      'Two-hand Russian swing (to chest height) is the standard version.',
      'American swing (overhead) is advanced and requires shoulder mobility.',
    ],
  },
  {
    name: 'Box Jumps',
    muscleGroup: 'Full Body',
    equipment: 'Equipment',
    type: 'Compound',
    description: 'Plyometric power exercise. Develops explosive lower body power and fast-twitch fibers.',
    tips: [
      'Land softly with bent knees to absorb the impact.',
      'Full hip extension at takeoff — don\'t just use your knees.',
      'Always STEP DOWN from the box — jumping down increases injury risk significantly.',
      'Rest fully between sets — this is a power exercise, not conditioning.',
      'Prioritise quality of explosion, not just box height.',
    ],
  },
  {
    name: 'Burpees',
    muscleGroup: 'Full Body',
    equipment: 'Bodyweight',
    type: 'Compound',
    description: 'High-intensity full body conditioning exercise. Great for cardiovascular fitness.',
    tips: [
      '6-count movement: squat down, kick feet back, chest to floor, push up, feet forward, jump.',
      'Keep your core tight when kicking feet back.',
      'Can be scaled: remove the push up, remove the jump, or do step-back burpees.',
      'Pace yourself — burpees are as hard as you make them.',
    ],
  },
  {
    name: 'Battle Ropes',
    muscleGroup: 'Full Body',
    equipment: 'Equipment',
    type: 'Compound',
    description: 'Conditioning tool that builds upper body endurance and cardiovascular fitness.',
    tips: [
      'Stance slightly wider than shoulder-width, slight knee bend.',
      'Alternating waves, simultaneous waves, circles — all valid patterns.',
      'Keep your core engaged throughout.',
      'Work in intervals: 20–40 seconds on, full rest off.',
    ],
  },
  {
    name: 'Jump Rope',
    muscleGroup: 'Full Body',
    equipment: 'Equipment',
    type: 'Compound',
    description: 'Classic conditioning tool for cardiovascular fitness and foot speed.',
    tips: [
      'Stay on the balls of your feet — don\'t flat-foot the landings.',
      'Small, controlled jumps — just enough clearance for the rope.',
      'Wrists do the rotation — not your arms.',
      'Build up to double-unders (rope passes twice per jump) for advanced conditioning.',
    ],
  },
];
