// All exercises database
export const ALL_EXERCISES = [
  // CHEST
  { name: 'Barbell Bench Press', muscleGroup: 'Chest', equipment: 'Barbell', type: 'compound' },
  { name: 'Dumbbell Bench Press', muscleGroup: 'Chest', equipment: 'Dumbbells', type: 'compound' },
  { name: 'Incline Barbell Press', muscleGroup: 'Upper Chest', equipment: 'Barbell', type: 'compound' },
  { name: 'Incline Dumbbell Press', muscleGroup: 'Upper Chest', equipment: 'Dumbbells', type: 'compound' },
  { name: 'Decline Bench Press', muscleGroup: 'Lower Chest', equipment: 'Barbell', type: 'compound' },
  { name: 'Machine Chest Press', muscleGroup: 'Chest', equipment: 'Machine', type: 'compound' },
  { name: 'Cable Fly', muscleGroup: 'Chest', equipment: 'Cable', type: 'isolation' },
  { name: 'Incline Cable Fly', muscleGroup: 'Upper Chest', equipment: 'Cable', type: 'isolation' },
  { name: 'Pec Deck', muscleGroup: 'Chest', equipment: 'Machine', type: 'isolation' },
  { name: 'Dumbbell Fly', muscleGroup: 'Chest', equipment: 'Dumbbells', type: 'isolation' },
  { name: 'Push Ups', muscleGroup: 'Chest', equipment: 'Bodyweight', type: 'compound' },
  { name: 'Dips', muscleGroup: 'Chest', equipment: 'Bodyweight', type: 'compound' },
  { name: 'Landmine Press', muscleGroup: 'Chest', equipment: 'Barbell', type: 'compound' },
  { name: 'Floor Press', muscleGroup: 'Chest', equipment: 'Barbell', type: 'compound' },
  { name: 'Close Grip Bench Press', muscleGroup: 'Chest', equipment: 'Barbell', type: 'compound' },
  
  // BACK - with muscle region targeting
  { name: 'Barbell Row', muscleGroup: 'Back', equipment: 'Barbell', type: 'compound', targetedHeads: ['Mid Back', 'Upper Back'] },
  { name: 'Pendlay Row', muscleGroup: 'Back', equipment: 'Barbell', type: 'compound', targetedHeads: ['Mid Back', 'Upper Back'] },
  { name: 'Dumbbell Row', muscleGroup: 'Back', equipment: 'Dumbbells', type: 'compound', targetedHeads: ['Mid Back'] },
  { name: 'Chest Supported Row', muscleGroup: 'Back', equipment: 'Dumbbells', type: 'compound', targetedHeads: ['Upper Back', 'Mid Back'] },
  { name: 'T-Bar Row', muscleGroup: 'Back', equipment: 'Barbell', type: 'compound', targetedHeads: ['Mid Back'] },
  { name: 'Seated Cable Row', muscleGroup: 'Back', equipment: 'Cable', type: 'compound', targetedHeads: ['Mid Back'] },
  { name: 'Lat Pulldown', muscleGroup: 'Lats', equipment: 'Cable', type: 'compound' },
  { name: 'Close Grip Pulldown', muscleGroup: 'Lats', equipment: 'Cable', type: 'compound' },
  { name: 'Wide Grip Pulldown', muscleGroup: 'Lats', equipment: 'Cable', type: 'compound' },
  { name: 'Pull Ups', muscleGroup: 'Lats', equipment: 'Bodyweight', type: 'compound' },
  { name: 'Chin Ups', muscleGroup: 'Lats', equipment: 'Bodyweight', type: 'compound' },
  { name: 'Neutral Grip Pull Ups', muscleGroup: 'Lats', equipment: 'Bodyweight', type: 'compound' },
  { name: 'Machine Row', muscleGroup: 'Back', equipment: 'Machine', type: 'compound', targetedHeads: ['Mid Back'] },
  { name: 'Meadows Row', muscleGroup: 'Back', equipment: 'Barbell', type: 'compound', targetedHeads: ['Mid Back'] },
  { name: 'Seal Row', muscleGroup: 'Back', equipment: 'Barbell', type: 'compound', targetedHeads: ['Mid Back', 'Upper Back'] },
  { name: 'Straight Arm Pulldown', muscleGroup: 'Lats', equipment: 'Cable', type: 'isolation' },
  { name: 'Rack Pulls', muscleGroup: 'Back', equipment: 'Barbell', type: 'compound', targetedHeads: ['Lower Back'] },
  { name: 'Deadlift', muscleGroup: 'Back', equipment: 'Barbell', type: 'compound', targetedHeads: ['Lower Back', 'Mid Back'] },
  { name: 'Snatch Grip Deadlift', muscleGroup: 'Back', equipment: 'Barbell', type: 'compound', targetedHeads: ['Upper Back', 'Mid Back'] },
  { name: 'Wide Grip Cable Row', muscleGroup: 'Back', equipment: 'Cable', type: 'compound', targetedHeads: ['Upper Back'] },
  { name: 'High Cable Row', muscleGroup: 'Back', equipment: 'Cable', type: 'compound', targetedHeads: ['Upper Back'] },
  { name: 'Back Extension', muscleGroup: 'Back', equipment: 'Equipment', type: 'isolation', targetedHeads: ['Lower Back'] },
  { name: 'Hyperextension', muscleGroup: 'Back', equipment: 'Equipment', type: 'isolation', targetedHeads: ['Lower Back'] },
  
  // SHOULDERS
  { name: 'Overhead Press', muscleGroup: 'Shoulders', equipment: 'Barbell', type: 'compound' },
  { name: 'Seated Dumbbell Press', muscleGroup: 'Shoulders', equipment: 'Dumbbells', type: 'compound' },
  { name: 'Arnold Press', muscleGroup: 'Shoulders', equipment: 'Dumbbells', type: 'compound' },
  { name: 'Machine Shoulder Press', muscleGroup: 'Shoulders', equipment: 'Machine', type: 'compound' },
  { name: 'Push Press', muscleGroup: 'Shoulders', equipment: 'Barbell', type: 'compound' },
  { name: 'Lateral Raises', muscleGroup: 'Side Delts', equipment: 'Dumbbells', type: 'isolation' },
  { name: 'Cable Lateral Raises', muscleGroup: 'Side Delts', equipment: 'Cable', type: 'isolation' },
  { name: 'Machine Lateral Raises', muscleGroup: 'Side Delts', equipment: 'Machine', type: 'isolation' },
  { name: 'Front Raises', muscleGroup: 'Front Delts', equipment: 'Dumbbells', type: 'isolation' },
  { name: 'Cable Front Raises', muscleGroup: 'Front Delts', equipment: 'Cable', type: 'isolation' },
  { name: 'Face Pulls', muscleGroup: 'Rear Delts', equipment: 'Cable', type: 'isolation' },
  { name: 'Reverse Pec Deck', muscleGroup: 'Rear Delts', equipment: 'Machine', type: 'isolation' },
  { name: 'Rear Delt Fly', muscleGroup: 'Rear Delts', equipment: 'Dumbbells', type: 'isolation' },
  { name: 'Cable Rear Delt Fly', muscleGroup: 'Rear Delts', equipment: 'Cable', type: 'isolation' },
  { name: 'Upright Rows', muscleGroup: 'Shoulders', equipment: 'Barbell', type: 'compound' },
  { name: 'Lu Raises', muscleGroup: 'Side Delts', equipment: 'Dumbbells', type: 'isolation' },
  { name: 'Y Raises', muscleGroup: 'Shoulders', equipment: 'Dumbbells', type: 'isolation' },
  
  // TRICEPS - with muscle head targeting
  { name: 'Tricep Pushdowns', muscleGroup: 'Triceps', equipment: 'Cable', type: 'isolation', targetedHeads: ['Lateral Head Triceps'] },
  { name: 'Rope Pushdowns', muscleGroup: 'Triceps', equipment: 'Cable', type: 'isolation', targetedHeads: ['Lateral Head Triceps', 'Medial Head Triceps'] },
  { name: 'Overhead Tricep Extension', muscleGroup: 'Triceps', equipment: 'Cable', type: 'isolation', targetedHeads: ['Long Head Triceps'] },
  { name: 'Skull Crushers', muscleGroup: 'Triceps', equipment: 'Barbell', type: 'isolation', targetedHeads: ['Long Head Triceps'] },
  { name: 'Dumbbell Skull Crushers', muscleGroup: 'Triceps', equipment: 'Dumbbells', type: 'isolation', targetedHeads: ['Long Head Triceps'] },
  { name: 'Tricep Dips', muscleGroup: 'Triceps', equipment: 'Bodyweight', type: 'compound', targetedHeads: ['Lateral Head Triceps', 'Medial Head Triceps'] },
  { name: 'Diamond Push Ups', muscleGroup: 'Triceps', equipment: 'Bodyweight', type: 'compound', targetedHeads: ['Medial Head Triceps'] },
  { name: 'JM Press', muscleGroup: 'Triceps', equipment: 'Barbell', type: 'compound', targetedHeads: ['Long Head Triceps', 'Lateral Head Triceps'] },
  { name: 'Tricep Kickbacks', muscleGroup: 'Triceps', equipment: 'Dumbbells', type: 'isolation', targetedHeads: ['Lateral Head Triceps'] },
  { name: 'Single Arm Pushdown', muscleGroup: 'Triceps', equipment: 'Cable', type: 'isolation', targetedHeads: ['Lateral Head Triceps'] },
  { name: 'V-Bar Pushdown', muscleGroup: 'Triceps', equipment: 'Cable', type: 'isolation', targetedHeads: ['Lateral Head Triceps'] },
  { name: 'Reverse Grip Pushdown', muscleGroup: 'Triceps', equipment: 'Cable', type: 'isolation', targetedHeads: ['Medial Head Triceps'] },
  { name: 'French Press', muscleGroup: 'Triceps', equipment: 'Barbell', type: 'isolation', targetedHeads: ['Long Head Triceps'] },
  { name: 'Incline Skull Crushers', muscleGroup: 'Triceps', equipment: 'Barbell', type: 'isolation', targetedHeads: ['Long Head Triceps'] },
  { name: 'Overhead Dumbbell Extension', muscleGroup: 'Triceps', equipment: 'Dumbbells', type: 'isolation', targetedHeads: ['Long Head Triceps'] },
  
  // BICEPS - with muscle head targeting
  { name: 'Barbell Curl', muscleGroup: 'Biceps', equipment: 'Barbell', type: 'isolation', targetedHeads: ['Long Head Biceps', 'Short Head Biceps'] },
  { name: 'EZ Bar Curl', muscleGroup: 'Biceps', equipment: 'Barbell', type: 'isolation', targetedHeads: ['Long Head Biceps', 'Short Head Biceps'] },
  { name: 'Dumbbell Curl', muscleGroup: 'Biceps', equipment: 'Dumbbells', type: 'isolation', targetedHeads: ['Long Head Biceps', 'Short Head Biceps'] },
  { name: 'Hammer Curls', muscleGroup: 'Biceps', equipment: 'Dumbbells', type: 'isolation', targetedHeads: ['Long Head Biceps'] },
  { name: 'Incline Dumbbell Curl', muscleGroup: 'Biceps', equipment: 'Dumbbells', type: 'isolation', targetedHeads: ['Long Head Biceps'] },
  { name: 'Preacher Curl', muscleGroup: 'Biceps', equipment: 'Barbell', type: 'isolation', targetedHeads: ['Short Head Biceps'] },
  { name: 'Cable Curl', muscleGroup: 'Biceps', equipment: 'Cable', type: 'isolation', targetedHeads: ['Long Head Biceps', 'Short Head Biceps'] },
  { name: 'Concentration Curl', muscleGroup: 'Biceps', equipment: 'Dumbbells', type: 'isolation', targetedHeads: ['Short Head Biceps'] },
  { name: 'Spider Curls', muscleGroup: 'Biceps', equipment: 'Dumbbells', type: 'isolation', targetedHeads: ['Short Head Biceps'] },
  { name: 'Drag Curls', muscleGroup: 'Biceps', equipment: 'Barbell', type: 'isolation', targetedHeads: ['Long Head Biceps'] },
  { name: 'Reverse Curls', muscleGroup: 'Forearms', equipment: 'Barbell', type: 'isolation' },
  { name: 'Wrist Curls', muscleGroup: 'Forearms', equipment: 'Barbell', type: 'isolation' },
  { name: 'Bayesian Cable Curl', muscleGroup: 'Biceps', equipment: 'Cable', type: 'isolation', targetedHeads: ['Long Head Biceps'] },
  { name: 'High Cable Curl', muscleGroup: 'Biceps', equipment: 'Cable', type: 'isolation', targetedHeads: ['Short Head Biceps'] },
  { name: 'Machine Preacher Curl', muscleGroup: 'Biceps', equipment: 'Machine', type: 'isolation', targetedHeads: ['Short Head Biceps'] },
  { name: 'Wide Grip Barbell Curl', muscleGroup: 'Biceps', equipment: 'Barbell', type: 'isolation', targetedHeads: ['Short Head Biceps'] },
  { name: 'Narrow Grip EZ Curl', muscleGroup: 'Biceps', equipment: 'Barbell', type: 'isolation', targetedHeads: ['Long Head Biceps'] },
  
  // QUADS - with muscle head targeting
  { name: 'Barbell Back Squat', muscleGroup: 'Quads', equipment: 'Barbell', type: 'compound', targetedHeads: ['Vastus Lateralis', 'Vastus Medialis', 'Rectus Femoris'] },
  { name: 'Front Squat', muscleGroup: 'Quads', equipment: 'Barbell', type: 'compound', targetedHeads: ['Rectus Femoris', 'Vastus Medialis'] },
  { name: 'Goblet Squat', muscleGroup: 'Quads', equipment: 'Dumbbells', type: 'compound', targetedHeads: ['Vastus Medialis', 'Rectus Femoris'] },
  { name: 'Hack Squat', muscleGroup: 'Quads', equipment: 'Machine', type: 'compound', targetedHeads: ['Rectus Femoris', 'Vastus Lateralis'] },
  { name: 'Leg Press', muscleGroup: 'Quads', equipment: 'Machine', type: 'compound', targetedHeads: ['Vastus Lateralis', 'Vastus Medialis'] },
  { name: 'Bulgarian Split Squat', muscleGroup: 'Quads', equipment: 'Dumbbells', type: 'compound', targetedHeads: ['Vastus Medialis', 'Rectus Femoris'] },
  { name: 'Walking Lunges', muscleGroup: 'Quads', equipment: 'Dumbbells', type: 'compound', targetedHeads: ['Vastus Lateralis', 'Rectus Femoris'] },
  { name: 'Reverse Lunges', muscleGroup: 'Quads', equipment: 'Dumbbells', type: 'compound', targetedHeads: ['Vastus Medialis', 'Rectus Femoris'] },
  { name: 'Step Ups', muscleGroup: 'Quads', equipment: 'Dumbbells', type: 'compound', targetedHeads: ['Vastus Medialis', 'Rectus Femoris'] },
  { name: 'Leg Extension', muscleGroup: 'Quads', equipment: 'Machine', type: 'isolation', targetedHeads: ['Rectus Femoris'] },
  { name: 'Sissy Squat', muscleGroup: 'Quads', equipment: 'Bodyweight', type: 'isolation', targetedHeads: ['Vastus Medialis', 'Rectus Femoris'] },
  { name: 'Pendulum Squat', muscleGroup: 'Quads', equipment: 'Machine', type: 'compound', targetedHeads: ['Rectus Femoris'] },
  { name: 'Belt Squat', muscleGroup: 'Quads', equipment: 'Machine', type: 'compound', targetedHeads: ['Vastus Lateralis', 'Vastus Medialis'] },
  { name: 'Smith Machine Squat', muscleGroup: 'Quads', equipment: 'Machine', type: 'compound', targetedHeads: ['Vastus Lateralis', 'Vastus Medialis'] },
  { name: 'Heels Elevated Squat', muscleGroup: 'Quads', equipment: 'Barbell', type: 'compound', targetedHeads: ['Vastus Medialis'] },
  { name: 'Narrow Stance Leg Press', muscleGroup: 'Quads', equipment: 'Machine', type: 'compound', targetedHeads: ['Vastus Medialis'] },
  { name: 'Wide Stance Leg Press', muscleGroup: 'Quads', equipment: 'Machine', type: 'compound', targetedHeads: ['Vastus Lateralis'] },

  // HAMSTRINGS & GLUTES - with muscle head targeting
  { name: 'Romanian Deadlift', muscleGroup: 'Hamstrings', equipment: 'Barbell', type: 'compound', targetedHeads: ['Bicep Femoris'] },
  { name: 'Stiff Leg Deadlift', muscleGroup: 'Hamstrings', equipment: 'Barbell', type: 'compound', targetedHeads: ['Bicep Femoris'] },
  { name: 'Dumbbell RDL', muscleGroup: 'Hamstrings', equipment: 'Dumbbells', type: 'compound', targetedHeads: ['Bicep Femoris'] },
  { name: 'Single Leg RDL', muscleGroup: 'Hamstrings', equipment: 'Dumbbells', type: 'compound', targetedHeads: ['Bicep Femoris'] },
  { name: 'Good Mornings', muscleGroup: 'Hamstrings', equipment: 'Barbell', type: 'compound', targetedHeads: ['Bicep Femoris'] },
  { name: 'Lying Leg Curl', muscleGroup: 'Hamstrings', equipment: 'Machine', type: 'isolation', targetedHeads: ['Bicep Femoris'] },
  { name: 'Seated Leg Curl', muscleGroup: 'Hamstrings', equipment: 'Machine', type: 'isolation', targetedHeads: ['Semitendinosus'] },
  { name: 'Nordic Curls', muscleGroup: 'Hamstrings', equipment: 'Bodyweight', type: 'isolation', targetedHeads: ['Semitendinosus', 'Bicep Femoris'] },
  { name: 'Glute Ham Raise', muscleGroup: 'Hamstrings', equipment: 'Equipment', type: 'isolation', targetedHeads: ['Semitendinosus', 'Bicep Femoris'] },
  { name: 'Hip Thrust', muscleGroup: 'Glutes', equipment: 'Barbell', type: 'compound', targetedHeads: ['Gluteus Maximus'] },
  { name: 'Glute Bridge', muscleGroup: 'Glutes', equipment: 'Barbell', type: 'compound', targetedHeads: ['Gluteus Maximus'] },
  { name: 'Cable Pull Through', muscleGroup: 'Glutes', equipment: 'Cable', type: 'compound', targetedHeads: ['Gluteus Maximus'] },
  { name: 'Glute Kickback', muscleGroup: 'Glutes', equipment: 'Cable', type: 'isolation', targetedHeads: ['Gluteus Maximus', 'Gluteus Medius'] },
  { name: 'Hip Abduction', muscleGroup: 'Glutes', equipment: 'Machine', type: 'isolation', targetedHeads: ['Gluteus Medius'] },
  { name: 'Sumo Deadlift', muscleGroup: 'Glutes', equipment: 'Barbell', type: 'compound', targetedHeads: ['Gluteus Maximus'] },
  { name: 'Single Leg Hip Thrust', muscleGroup: 'Glutes', equipment: 'Bodyweight', type: 'isolation', targetedHeads: ['Gluteus Maximus'] },
  { name: 'Cable Hip Abduction', muscleGroup: 'Glutes', equipment: 'Cable', type: 'isolation', targetedHeads: ['Gluteus Medius'] },
  { name: 'Curtsy Lunge', muscleGroup: 'Glutes', equipment: 'Dumbbells', type: 'compound', targetedHeads: ['Gluteus Medius', 'Gluteus Maximus'] },
  
  // CALVES
  { name: 'Standing Calf Raises', muscleGroup: 'Calves', equipment: 'Machine', type: 'isolation' },
  { name: 'Seated Calf Raises', muscleGroup: 'Calves', equipment: 'Machine', type: 'isolation' },
  { name: 'Leg Press Calf Raises', muscleGroup: 'Calves', equipment: 'Machine', type: 'isolation' },
  { name: 'Donkey Calf Raises', muscleGroup: 'Calves', equipment: 'Machine', type: 'isolation' },
  { name: 'Single Leg Calf Raise', muscleGroup: 'Calves', equipment: 'Bodyweight', type: 'isolation' },
  { name: 'Smith Machine Calf Raise', muscleGroup: 'Calves', equipment: 'Machine', type: 'isolation' },
  
  // CORE
  { name: 'Hanging Leg Raises', muscleGroup: 'Abs', equipment: 'Bodyweight', type: 'isolation' },
  { name: 'Hanging Knee Raises', muscleGroup: 'Abs', equipment: 'Bodyweight', type: 'isolation' },
  { name: 'Cable Crunches', muscleGroup: 'Abs', equipment: 'Cable', type: 'isolation' },
  { name: 'Ab Wheel Rollout', muscleGroup: 'Abs', equipment: 'Equipment', type: 'isolation' },
  { name: 'Plank', muscleGroup: 'Core', equipment: 'Bodyweight', type: 'isolation' },
  { name: 'Dead Bug', muscleGroup: 'Core', equipment: 'Bodyweight', type: 'isolation' },
  { name: 'Pallof Press', muscleGroup: 'Core', equipment: 'Cable', type: 'isolation' },
  { name: 'Wood Chops', muscleGroup: 'Core', equipment: 'Cable', type: 'isolation' },
  { name: 'Russian Twists', muscleGroup: 'Obliques', equipment: 'Bodyweight', type: 'isolation' },
  { name: 'Side Plank', muscleGroup: 'Obliques', equipment: 'Bodyweight', type: 'isolation' },
  { name: 'Decline Sit Ups', muscleGroup: 'Abs', equipment: 'Bodyweight', type: 'isolation' },
  { name: 'Bicycle Crunches', muscleGroup: 'Abs', equipment: 'Bodyweight', type: 'isolation' },
  { name: 'Mountain Climbers', muscleGroup: 'Core', equipment: 'Bodyweight', type: 'compound' },
  { name: 'V-Ups', muscleGroup: 'Abs', equipment: 'Bodyweight', type: 'isolation' },
  { name: 'Toe Touches', muscleGroup: 'Abs', equipment: 'Bodyweight', type: 'isolation' },
  { name: 'Flutter Kicks', muscleGroup: 'Abs', equipment: 'Bodyweight', type: 'isolation' },
  { name: 'Dragon Flags', muscleGroup: 'Abs', equipment: 'Bodyweight', type: 'isolation' },
  { name: 'L-Sit', muscleGroup: 'Core', equipment: 'Bodyweight', type: 'isolation' },
  { name: 'Hollow Body Hold', muscleGroup: 'Core', equipment: 'Bodyweight', type: 'isolation' },
  { name: 'Bird Dog', muscleGroup: 'Core', equipment: 'Bodyweight', type: 'isolation' },

  // TRAPS
  { name: 'Barbell Shrugs', muscleGroup: 'Traps', equipment: 'Barbell', type: 'isolation' },
  { name: 'Dumbbell Shrugs', muscleGroup: 'Traps', equipment: 'Dumbbells', type: 'isolation' },
  { name: 'Cable Shrugs', muscleGroup: 'Traps', equipment: 'Cable', type: 'isolation' },
  { name: 'Farmers Walk', muscleGroup: 'Traps', equipment: 'Dumbbells', type: 'compound' },
  { name: 'Rack Pulls (High)', muscleGroup: 'Traps', equipment: 'Barbell', type: 'compound' },

  // CARDIO & CONDITIONING
  { name: 'Treadmill Run', muscleGroup: 'Cardio', equipment: 'Machine', type: 'cardio' },
  { name: 'Treadmill Walk (Incline)', muscleGroup: 'Cardio', equipment: 'Machine', type: 'cardio' },
  { name: 'Stationary Bike', muscleGroup: 'Cardio', equipment: 'Machine', type: 'cardio' },
  { name: 'Rowing Machine', muscleGroup: 'Cardio', equipment: 'Machine', type: 'cardio' },
  { name: 'Stair Climber', muscleGroup: 'Cardio', equipment: 'Machine', type: 'cardio' },
  { name: 'Elliptical', muscleGroup: 'Cardio', equipment: 'Machine', type: 'cardio' },
  { name: 'Battle Ropes', muscleGroup: 'Cardio', equipment: 'Equipment', type: 'cardio' },
  { name: 'Box Jumps', muscleGroup: 'Cardio', equipment: 'Equipment', type: 'compound' },
  { name: 'Burpees', muscleGroup: 'Cardio', equipment: 'Bodyweight', type: 'compound' },
  { name: 'Jump Rope', muscleGroup: 'Cardio', equipment: 'Equipment', type: 'cardio' },
  { name: 'Sled Push', muscleGroup: 'Cardio', equipment: 'Equipment', type: 'compound' },
  { name: 'Sled Pull', muscleGroup: 'Cardio', equipment: 'Equipment', type: 'compound' },
  { name: 'Kettlebell Swings', muscleGroup: 'Cardio', equipment: 'Kettlebell', type: 'compound' },
  { name: 'Assault Bike', muscleGroup: 'Cardio', equipment: 'Machine', type: 'cardio' },
  { name: 'Ski Erg', muscleGroup: 'Cardio', equipment: 'Machine', type: 'cardio' },

  // OLYMPIC LIFTS & VARIATIONS
  { name: 'Power Clean', muscleGroup: 'Full Body', equipment: 'Barbell', type: 'compound' },
  { name: 'Hang Clean', muscleGroup: 'Full Body', equipment: 'Barbell', type: 'compound' },
  { name: 'Clean and Jerk', muscleGroup: 'Full Body', equipment: 'Barbell', type: 'compound' },
  { name: 'Snatch', muscleGroup: 'Full Body', equipment: 'Barbell', type: 'compound' },
  { name: 'Hang Snatch', muscleGroup: 'Full Body', equipment: 'Barbell', type: 'compound' },
  { name: 'Clean High Pull', muscleGroup: 'Full Body', equipment: 'Barbell', type: 'compound' },
  { name: 'Dumbbell Snatch', muscleGroup: 'Full Body', equipment: 'Dumbbells', type: 'compound' },
  { name: 'Kettlebell Clean', muscleGroup: 'Full Body', equipment: 'Kettlebell', type: 'compound' },
  { name: 'Thruster', muscleGroup: 'Full Body', equipment: 'Barbell', type: 'compound' },
  { name: 'Dumbbell Thruster', muscleGroup: 'Full Body', equipment: 'Dumbbells', type: 'compound' },

  // FUNCTIONAL & STABILITY
  { name: 'Turkish Get Up', muscleGroup: 'Full Body', equipment: 'Kettlebell', type: 'compound' },
  { name: 'Landmine Rotation', muscleGroup: 'Core', equipment: 'Barbell', type: 'compound' },
  { name: 'Medicine Ball Slam', muscleGroup: 'Full Body', equipment: 'Equipment', type: 'compound' },
  { name: 'Wall Ball', muscleGroup: 'Full Body', equipment: 'Equipment', type: 'compound' },
  { name: 'Cable Woodchop (Low to High)', muscleGroup: 'Core', equipment: 'Cable', type: 'compound' },
  { name: 'Bosu Ball Squat', muscleGroup: 'Quads', equipment: 'Equipment', type: 'compound' },
  { name: 'Single Leg Deadlift', muscleGroup: 'Hamstrings', equipment: 'Dumbbells', type: 'compound' },
  { name: 'Pistol Squat', muscleGroup: 'Quads', equipment: 'Bodyweight', type: 'compound' },
  { name: 'Box Step Up', muscleGroup: 'Quads', equipment: 'Equipment', type: 'compound' },
  { name: 'Reverse Lunge', muscleGroup: 'Quads', equipment: 'Dumbbells', type: 'compound' },
  { name: 'Walking Lunge', muscleGroup: 'Quads', equipment: 'Dumbbells', type: 'compound' },
  { name: 'Curtsy Lunge', muscleGroup: 'Glutes', equipment: 'Dumbbells', type: 'compound' },
  { name: 'Step Through Lunge', muscleGroup: 'Quads', equipment: 'Dumbbells', type: 'compound' },

  // ADVANCED BODYWEIGHT
  { name: 'Muscle Up', muscleGroup: 'Full Body', equipment: 'Bodyweight', type: 'compound' },
  { name: 'Ring Dips', muscleGroup: 'Chest', equipment: 'Bodyweight', type: 'compound' },
  { name: 'Ring Rows', muscleGroup: 'Back', equipment: 'Bodyweight', type: 'compound' },
  { name: 'Handstand Push Up', muscleGroup: 'Shoulders', equipment: 'Bodyweight', type: 'compound' },
  { name: 'Archer Push Up', muscleGroup: 'Chest', equipment: 'Bodyweight', type: 'compound' },
  { name: 'Pike Push Up', muscleGroup: 'Shoulders', equipment: 'Bodyweight', type: 'compound' },
  { name: 'Decline Push Up', muscleGroup: 'Chest', equipment: 'Bodyweight', type: 'compound' },
  { name: 'Inverted Row', muscleGroup: 'Back', equipment: 'Bodyweight', type: 'compound' },
  { name: 'Typewriter Pull Up', muscleGroup: 'Back', equipment: 'Bodyweight', type: 'compound' },
  { name: 'Archer Pull Up', muscleGroup: 'Back', equipment: 'Bodyweight', type: 'compound' },

  // ADDITIONAL SHOULDER EXERCISES
  { name: 'Seated Arnold Press', muscleGroup: 'Shoulders', equipment: 'Dumbbells', type: 'compound' },
  { name: 'Bradford Press', muscleGroup: 'Shoulders', equipment: 'Barbell', type: 'compound' },
  { name: 'Z Press', muscleGroup: 'Shoulders', equipment: 'Barbell', type: 'compound' },
  { name: 'Behind the Neck Press', muscleGroup: 'Shoulders', equipment: 'Barbell', type: 'compound' },
  { name: 'Bottoms Up Press', muscleGroup: 'Shoulders', equipment: 'Kettlebell', type: 'compound' },
  { name: 'Javelin Press', muscleGroup: 'Shoulders', equipment: 'Barbell', type: 'compound' },
  { name: 'Crucifix Hold', muscleGroup: 'Side Delts', equipment: 'Dumbbells', type: 'isolation' },

  // ADDITIONAL ARM EXERCISES
  { name: '21s (Bicep)', muscleGroup: 'Biceps', equipment: 'Barbell', type: 'isolation' },
  { name: 'Zottman Curls', muscleGroup: 'Biceps', equipment: 'Dumbbells', type: 'isolation' },
  { name: 'Waiter Curls', muscleGroup: 'Biceps', equipment: 'Dumbbells', type: 'isolation' },
  { name: 'Cable Hammer Curl', muscleGroup: 'Biceps', equipment: 'Cable', type: 'isolation' },
  { name: 'Overhead Cable Curl', muscleGroup: 'Biceps', equipment: 'Cable', type: 'isolation' },
  { name: 'California Press', muscleGroup: 'Triceps', equipment: 'Barbell', type: 'compound' },
  { name: 'Tate Press', muscleGroup: 'Triceps', equipment: 'Dumbbells', type: 'isolation' },
  { name: 'Bench Dips', muscleGroup: 'Triceps', equipment: 'Bodyweight', type: 'compound' },
  { name: 'Overhead Dumbbell Extension', muscleGroup: 'Triceps', equipment: 'Dumbbells', type: 'isolation' },
  { name: 'Cross Body Tricep Extension', muscleGroup: 'Triceps', equipment: 'Cable', type: 'isolation' },
];

// ============================================
// DYNAMIC WORKOUT GENERATION SYSTEM
// ============================================

