export const FOOD_CATEGORIES = [
  'All',
  'Protein',
  'Dairy',
  'Grains & Carbs',
  'Fruits & Vegetables',
  'Snacks & Convenience',
  'Meals & Combos',
  'Fast Food & Takeaway',
  'Desserts & Treats',
  'Oils & Condiments',
  'Beverages',
];

export const QUICK_FOODS = [
  // ─── PROTEIN ──────────────────────────────────────────────────────────────
  // Chicken
  { name: 'Chicken Breast', calories: 165, protein: 31, carbs: 0, fats: 3.6, serving: '100g', category: 'Protein' },
  { name: 'Chicken Thigh', calories: 209, protein: 26, carbs: 0, fats: 11, serving: '100g', category: 'Protein' },
  { name: 'Chicken Drumstick', calories: 172, protein: 28, carbs: 0, fats: 6, serving: '100g', category: 'Protein' },
  { name: 'Chicken Wing', calories: 203, protein: 30, carbs: 0, fats: 8, serving: '100g', category: 'Protein' },
  { name: 'Chicken Tender', calories: 150, protein: 28, carbs: 2, fats: 3, serving: '100g', category: 'Protein' },
  { name: 'Rotisserie Chicken', calories: 190, protein: 27, carbs: 0, fats: 9, serving: '100g', category: 'Protein' },
  { name: 'Canned Chicken', calories: 130, protein: 25, carbs: 0, fats: 3, serving: '100g', category: 'Protein' },
  // Turkey
  { name: 'Turkey Breast', calories: 135, protein: 30, carbs: 0, fats: 1, serving: '100g', category: 'Protein' },
  { name: 'Turkey Mince', calories: 170, protein: 21, carbs: 0, fats: 9, serving: '100g', category: 'Protein' },
  { name: 'Deli Turkey Slices', calories: 60, protein: 12, carbs: 1, fats: 0.5, serving: '56g (4 slices)', category: 'Protein' },
  // Beef
  { name: 'Beef Steak (Sirloin)', calories: 271, protein: 26, carbs: 0, fats: 18, serving: '100g', category: 'Protein' },
  { name: 'Beef Eye Fillet', calories: 218, protein: 28, carbs: 0, fats: 11, serving: '100g', category: 'Protein' },
  { name: 'Beef Rump Steak', calories: 198, protein: 28, carbs: 0, fats: 9, serving: '100g', category: 'Protein' },
  { name: 'Lean Beef Mince (5%)', calories: 176, protein: 20, carbs: 0, fats: 10, serving: '100g', category: 'Protein' },
  { name: 'Beef Mince (Regular)', calories: 254, protein: 17, carbs: 0, fats: 20, serving: '100g', category: 'Protein' },
  { name: 'Beef Brisket', calories: 280, protein: 22, carbs: 0, fats: 21, serving: '100g', category: 'Protein' },
  { name: 'Corned Beef', calories: 250, protein: 18, carbs: 0, fats: 19, serving: '100g', category: 'Protein' },
  { name: 'Deli Roast Beef', calories: 70, protein: 12, carbs: 1, fats: 2, serving: '56g (4 slices)', category: 'Protein' },
  // Pork & Lamb
  { name: 'Pork Loin', calories: 143, protein: 26, carbs: 0, fats: 3.5, serving: '100g', category: 'Protein' },
  { name: 'Pork Chop', calories: 231, protein: 25, carbs: 0, fats: 14, serving: '100g', category: 'Protein' },
  { name: 'Pork Belly', calories: 518, protein: 9, carbs: 0, fats: 53, serving: '100g', category: 'Protein' },
  { name: 'Pork Mince', calories: 212, protein: 19, carbs: 0, fats: 15, serving: '100g', category: 'Protein' },
  { name: 'Bacon (2 Rashers)', calories: 86, protein: 6, carbs: 0.3, fats: 7, serving: '2 rashers', category: 'Protein' },
  { name: 'Bacon (4 Rashers)', calories: 172, protein: 12, carbs: 0.6, fats: 14, serving: '4 rashers', category: 'Protein' },
  { name: 'Ham Slices', calories: 60, protein: 10, carbs: 1.5, fats: 1.5, serving: '56g (4 slices)', category: 'Protein' },
  { name: 'Lamb Chop', calories: 258, protein: 25, carbs: 0, fats: 17, serving: '100g', category: 'Protein' },
  { name: 'Lamb Mince', calories: 282, protein: 17, carbs: 0, fats: 23, serving: '100g', category: 'Protein' },
  { name: 'Lamb Shank', calories: 201, protein: 28, carbs: 0, fats: 9, serving: '100g', category: 'Protein' },
  // Sausages
  { name: 'Beef Sausage', calories: 250, protein: 14, carbs: 2, fats: 21, serving: '1 sausage', category: 'Protein' },
  { name: 'Chicken Sausage', calories: 140, protein: 14, carbs: 4, fats: 7, serving: '1 sausage', category: 'Protein' },
  // Seafood
  { name: 'Salmon Fillet', calories: 208, protein: 20, carbs: 0, fats: 13, serving: '100g', category: 'Protein' },
  { name: 'Smoked Salmon', calories: 117, protein: 18, carbs: 0, fats: 4.3, serving: '56g', category: 'Protein' },
  { name: 'Canned Salmon', calories: 167, protein: 23, carbs: 0, fats: 8, serving: '100g', category: 'Protein' },
  { name: 'Canned Tuna (Plain)', calories: 116, protein: 26, carbs: 0, fats: 1, serving: '100g', category: 'Protein' },
  { name: 'Canned Tuna (Oil)', calories: 186, protein: 26, carbs: 0, fats: 8, serving: '100g', category: 'Protein' },
  { name: 'Canned Sardines', calories: 208, protein: 25, carbs: 0, fats: 11, serving: '100g', category: 'Protein' },
  { name: 'Prawns', calories: 85, protein: 20, carbs: 0, fats: 0.5, serving: '100g', category: 'Protein' },
  { name: 'White Fish (Barramundi)', calories: 90, protein: 20, carbs: 0, fats: 1, serving: '100g', category: 'Protein' },
  { name: 'Cod Fillet', calories: 82, protein: 18, carbs: 0, fats: 0.7, serving: '100g', category: 'Protein' },
  { name: 'Tuna Steak', calories: 132, protein: 28, carbs: 0, fats: 1.3, serving: '100g', category: 'Protein' },
  { name: 'Calamari (Grilled)', calories: 92, protein: 15, carbs: 3, fats: 1.4, serving: '100g', category: 'Protein' },
  { name: 'Mussels', calories: 86, protein: 12, carbs: 4, fats: 2.2, serving: '100g', category: 'Protein' },
  // Eggs
  { name: 'Egg (1)', calories: 72, protein: 6, carbs: 0.4, fats: 5, serving: '1 large', category: 'Protein' },
  { name: 'Eggs (2)', calories: 144, protein: 12, carbs: 0.8, fats: 10, serving: '2 large', category: 'Protein' },
  { name: 'Eggs (3)', calories: 216, protein: 18, carbs: 1.2, fats: 15, serving: '3 large', category: 'Protein' },
  { name: 'Eggs (4)', calories: 288, protein: 24, carbs: 1.6, fats: 20, serving: '4 large', category: 'Protein' },
  { name: 'Egg Whites (3)', calories: 51, protein: 11, carbs: 0.7, fats: 0.2, serving: '3 large', category: 'Protein' },
  { name: 'Egg Whites (4)', calories: 68, protein: 15, carbs: 1, fats: 0.3, serving: '4 large', category: 'Protein' },
  { name: 'Hard Boiled Egg', calories: 78, protein: 6, carbs: 0.6, fats: 5, serving: '1 large', category: 'Protein' },
  // Plant protein
  { name: 'Tofu (Firm)', calories: 144, protein: 17, carbs: 3, fats: 8, serving: '150g', category: 'Protein' },
  { name: 'Tofu (Silken)', calories: 55, protein: 5, carbs: 2, fats: 3, serving: '100g', category: 'Protein' },
  { name: 'Tempeh', calories: 192, protein: 20, carbs: 8, fats: 11, serving: '100g', category: 'Protein' },
  { name: 'Edamame', calories: 120, protein: 12, carbs: 9, fats: 5, serving: '100g', category: 'Protein' },
  { name: 'Chickpeas (Cooked)', calories: 164, protein: 9, carbs: 27, fats: 2.6, serving: '1 cup', category: 'Protein' },
  { name: 'Lentils (Cooked)', calories: 230, protein: 18, carbs: 40, fats: 0.8, serving: '1 cup', category: 'Protein' },
  { name: 'Black Beans (Cooked)', calories: 227, protein: 15, carbs: 41, fats: 0.9, serving: '1 cup', category: 'Protein' },
  { name: 'Kidney Beans (Cooked)', calories: 225, protein: 15, carbs: 40, fats: 0.9, serving: '1 cup', category: 'Protein' },
  { name: 'Baked Beans', calories: 155, protein: 7, carbs: 27, fats: 0.6, serving: '½ can', category: 'Protein' },
  { name: 'Seitan', calories: 126, protein: 25, carbs: 4, fats: 1, serving: '100g', category: 'Protein' },
  { name: 'Kangaroo Steak', calories: 120, protein: 24, carbs: 0, fats: 2, serving: '100g', category: 'Protein' },
  { name: 'Venison', calories: 158, protein: 30, carbs: 0, fats: 3.2, serving: '100g', category: 'Protein' },
  { name: 'Duck Breast', calories: 201, protein: 24, carbs: 0, fats: 11, serving: '100g', category: 'Protein' },
  { name: 'Protein Pancakes (3)', calories: 280, protein: 25, carbs: 30, fats: 6, serving: '3 pancakes', category: 'Protein' },
  { name: 'Beef Patty', calories: 210, protein: 18, carbs: 0, fats: 15, serving: '1 patty (100g)', category: 'Protein' },
  { name: 'Chicken Patty', calories: 160, protein: 18, carbs: 8, fats: 6, serving: '1 patty', category: 'Protein' },
  { name: 'Turkey Patty', calories: 150, protein: 20, carbs: 2, fats: 7, serving: '1 patty', category: 'Protein' },

  // ─── DAIRY ────────────────────────────────────────────────────────────────
  // Yogurt
  { name: 'Greek Yogurt (Plain)', calories: 100, protein: 17, carbs: 6, fats: 0.7, serving: '170g', category: 'Dairy' },
  { name: 'Greek Yogurt (Flavored)', calories: 150, protein: 15, carbs: 18, fats: 2, serving: '170g', category: 'Dairy' },
  { name: 'Greek Yogurt (Full Fat)', calories: 165, protein: 15, carbs: 7, fats: 9, serving: '170g', category: 'Dairy' },
  { name: 'Natural Yogurt', calories: 100, protein: 5, carbs: 12, fats: 3.3, serving: '170g', category: 'Dairy' },
  { name: 'Skyr', calories: 110, protein: 19, carbs: 7, fats: 0.5, serving: '170g', category: 'Dairy' },
  { name: 'YoPro (High Protein)', calories: 120, protein: 15, carbs: 12, fats: 0.3, serving: '160g', category: 'Dairy' },
  // Cheese
  { name: 'Cottage Cheese', calories: 98, protein: 11, carbs: 3.4, fats: 4.3, serving: '100g', category: 'Dairy' },
  { name: 'Cottage Cheese (Low Fat)', calories: 72, protein: 12, carbs: 3, fats: 1, serving: '100g', category: 'Dairy' },
  { name: 'Ricotta', calories: 174, protein: 11, carbs: 6, fats: 12, serving: '100g', category: 'Dairy' },
  { name: 'Cheddar Cheese', calories: 113, protein: 7, carbs: 0.4, fats: 9, serving: '28g', category: 'Dairy' },
  { name: 'Mozzarella', calories: 85, protein: 6, carbs: 0.7, fats: 6, serving: '28g', category: 'Dairy' },
  { name: 'Parmesan', calories: 110, protein: 10, carbs: 0.9, fats: 7, serving: '28g', category: 'Dairy' },
  { name: 'Swiss Cheese', calories: 106, protein: 8, carbs: 0.4, fats: 8, serving: '28g', category: 'Dairy' },
  { name: 'Feta Cheese', calories: 75, protein: 4, carbs: 1.1, fats: 6, serving: '28g', category: 'Dairy' },
  { name: 'Cream Cheese', calories: 99, protein: 2, carbs: 1.6, fats: 10, serving: '28g', category: 'Dairy' },
  { name: 'Cheese Slice (Processed)', calories: 60, protein: 4, carbs: 1, fats: 5, serving: '1 slice', category: 'Dairy' },
  { name: 'Halloumi', calories: 110, protein: 7, carbs: 1, fats: 9, serving: '40g', category: 'Dairy' },
  { name: 'Brie', calories: 95, protein: 6, carbs: 0.1, fats: 8, serving: '28g', category: 'Dairy' },
  // Milk
  { name: 'Whole Milk', calories: 149, protein: 8, carbs: 12, fats: 8, serving: '1 cup', category: 'Dairy' },
  { name: 'Skim Milk', calories: 83, protein: 8, carbs: 12, fats: 0.2, serving: '1 cup', category: 'Dairy' },
  { name: 'Semi-Skim Milk', calories: 122, protein: 8, carbs: 12, fats: 5, serving: '1 cup', category: 'Dairy' },
  { name: 'Oat Milk', calories: 120, protein: 3, carbs: 16, fats: 5, serving: '1 cup', category: 'Dairy' },
  { name: 'Almond Milk (Unsweetened)', calories: 30, protein: 1, carbs: 1, fats: 2.5, serving: '1 cup', category: 'Dairy' },
  { name: 'Soy Milk', calories: 80, protein: 7, carbs: 4, fats: 4, serving: '1 cup', category: 'Dairy' },
  // Other dairy
  { name: 'Butter', calories: 102, protein: 0.1, carbs: 0, fats: 12, serving: '1 tbsp', category: 'Dairy' },
  { name: 'Sour Cream', calories: 23, protein: 0.3, carbs: 0.5, fats: 2.4, serving: '1 tbsp', category: 'Dairy' },
  { name: 'Thickened Cream', calories: 51, protein: 0.3, carbs: 0.4, fats: 5.5, serving: '1 tbsp', category: 'Dairy' },
  { name: 'Whipped Cream', calories: 25, protein: 0.2, carbs: 1, fats: 2.2, serving: '2 tbsp', category: 'Dairy' },

  // ─── GRAINS & CARBS ──────────────────────────────────────────────────────
  // Rice & grains
  { name: 'White Rice', calories: 206, protein: 4.3, carbs: 45, fats: 0.4, serving: '1 cup', category: 'Grains & Carbs' },
  { name: 'Brown Rice', calories: 216, protein: 5, carbs: 45, fats: 1.8, serving: '1 cup', category: 'Grains & Carbs' },
  { name: 'Basmati Rice', calories: 210, protein: 4.5, carbs: 46, fats: 0.5, serving: '1 cup', category: 'Grains & Carbs' },
  { name: 'Jasmine Rice', calories: 205, protein: 4.2, carbs: 45, fats: 0.3, serving: '1 cup', category: 'Grains & Carbs' },
  { name: 'Quinoa', calories: 222, protein: 8, carbs: 39, fats: 3.5, serving: '1 cup', category: 'Grains & Carbs' },
  { name: 'Couscous', calories: 176, protein: 6, carbs: 36, fats: 0.3, serving: '1 cup', category: 'Grains & Carbs' },
  { name: 'Bulgur Wheat', calories: 151, protein: 6, carbs: 34, fats: 0.4, serving: '1 cup', category: 'Grains & Carbs' },
  // Oats & cereal
  { name: 'Oats', calories: 150, protein: 5, carbs: 27, fats: 2.5, serving: '½ cup dry', category: 'Grains & Carbs' },
  { name: 'Overnight Oats', calories: 210, protein: 8, carbs: 34, fats: 5, serving: '1 cup', category: 'Grains & Carbs' },
  { name: 'Muesli', calories: 200, protein: 5, carbs: 36, fats: 5, serving: '½ cup', category: 'Grains & Carbs' },
  { name: 'Weet-Bix (2)', calories: 120, protein: 4, carbs: 22, fats: 0.6, serving: '2 biscuits', category: 'Grains & Carbs' },
  { name: 'Cornflakes', calories: 100, protein: 2, carbs: 24, fats: 0.1, serving: '1 cup', category: 'Grains & Carbs' },
  // Bread & wraps
  { name: 'Whole Wheat Bread', calories: 79, protein: 4, carbs: 15, fats: 1, serving: '1 slice', category: 'Grains & Carbs' },
  { name: 'White Bread', calories: 75, protein: 2.5, carbs: 14, fats: 1, serving: '1 slice', category: 'Grains & Carbs' },
  { name: 'Sourdough Bread', calories: 93, protein: 4, carbs: 18, fats: 0.6, serving: '1 slice', category: 'Grains & Carbs' },
  { name: 'Rye Bread', calories: 83, protein: 3, carbs: 16, fats: 1, serving: '1 slice', category: 'Grains & Carbs' },
  { name: 'Multigrain Bread', calories: 85, protein: 4, carbs: 15, fats: 1.5, serving: '1 slice', category: 'Grains & Carbs' },
  { name: 'Toast (2 Slices)', calories: 160, protein: 5, carbs: 30, fats: 2, serving: '2 slices', category: 'Grains & Carbs' },
  { name: 'Wrap (Tortilla)', calories: 140, protein: 4, carbs: 24, fats: 3, serving: '1 large', category: 'Grains & Carbs' },
  { name: 'Pita Bread', calories: 165, protein: 5, carbs: 33, fats: 0.7, serving: '1 large', category: 'Grains & Carbs' },
  { name: 'Naan Bread', calories: 260, protein: 8, carbs: 45, fats: 5, serving: '1 piece', category: 'Grains & Carbs' },
  { name: 'Bagel', calories: 270, protein: 10, carbs: 53, fats: 1.5, serving: '1 large', category: 'Grains & Carbs' },
  { name: 'English Muffin', calories: 132, protein: 5, carbs: 26, fats: 1, serving: '1 muffin', category: 'Grains & Carbs' },
  { name: 'Crumpet', calories: 80, protein: 3, carbs: 16, fats: 0.3, serving: '1 crumpet', category: 'Grains & Carbs' },
  // Pasta & noodles
  { name: 'Pasta (Cooked)', calories: 220, protein: 8, carbs: 43, fats: 1.3, serving: '1 cup', category: 'Grains & Carbs' },
  { name: 'Whole Wheat Pasta', calories: 174, protein: 7, carbs: 37, fats: 0.8, serving: '1 cup', category: 'Grains & Carbs' },
  { name: 'Egg Noodles', calories: 221, protein: 7, carbs: 40, fats: 3, serving: '1 cup', category: 'Grains & Carbs' },
  { name: 'Rice Noodles', calories: 192, protein: 1.6, carbs: 44, fats: 0.4, serving: '1 cup', category: 'Grains & Carbs' },
  { name: 'Ramen Noodles (Dry)', calories: 190, protein: 5, carbs: 26, fats: 7, serving: '½ block', category: 'Grains & Carbs' },
  // Potatoes & starchy veg
  { name: 'Sweet Potato', calories: 103, protein: 2.3, carbs: 24, fats: 0.1, serving: '1 medium', category: 'Grains & Carbs' },
  { name: 'White Potato', calories: 130, protein: 3, carbs: 30, fats: 0.2, serving: '1 medium', category: 'Grains & Carbs' },
  { name: 'Mashed Potato', calories: 174, protein: 3, carbs: 24, fats: 8, serving: '1 cup', category: 'Grains & Carbs' },
  { name: 'Baked Potato', calories: 161, protein: 4, carbs: 37, fats: 0.2, serving: '1 medium', category: 'Grains & Carbs' },
  { name: 'Chips / Fries', calories: 312, protein: 3.4, carbs: 41, fats: 15, serving: '100g', category: 'Grains & Carbs' },
  { name: 'Corn on the Cob', calories: 88, protein: 3, carbs: 19, fats: 1.4, serving: '1 ear', category: 'Grains & Carbs' },
  // Other carbs
  { name: 'Rice Cakes (2)', calories: 70, protein: 1.4, carbs: 15, fats: 0.4, serving: '2 cakes', category: 'Grains & Carbs' },
  { name: 'Honey', calories: 64, protein: 0, carbs: 17, fats: 0, serving: '1 tbsp', category: 'Grains & Carbs' },
  { name: 'Maple Syrup', calories: 52, protein: 0, carbs: 13, fats: 0, serving: '1 tbsp', category: 'Grains & Carbs' },
  { name: 'Jam', calories: 56, protein: 0.1, carbs: 14, fats: 0, serving: '1 tbsp', category: 'Grains & Carbs' },

  // ─── FRUITS & VEGETABLES ─────────────────────────────────────────────────
  // Fruits
  { name: 'Banana', calories: 105, protein: 1.3, carbs: 27, fats: 0.4, serving: '1 medium', category: 'Fruits & Vegetables' },
  { name: 'Apple', calories: 95, protein: 0.5, carbs: 25, fats: 0.3, serving: '1 medium', category: 'Fruits & Vegetables' },
  { name: 'Orange', calories: 62, protein: 1.2, carbs: 15, fats: 0.2, serving: '1 medium', category: 'Fruits & Vegetables' },
  { name: 'Blueberries', calories: 84, protein: 1.1, carbs: 21, fats: 0.5, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Strawberries', calories: 49, protein: 1, carbs: 12, fats: 0.5, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Raspberries', calories: 64, protein: 1.5, carbs: 15, fats: 0.8, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Mixed Berries', calories: 70, protein: 1, carbs: 17, fats: 0.5, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Grapes', calories: 104, protein: 1, carbs: 27, fats: 0.2, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Watermelon', calories: 46, protein: 0.9, carbs: 12, fats: 0.2, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Mango', calories: 99, protein: 1.4, carbs: 25, fats: 0.6, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Pineapple', calories: 82, protein: 0.9, carbs: 22, fats: 0.2, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Pear', calories: 101, protein: 0.6, carbs: 27, fats: 0.2, serving: '1 medium', category: 'Fruits & Vegetables' },
  { name: 'Peach', calories: 59, protein: 1.4, carbs: 14, fats: 0.4, serving: '1 medium', category: 'Fruits & Vegetables' },
  { name: 'Kiwi Fruit', calories: 42, protein: 0.8, carbs: 10, fats: 0.4, serving: '1 fruit', category: 'Fruits & Vegetables' },
  { name: 'Mandarin', calories: 47, protein: 0.7, carbs: 12, fats: 0.3, serving: '1 medium', category: 'Fruits & Vegetables' },
  { name: 'Medjool Dates (2)', calories: 133, protein: 0.7, carbs: 36, fats: 0.1, serving: '2 dates', category: 'Fruits & Vegetables' },
  { name: 'Dried Cranberries', calories: 130, protein: 0, carbs: 33, fats: 0.5, serving: '¼ cup', category: 'Fruits & Vegetables' },
  { name: 'Raisins', calories: 130, protein: 1, carbs: 34, fats: 0.2, serving: '¼ cup', category: 'Fruits & Vegetables' },
  // Avocado
  { name: 'Avocado (Whole)', calories: 234, protein: 3, carbs: 12, fats: 21, serving: '1 whole', category: 'Fruits & Vegetables' },
  { name: 'Avocado (Half)', calories: 117, protein: 1.5, carbs: 6, fats: 10.5, serving: '½ avocado', category: 'Fruits & Vegetables' },
  // Vegetables
  { name: 'Broccoli', calories: 55, protein: 3.7, carbs: 11, fats: 0.6, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Spinach (Raw)', calories: 7, protein: 0.9, carbs: 1.1, fats: 0.1, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Spinach (Cooked)', calories: 41, protein: 5, carbs: 7, fats: 0.5, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Mixed Salad', calories: 20, protein: 1.5, carbs: 3.5, fats: 0.2, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Kale', calories: 33, protein: 2.9, carbs: 6, fats: 0.6, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Asparagus', calories: 27, protein: 3, carbs: 5, fats: 0.2, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Green Beans', calories: 31, protein: 1.8, carbs: 7, fats: 0.1, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Capsicum (Bell Pepper)', calories: 30, protein: 1, carbs: 7, fats: 0.3, serving: '1 medium', category: 'Fruits & Vegetables' },
  { name: 'Zucchini', calories: 21, protein: 1.5, carbs: 4, fats: 0.4, serving: '1 medium', category: 'Fruits & Vegetables' },
  { name: 'Carrot', calories: 25, protein: 0.6, carbs: 6, fats: 0.1, serving: '1 medium', category: 'Fruits & Vegetables' },
  { name: 'Mushrooms', calories: 15, protein: 2.2, carbs: 2.3, fats: 0.2, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Tomato', calories: 22, protein: 1.1, carbs: 4.8, fats: 0.2, serving: '1 medium', category: 'Fruits & Vegetables' },
  { name: 'Cherry Tomatoes', calories: 27, protein: 1.3, carbs: 6, fats: 0.3, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Cucumber', calories: 16, protein: 0.7, carbs: 3.8, fats: 0.1, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Onion', calories: 44, protein: 1.2, carbs: 10, fats: 0.1, serving: '1 medium', category: 'Fruits & Vegetables' },
  { name: 'Peas', calories: 62, protein: 4, carbs: 11, fats: 0.3, serving: '½ cup', category: 'Fruits & Vegetables' },
  { name: 'Cauliflower', calories: 25, protein: 2, carbs: 5, fats: 0.3, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Brussels Sprouts', calories: 56, protein: 4, carbs: 11, fats: 0.8, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Celery', calories: 6, protein: 0.3, carbs: 1.2, fats: 0.1, serving: '2 stalks', category: 'Fruits & Vegetables' },
  { name: 'Eggplant', calories: 20, protein: 0.8, carbs: 5, fats: 0.2, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Cabbage', calories: 22, protein: 1.3, carbs: 5, fats: 0.1, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Mixed Frozen Veg', calories: 65, protein: 3, carbs: 13, fats: 0.3, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Stir Fry Vegetables', calories: 45, protein: 2, carbs: 9, fats: 0.5, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Sweet Corn (Canned)', calories: 130, protein: 4, carbs: 27, fats: 1.5, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Beetroot', calories: 58, protein: 2, carbs: 13, fats: 0.2, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Roasted Vegetables', calories: 120, protein: 2, carbs: 18, fats: 5, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Coleslaw (No Dressing)', calories: 25, protein: 1, carbs: 6, fats: 0.1, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Edamame Beans', calories: 120, protein: 12, carbs: 9, fats: 5, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Sun-Dried Tomatoes', calories: 40, protein: 2, carbs: 5, fats: 2, serving: '28g', category: 'Fruits & Vegetables' },
  { name: 'Olives (10)', calories: 40, protein: 0.3, carbs: 2, fats: 3.5, serving: '10 olives', category: 'Fruits & Vegetables' },
  { name: 'Pickles (Gherkin)', calories: 5, protein: 0.2, carbs: 1, fats: 0, serving: '1 pickle', category: 'Fruits & Vegetables' },
  { name: 'Frozen Berries', calories: 70, protein: 1, carbs: 16, fats: 0.5, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Grapefruit', calories: 52, protein: 1, carbs: 13, fats: 0.2, serving: '½ fruit', category: 'Fruits & Vegetables' },
  { name: 'Passionfruit (2)', calories: 34, protein: 0.8, carbs: 8, fats: 0.3, serving: '2 fruits', category: 'Fruits & Vegetables' },
  { name: 'Cherries', calories: 87, protein: 1.5, carbs: 22, fats: 0.3, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Rockmelon', calories: 54, protein: 1.3, carbs: 13, fats: 0.3, serving: '1 cup', category: 'Fruits & Vegetables' },

  // ─── SNACKS & CONVENIENCE ────────────────────────────────────────────────
  // Bars
  { name: 'Protein Bar', calories: 220, protein: 20, carbs: 25, fats: 8, serving: '1 bar', category: 'Snacks & Convenience' },
  { name: 'Protein Ball (1)', calories: 95, protein: 5, carbs: 10, fats: 4, serving: '1 ball', category: 'Snacks & Convenience' },
  { name: 'Muesli Bar', calories: 120, protein: 2, carbs: 20, fats: 4, serving: '1 bar', category: 'Snacks & Convenience' },
  { name: 'Granola Bar', calories: 100, protein: 2, carbs: 18, fats: 3, serving: '1 bar', category: 'Snacks & Convenience' },
  { name: 'Rice Krispies Treat', calories: 90, protein: 1, carbs: 17, fats: 2.5, serving: '1 bar', category: 'Snacks & Convenience' },
  // Nuts & seeds
  { name: 'Almonds', calories: 164, protein: 6, carbs: 6, fats: 14, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Cashews', calories: 157, protein: 5, carbs: 9, fats: 12, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Walnuts', calories: 185, protein: 4, carbs: 4, fats: 18, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Peanuts', calories: 161, protein: 7, carbs: 5, fats: 14, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Macadamias', calories: 204, protein: 2, carbs: 4, fats: 22, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Pistachios', calories: 159, protein: 6, carbs: 8, fats: 13, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Mixed Nuts', calories: 172, protein: 5, carbs: 7, fats: 15, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Trail Mix', calories: 140, protein: 4, carbs: 13, fats: 9, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Peanut Butter', calories: 188, protein: 8, carbs: 6, fats: 16, serving: '2 tbsp', category: 'Snacks & Convenience' },
  { name: 'Almond Butter', calories: 196, protein: 7, carbs: 6, fats: 18, serving: '2 tbsp', category: 'Snacks & Convenience' },
  { name: 'Sunflower Seeds', calories: 165, protein: 6, carbs: 7, fats: 14, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Pumpkin Seeds', calories: 151, protein: 7, carbs: 5, fats: 13, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Chia Seeds', calories: 137, protein: 4, carbs: 12, fats: 9, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Flaxseed (Ground)', calories: 37, protein: 1.3, carbs: 2, fats: 3, serving: '1 tbsp', category: 'Snacks & Convenience' },
  // Snack foods
  { name: 'Beef Jerky', calories: 116, protein: 9, carbs: 3, fats: 7, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Granola', calories: 210, protein: 5, carbs: 34, fats: 7, serving: '½ cup', category: 'Snacks & Convenience' },
  { name: 'Dark Chocolate', calories: 170, protein: 2, carbs: 13, fats: 12, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Milk Chocolate', calories: 150, protein: 2, carbs: 17, fats: 9, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Hummus', calories: 70, protein: 2, carbs: 6, fats: 4, serving: '2 tbsp', category: 'Snacks & Convenience' },
  { name: 'Tuna + Rice Cup', calories: 280, protein: 22, carbs: 35, fats: 4, serving: '1 cup', category: 'Snacks & Convenience' },
  { name: 'Popcorn (Air Popped)', calories: 31, protein: 1, carbs: 6, fats: 0.4, serving: '1 cup', category: 'Snacks & Convenience' },
  { name: 'Popcorn (Buttered)', calories: 80, protein: 1, carbs: 8, fats: 5, serving: '1 cup', category: 'Snacks & Convenience' },
  { name: 'Pretzels', calories: 110, protein: 3, carbs: 23, fats: 1, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Corn Chips', calories: 140, protein: 2, carbs: 19, fats: 7, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Potato Chips', calories: 152, protein: 2, carbs: 15, fats: 10, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Crackers (6)', calories: 80, protein: 1, carbs: 12, fats: 3, serving: '6 crackers', category: 'Snacks & Convenience' },
  { name: 'Rice Crackers', calories: 70, protein: 1, carbs: 15, fats: 0.5, serving: '10 crackers', category: 'Snacks & Convenience' },
  { name: 'Cheese & Crackers', calories: 190, protein: 6, carbs: 14, fats: 12, serving: '1 serve', category: 'Snacks & Convenience' },
  { name: 'Fruit & Nut Mix', calories: 160, protein: 4, carbs: 16, fats: 10, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Muffin (Blueberry)', calories: 340, protein: 5, carbs: 52, fats: 13, serving: '1 large', category: 'Snacks & Convenience' },

  // ─── MEALS & COMBOS ──────────────────────────────────────────────────────
  // Breakfast
  { name: 'Eggs on Toast (2)', calories: 300, protein: 18, carbs: 28, fats: 13, serving: '2 eggs + 2 toast', category: 'Meals & Combos' },
  { name: 'Bacon & Eggs', calories: 250, protein: 18, carbs: 1, fats: 19, serving: '2 eggs + 2 bacon', category: 'Meals & Combos' },
  { name: 'Oats + Banana + PB', calories: 400, protein: 14, carbs: 58, fats: 15, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Avocado Toast', calories: 280, protein: 7, carbs: 26, fats: 18, serving: '1 slice + ½ avo', category: 'Meals & Combos' },
  { name: 'Smoothie Bowl', calories: 350, protein: 12, carbs: 55, fats: 10, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Pancakes (3)', calories: 350, protein: 9, carbs: 52, fats: 12, serving: '3 pancakes', category: 'Meals & Combos' },
  { name: 'French Toast (2)', calories: 300, protein: 12, carbs: 38, fats: 12, serving: '2 slices', category: 'Meals & Combos' },
  { name: 'Yogurt + Granola + Fruit', calories: 280, protein: 18, carbs: 40, fats: 6, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Muesli + Milk', calories: 300, protein: 10, carbs: 48, fats: 8, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Big Brekkie', calories: 650, protein: 35, carbs: 40, fats: 38, serving: '1 plate', category: 'Meals & Combos' },
  // Lunch / Dinner
  { name: 'Chicken + Rice', calories: 450, protein: 40, carbs: 45, fats: 8, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Chicken + Rice + Veg', calories: 500, protein: 42, carbs: 50, fats: 10, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Steak + Mash + Veg', calories: 550, protein: 35, carbs: 35, fats: 28, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Salmon + Rice', calories: 430, protein: 28, carbs: 45, fats: 14, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Tuna + Rice Bowl', calories: 380, protein: 32, carbs: 46, fats: 4, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Mince + Rice', calories: 480, protein: 28, carbs: 45, fats: 20, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Chicken Stir Fry', calories: 420, protein: 35, carbs: 35, fats: 14, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Beef Stir Fry', calories: 470, protein: 30, carbs: 38, fats: 20, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Pasta + Mince Sauce', calories: 550, protein: 25, carbs: 60, fats: 22, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Pasta + Chicken', calories: 500, protein: 35, carbs: 55, fats: 12, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Chicken Wrap', calories: 420, protein: 30, carbs: 38, fats: 16, serving: '1 wrap', category: 'Meals & Combos' },
  { name: 'Chicken Salad', calories: 350, protein: 35, carbs: 12, fats: 18, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Tuna Salad', calories: 280, protein: 28, carbs: 10, fats: 14, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Caesar Salad', calories: 390, protein: 18, carbs: 15, fats: 30, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Chicken Sandwich', calories: 400, protein: 28, carbs: 35, fats: 16, serving: '1 sandwich', category: 'Meals & Combos' },
  { name: 'Ham & Cheese Sandwich', calories: 350, protein: 18, carbs: 30, fats: 18, serving: '1 sandwich', category: 'Meals & Combos' },
  { name: 'BLT Sandwich', calories: 320, protein: 12, carbs: 30, fats: 17, serving: '1 sandwich', category: 'Meals & Combos' },
  { name: 'Tuna Sandwich', calories: 360, protein: 22, carbs: 30, fats: 16, serving: '1 sandwich', category: 'Meals & Combos' },
  { name: 'Chicken Burger', calories: 480, protein: 30, carbs: 40, fats: 22, serving: '1 burger', category: 'Meals & Combos' },
  { name: 'Beef Burger', calories: 540, protein: 28, carbs: 40, fats: 30, serving: '1 burger', category: 'Meals & Combos' },
  { name: 'Fish & Chips', calories: 600, protein: 22, carbs: 55, fats: 32, serving: '1 serve', category: 'Meals & Combos' },
  { name: 'Chicken Schnitzel', calories: 350, protein: 28, carbs: 18, fats: 18, serving: '1 piece', category: 'Meals & Combos' },
  { name: 'Meat Pie', calories: 400, protein: 14, carbs: 32, fats: 24, serving: '1 pie', category: 'Meals & Combos' },
  { name: 'Sausage Roll', calories: 320, protein: 8, carbs: 22, fats: 22, serving: '1 roll', category: 'Meals & Combos' },
  { name: 'Fried Rice', calories: 350, protein: 8, carbs: 50, fats: 13, serving: '1 cup', category: 'Meals & Combos' },
  { name: 'Burrito Bowl', calories: 520, protein: 28, carbs: 55, fats: 20, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Poke Bowl', calories: 450, protein: 25, carbs: 50, fats: 16, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Sushi (8 Pieces)', calories: 350, protein: 12, carbs: 55, fats: 8, serving: '8 pieces', category: 'Meals & Combos' },
  { name: 'Pizza (2 Slices)', calories: 500, protein: 20, carbs: 56, fats: 22, serving: '2 slices', category: 'Meals & Combos' },
  { name: 'Soup (Chicken Noodle)', calories: 150, protein: 10, carbs: 18, fats: 4, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Soup (Pumpkin)', calories: 120, protein: 3, carbs: 18, fats: 4, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Protein Oats', calories: 350, protein: 30, carbs: 35, fats: 8, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Lamb Chops + Veg', calories: 480, protein: 32, carbs: 15, fats: 33, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Chicken Curry + Rice', calories: 550, protein: 28, carbs: 60, fats: 20, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Beef Curry + Rice', calories: 600, protein: 25, carbs: 60, fats: 26, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Dhal + Rice', calories: 400, protein: 14, carbs: 65, fats: 8, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Chilli Con Carne', calories: 400, protein: 25, carbs: 35, fats: 16, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Shepherd\'s Pie', calories: 450, protein: 22, carbs: 40, fats: 22, serving: '1 serve', category: 'Meals & Combos' },
  { name: 'Lasagne', calories: 500, protein: 24, carbs: 40, fats: 26, serving: '1 serve', category: 'Meals & Combos' },
  { name: 'Mac & Cheese', calories: 450, protein: 16, carbs: 45, fats: 22, serving: '1 serve', category: 'Meals & Combos' },
  { name: 'Risotto', calories: 400, protein: 10, carbs: 55, fats: 14, serving: '1 serve', category: 'Meals & Combos' },
  { name: 'Omelette (3 Egg)', calories: 280, protein: 21, carbs: 2, fats: 21, serving: '1 omelette', category: 'Meals & Combos' },
  { name: 'Scrambled Eggs (3)', calories: 260, protein: 18, carbs: 3, fats: 20, serving: '3 eggs', category: 'Meals & Combos' },
  { name: 'Taco (2)', calories: 380, protein: 20, carbs: 30, fats: 20, serving: '2 tacos', category: 'Meals & Combos' },
  { name: 'Burrito', calories: 550, protein: 24, carbs: 60, fats: 22, serving: '1 burrito', category: 'Meals & Combos' },
  { name: 'Quesadilla', calories: 470, protein: 22, carbs: 36, fats: 26, serving: '1 quesadilla', category: 'Meals & Combos' },
  { name: 'Nachos', calories: 550, protein: 18, carbs: 48, fats: 32, serving: '1 serve', category: 'Meals & Combos' },
  { name: 'Soup (Minestrone)', calories: 130, protein: 5, carbs: 22, fats: 2, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Soup (Tom Yum)', calories: 100, protein: 8, carbs: 10, fats: 3, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Soup (Bone Broth)', calories: 40, protein: 8, carbs: 1, fats: 0.5, serving: '1 cup', category: 'Meals & Combos' },
  { name: 'Roast Chicken Dinner', calories: 600, protein: 42, carbs: 40, fats: 28, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'BBQ Ribs', calories: 500, protein: 30, carbs: 12, fats: 38, serving: '4 ribs', category: 'Meals & Combos' },
  { name: 'Pulled Pork + Rice', calories: 520, protein: 28, carbs: 50, fats: 22, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Meatballs (5)', calories: 300, protein: 20, carbs: 8, fats: 20, serving: '5 meatballs', category: 'Meals & Combos' },
  { name: 'Pad Thai', calories: 460, protein: 18, carbs: 55, fats: 18, serving: '1 serve', category: 'Meals & Combos' },
  { name: 'Pho', calories: 350, protein: 20, carbs: 42, fats: 8, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Laksa', calories: 500, protein: 18, carbs: 42, fats: 28, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Butter Chicken + Rice', calories: 620, protein: 28, carbs: 58, fats: 30, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Thai Green Curry + Rice', calories: 550, protein: 22, carbs: 55, fats: 26, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Noodle Stir Fry', calories: 400, protein: 15, carbs: 50, fats: 16, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Chicken Fried Rice', calories: 420, protein: 18, carbs: 52, fats: 16, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'San Choy Bow', calories: 250, protein: 18, carbs: 10, fats: 16, serving: '4 cups', category: 'Meals & Combos' },
  { name: 'Spring Rolls (3)', calories: 210, protein: 5, carbs: 25, fats: 10, serving: '3 rolls', category: 'Meals & Combos' },
  { name: 'Dumplings (6)', calories: 280, protein: 12, carbs: 32, fats: 12, serving: '6 dumplings', category: 'Meals & Combos' },
  { name: 'Teriyaki Chicken + Rice', calories: 480, protein: 32, carbs: 55, fats: 12, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Bibimbap', calories: 500, protein: 22, carbs: 62, fats: 18, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Fish Tacos (2)', calories: 340, protein: 18, carbs: 28, fats: 16, serving: '2 tacos', category: 'Meals & Combos' },
  { name: 'Gyoza (6)', calories: 240, protein: 10, carbs: 28, fats: 10, serving: '6 pieces', category: 'Meals & Combos' },
  { name: 'Chicken Katsu Curry', calories: 600, protein: 28, carbs: 65, fats: 24, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Meal Prep Chicken Bowl', calories: 450, protein: 38, carbs: 42, fats: 12, serving: '1 container', category: 'Meals & Combos' },
  { name: 'Eggs Benedict', calories: 450, protein: 20, carbs: 28, fats: 28, serving: '1 serve', category: 'Meals & Combos' },
  { name: 'Shakshuka', calories: 280, protein: 16, carbs: 14, fats: 18, serving: '1 serve', category: 'Meals & Combos' },
  { name: 'Chicken Caesar Wrap', calories: 460, protein: 28, carbs: 34, fats: 24, serving: '1 wrap', category: 'Meals & Combos' },
  { name: 'Tuna Melt', calories: 400, protein: 24, carbs: 30, fats: 20, serving: '1 sandwich', category: 'Meals & Combos' },
  { name: 'Grilled Chicken Salad', calories: 320, protein: 32, carbs: 10, fats: 18, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Prawn Stir Fry', calories: 300, protein: 24, carbs: 28, fats: 10, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Lamb Kofta + Rice', calories: 520, protein: 26, carbs: 50, fats: 24, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Cottage Pie', calories: 420, protein: 22, carbs: 38, fats: 20, serving: '1 serve', category: 'Meals & Combos' },
  { name: 'Chicken Enchiladas (2)', calories: 440, protein: 24, carbs: 38, fats: 22, serving: '2 enchiladas', category: 'Meals & Combos' },
  { name: 'Baked Potato + Beans', calories: 340, protein: 14, carbs: 60, fats: 4, serving: '1 potato', category: 'Meals & Combos' },
  { name: 'Baked Potato + Cheese', calories: 380, protein: 14, carbs: 42, fats: 18, serving: '1 potato', category: 'Meals & Combos' },

  // ─── FAST FOOD & TAKEAWAY ────────────────────────────────────────────────
  // Burgers
  { name: 'McChicken', calories: 400, protein: 14, carbs: 40, fats: 21, serving: '1 burger', category: 'Fast Food & Takeaway' },
  { name: 'Big Mac', calories: 550, protein: 25, carbs: 45, fats: 30, serving: '1 burger', category: 'Fast Food & Takeaway' },
  { name: 'Quarter Pounder', calories: 520, protein: 30, carbs: 40, fats: 26, serving: '1 burger', category: 'Fast Food & Takeaway' },
  { name: 'Cheeseburger', calories: 300, protein: 15, carbs: 33, fats: 12, serving: '1 burger', category: 'Fast Food & Takeaway' },
  { name: 'Double Cheeseburger', calories: 440, protein: 25, carbs: 34, fats: 23, serving: '1 burger', category: 'Fast Food & Takeaway' },
  { name: 'Whopper', calories: 660, protein: 28, carbs: 49, fats: 40, serving: '1 burger', category: 'Fast Food & Takeaway' },
  { name: 'Zinger Burger', calories: 480, protein: 22, carbs: 42, fats: 24, serving: '1 burger', category: 'Fast Food & Takeaway' },
  // Chicken
  { name: 'Chicken Nuggets (6)', calories: 270, protein: 13, carbs: 16, fats: 17, serving: '6 pieces', category: 'Fast Food & Takeaway' },
  { name: 'Chicken Nuggets (10)', calories: 450, protein: 22, carbs: 26, fats: 28, serving: '10 pieces', category: 'Fast Food & Takeaway' },
  { name: 'Fried Chicken (1 Piece)', calories: 320, protein: 18, carbs: 12, fats: 22, serving: '1 piece', category: 'Fast Food & Takeaway' },
  { name: 'Popcorn Chicken', calories: 260, protein: 14, carbs: 16, fats: 16, serving: '1 regular', category: 'Fast Food & Takeaway' },
  { name: 'Chicken Strips (3)', calories: 350, protein: 22, carbs: 20, fats: 20, serving: '3 strips', category: 'Fast Food & Takeaway' },
  // Sides
  { name: 'Small Fries', calories: 230, protein: 3, carbs: 29, fats: 11, serving: '1 small', category: 'Fast Food & Takeaway' },
  { name: 'Medium Fries', calories: 340, protein: 4, carbs: 44, fats: 16, serving: '1 medium', category: 'Fast Food & Takeaway' },
  { name: 'Large Fries', calories: 490, protein: 6, carbs: 63, fats: 23, serving: '1 large', category: 'Fast Food & Takeaway' },
  { name: 'Onion Rings', calories: 320, protein: 4, carbs: 38, fats: 17, serving: '1 regular', category: 'Fast Food & Takeaway' },
  { name: 'Hash Brown', calories: 140, protein: 1.5, carbs: 15, fats: 9, serving: '1 hash brown', category: 'Fast Food & Takeaway' },
  { name: 'Coleslaw', calories: 150, protein: 1, carbs: 13, fats: 11, serving: '1 serve', category: 'Fast Food & Takeaway' },
  // Subs & wraps
  { name: 'Subway 6" (Chicken)', calories: 360, protein: 24, carbs: 42, fats: 9, serving: '6 inch', category: 'Fast Food & Takeaway' },
  { name: 'Subway Footlong (Chicken)', calories: 720, protein: 48, carbs: 84, fats: 18, serving: '12 inch', category: 'Fast Food & Takeaway' },
  { name: 'Subway 6" (Meatball)', calories: 480, protein: 22, carbs: 52, fats: 20, serving: '6 inch', category: 'Fast Food & Takeaway' },
  { name: 'Kebab (Chicken)', calories: 550, protein: 30, carbs: 50, fats: 24, serving: '1 kebab', category: 'Fast Food & Takeaway' },
  { name: 'Kebab (Lamb)', calories: 620, protein: 28, carbs: 50, fats: 32, serving: '1 kebab', category: 'Fast Food & Takeaway' },
  { name: 'HSP / Halal Snack Pack', calories: 900, protein: 35, carbs: 60, fats: 56, serving: '1 regular', category: 'Fast Food & Takeaway' },
  // Pizza
  { name: 'Pizza Margherita (2 Sl)', calories: 440, protein: 16, carbs: 50, fats: 18, serving: '2 slices', category: 'Fast Food & Takeaway' },
  { name: 'Pizza Pepperoni (2 Sl)', calories: 520, protein: 22, carbs: 50, fats: 24, serving: '2 slices', category: 'Fast Food & Takeaway' },
  { name: 'Pizza Meat Lovers (2 Sl)', calories: 580, protein: 26, carbs: 48, fats: 30, serving: '2 slices', category: 'Fast Food & Takeaway' },
  { name: 'Garlic Bread (2 Sl)', calories: 200, protein: 4, carbs: 24, fats: 10, serving: '2 slices', category: 'Fast Food & Takeaway' },
  // Asian takeaway
  { name: 'Fried Dim Sims (4)', calories: 320, protein: 10, carbs: 28, fats: 18, serving: '4 pieces', category: 'Fast Food & Takeaway' },
  { name: 'Satay Chicken + Rice', calories: 520, protein: 26, carbs: 55, fats: 22, serving: '1 serve', category: 'Fast Food & Takeaway' },
  { name: 'Sweet & Sour Pork', calories: 380, protein: 16, carbs: 40, fats: 18, serving: '1 serve', category: 'Fast Food & Takeaway' },
  { name: 'Mongolian Beef', calories: 350, protein: 20, carbs: 25, fats: 18, serving: '1 serve', category: 'Fast Food & Takeaway' },
  { name: 'Honey Chicken', calories: 400, protein: 18, carbs: 45, fats: 16, serving: '1 serve', category: 'Fast Food & Takeaway' },
  { name: 'Chow Mein', calories: 380, protein: 14, carbs: 48, fats: 14, serving: '1 serve', category: 'Fast Food & Takeaway' },
  { name: 'Combination Fried Rice', calories: 420, protein: 14, carbs: 55, fats: 16, serving: '1 serve', category: 'Fast Food & Takeaway' },
  // Other takeaway
  { name: 'Fish Burger', calories: 450, protein: 18, carbs: 45, fats: 22, serving: '1 burger', category: 'Fast Food & Takeaway' },
  { name: 'Battered Fish', calories: 250, protein: 16, carbs: 14, fats: 14, serving: '1 piece', category: 'Fast Food & Takeaway' },
  { name: 'Souvlaki (Chicken)', calories: 480, protein: 28, carbs: 42, fats: 22, serving: '1 wrap', category: 'Fast Food & Takeaway' },
  { name: 'Souvlaki (Lamb)', calories: 540, protein: 26, carbs: 42, fats: 28, serving: '1 wrap', category: 'Fast Food & Takeaway' },
  { name: 'Hot Dog', calories: 290, protein: 10, carbs: 24, fats: 17, serving: '1 hot dog', category: 'Fast Food & Takeaway' },
  { name: 'Loaded Fries', calories: 600, protein: 18, carbs: 50, fats: 36, serving: '1 serve', category: 'Fast Food & Takeaway' },
  { name: 'Chicken Parma', calories: 700, protein: 40, carbs: 35, fats: 42, serving: '1 serve', category: 'Fast Food & Takeaway' },
  { name: 'Butter Chicken (Takeaway)', calories: 350, protein: 20, carbs: 12, fats: 24, serving: '1 serve (no rice)', category: 'Fast Food & Takeaway' },
  { name: 'Naan Bread (Takeaway)', calories: 300, protein: 9, carbs: 50, fats: 7, serving: '1 large', category: 'Fast Food & Takeaway' },
  { name: 'Egg McMuffin', calories: 300, protein: 17, carbs: 30, fats: 12, serving: '1 muffin', category: 'Fast Food & Takeaway' },
  { name: 'Bacon & Egg McMuffin', calories: 340, protein: 19, carbs: 30, fats: 16, serving: '1 muffin', category: 'Fast Food & Takeaway' },
  { name: 'Sausage McMuffin', calories: 400, protein: 14, carbs: 29, fats: 25, serving: '1 muffin', category: 'Fast Food & Takeaway' },
  { name: 'McFlurry', calories: 340, protein: 8, carbs: 50, fats: 12, serving: '1 regular', category: 'Fast Food & Takeaway' },
  { name: 'Sundae', calories: 250, protein: 5, carbs: 38, fats: 8, serving: '1 sundae', category: 'Fast Food & Takeaway' },
  { name: 'Apple Pie (Fast Food)', calories: 230, protein: 2, carbs: 32, fats: 11, serving: '1 pie', category: 'Fast Food & Takeaway' },
  { name: 'Wicked Wing (1)', calories: 95, protein: 5, carbs: 5, fats: 6, serving: '1 wing', category: 'Fast Food & Takeaway' },
  { name: 'Peri Peri Chicken', calories: 280, protein: 28, carbs: 2, fats: 18, serving: '¼ chicken', category: 'Fast Food & Takeaway' },

  // ─── DESSERTS & TREATS ───────────────────────────────────────────────────
  // Baked goods
  { name: 'Chocolate Chip Cookie', calories: 220, protein: 2, carbs: 30, fats: 11, serving: '1 large', category: 'Desserts & Treats' },
  { name: 'Tim Tam (2)', calories: 180, protein: 2, carbs: 22, fats: 10, serving: '2 biscuits', category: 'Desserts & Treats' },
  { name: 'Oreo (3)', calories: 160, protein: 1, carbs: 25, fats: 7, serving: '3 cookies', category: 'Desserts & Treats' },
  { name: 'Brownie', calories: 260, protein: 3, carbs: 36, fats: 12, serving: '1 piece', category: 'Desserts & Treats' },
  { name: 'Croissant', calories: 230, protein: 5, carbs: 26, fats: 12, serving: '1 croissant', category: 'Desserts & Treats' },
  { name: 'Chocolate Croissant', calories: 310, protein: 5, carbs: 34, fats: 17, serving: '1 croissant', category: 'Desserts & Treats' },
  { name: 'Donut (Glazed)', calories: 250, protein: 3, carbs: 31, fats: 13, serving: '1 donut', category: 'Desserts & Treats' },
  { name: 'Donut (Chocolate)', calories: 300, protein: 4, carbs: 38, fats: 15, serving: '1 donut', category: 'Desserts & Treats' },
  { name: 'Cinnamon Roll', calories: 350, protein: 5, carbs: 50, fats: 14, serving: '1 roll', category: 'Desserts & Treats' },
  { name: 'Scone', calories: 200, protein: 4, carbs: 28, fats: 8, serving: '1 scone', category: 'Desserts & Treats' },
  { name: 'Danish Pastry', calories: 260, protein: 4, carbs: 30, fats: 14, serving: '1 pastry', category: 'Desserts & Treats' },
  { name: 'Banana Bread (Slice)', calories: 260, protein: 3, carbs: 40, fats: 10, serving: '1 slice', category: 'Desserts & Treats' },
  // Ice cream & frozen
  { name: 'Ice Cream (Vanilla)', calories: 140, protein: 2, carbs: 16, fats: 7, serving: '½ cup', category: 'Desserts & Treats' },
  { name: 'Ice Cream (Chocolate)', calories: 150, protein: 3, carbs: 18, fats: 8, serving: '½ cup', category: 'Desserts & Treats' },
  { name: 'Magnum', calories: 260, protein: 4, carbs: 26, fats: 16, serving: '1 bar', category: 'Desserts & Treats' },
  { name: 'Frozen Yogurt', calories: 110, protein: 3, carbs: 22, fats: 1, serving: '½ cup', category: 'Desserts & Treats' },
  { name: 'Paddle Pop', calories: 100, protein: 1.5, carbs: 14, fats: 4, serving: '1 bar', category: 'Desserts & Treats' },
  { name: 'Sorbet', calories: 100, protein: 0.2, carbs: 26, fats: 0, serving: '½ cup', category: 'Desserts & Treats' },
  // Cakes & slices
  { name: 'Cheesecake (Slice)', calories: 320, protein: 6, carbs: 26, fats: 22, serving: '1 slice', category: 'Desserts & Treats' },
  { name: 'Chocolate Cake (Slice)', calories: 350, protein: 4, carbs: 50, fats: 16, serving: '1 slice', category: 'Desserts & Treats' },
  { name: 'Carrot Cake (Slice)', calories: 300, protein: 3, carbs: 38, fats: 16, serving: '1 slice', category: 'Desserts & Treats' },
  { name: 'Pancake (1)', calories: 120, protein: 3, carbs: 18, fats: 4, serving: '1 pancake', category: 'Desserts & Treats' },
  { name: 'Waffle', calories: 220, protein: 6, carbs: 25, fats: 11, serving: '1 waffle', category: 'Desserts & Treats' },
  // Candy & chocolate
  { name: 'Snickers Bar', calories: 250, protein: 4, carbs: 33, fats: 12, serving: '1 bar', category: 'Desserts & Treats' },
  { name: 'Mars Bar', calories: 228, protein: 2, carbs: 35, fats: 9, serving: '1 bar', category: 'Desserts & Treats' },
  { name: 'Kit Kat (4 Fingers)', calories: 210, protein: 3, carbs: 27, fats: 11, serving: '1 bar', category: 'Desserts & Treats' },
  { name: 'Cadbury Block (Row)', calories: 220, protein: 3, carbs: 25, fats: 12, serving: '4 squares', category: 'Desserts & Treats' },
  { name: 'M&Ms', calories: 240, protein: 2, carbs: 34, fats: 10, serving: '48g bag', category: 'Desserts & Treats' },
  { name: 'Gummy Bears', calories: 130, protein: 3, carbs: 30, fats: 0, serving: '28g', category: 'Desserts & Treats' },
  // Other desserts
  { name: 'Apple Pie (Slice)', calories: 300, protein: 2, carbs: 43, fats: 14, serving: '1 slice', category: 'Desserts & Treats' },
  { name: 'Tiramisu', calories: 280, protein: 5, carbs: 28, fats: 16, serving: '1 serve', category: 'Desserts & Treats' },
  { name: 'Pavlova (Slice)', calories: 250, protein: 3, carbs: 38, fats: 10, serving: '1 slice', category: 'Desserts & Treats' },
  { name: 'Custard', calories: 120, protein: 4, carbs: 16, fats: 4, serving: '½ cup', category: 'Desserts & Treats' },
  { name: 'Rice Pudding', calories: 170, protein: 4, carbs: 30, fats: 4, serving: '½ cup', category: 'Desserts & Treats' },
  { name: 'Protein Ice Cream', calories: 150, protein: 14, carbs: 20, fats: 3, serving: '½ pint', category: 'Desserts & Treats' },
  { name: 'Açaí Bowl', calories: 380, protein: 6, carbs: 62, fats: 12, serving: '1 bowl', category: 'Desserts & Treats' },
  { name: 'Protein Pudding', calories: 140, protein: 15, carbs: 14, fats: 3, serving: '1 serve', category: 'Desserts & Treats' },
  { name: 'Lamington', calories: 250, protein: 3, carbs: 34, fats: 12, serving: '1 lamington', category: 'Desserts & Treats' },
  { name: 'Éclair', calories: 230, protein: 4, carbs: 24, fats: 14, serving: '1 éclair', category: 'Desserts & Treats' },
  { name: 'Churros (3)', calories: 270, protein: 3, carbs: 36, fats: 13, serving: '3 churros', category: 'Desserts & Treats' },
  { name: 'Panna Cotta', calories: 220, protein: 3, carbs: 22, fats: 14, serving: '1 serve', category: 'Desserts & Treats' },
  { name: 'Sticky Date Pudding', calories: 350, protein: 3, carbs: 52, fats: 14, serving: '1 serve', category: 'Desserts & Treats' },
  { name: 'Fruit Salad', calories: 80, protein: 1, carbs: 20, fats: 0.3, serving: '1 cup', category: 'Desserts & Treats' },
  { name: 'Jelly', calories: 70, protein: 1.5, carbs: 16, fats: 0, serving: '½ cup', category: 'Desserts & Treats' },
  { name: 'Mochi (2)', calories: 130, protein: 1, carbs: 28, fats: 1, serving: '2 pieces', category: 'Desserts & Treats' },
  { name: 'Baklava', calories: 230, protein: 3, carbs: 28, fats: 13, serving: '1 piece', category: 'Desserts & Treats' },
  { name: 'Energy Ball (2)', calories: 180, protein: 5, carbs: 22, fats: 8, serving: '2 balls', category: 'Desserts & Treats' },
  { name: 'Rice Krispy Treat', calories: 90, protein: 1, carbs: 17, fats: 2, serving: '1 bar', category: 'Desserts & Treats' },
  { name: 'Anzac Biscuit', calories: 120, protein: 1.5, carbs: 17, fats: 5, serving: '1 biscuit', category: 'Desserts & Treats' },
  { name: 'Shortbread (2)', calories: 160, protein: 2, carbs: 20, fats: 8, serving: '2 pieces', category: 'Desserts & Treats' },
  { name: 'Protein Muffin', calories: 200, protein: 18, carbs: 22, fats: 5, serving: '1 muffin', category: 'Desserts & Treats' },
  { name: 'Lemon Slice', calories: 180, protein: 2, carbs: 26, fats: 8, serving: '1 piece', category: 'Desserts & Treats' },
  { name: 'Banana Split', calories: 450, protein: 6, carbs: 68, fats: 18, serving: '1 serve', category: 'Desserts & Treats' },

  // ─── OILS & CONDIMENTS ───────────────────────────────────────────────────
  // Oils
  { name: 'Olive Oil', calories: 119, protein: 0, carbs: 0, fats: 14, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Coconut Oil', calories: 121, protein: 0, carbs: 0, fats: 14, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Avocado Oil', calories: 124, protein: 0, carbs: 0, fats: 14, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Sesame Oil', calories: 120, protein: 0, carbs: 0, fats: 14, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Cooking Spray', calories: 5, protein: 0, carbs: 0, fats: 0.5, serving: '1 spray', category: 'Oils & Condiments' },
  // Sauces & dressings
  { name: 'Soy Sauce', calories: 9, protein: 1, carbs: 1, fats: 0, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Tomato Sauce (Ketchup)', calories: 20, protein: 0, carbs: 5, fats: 0, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'BBQ Sauce', calories: 29, protein: 0, carbs: 7, fats: 0, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Sweet Chilli Sauce', calories: 25, protein: 0, carbs: 6, fats: 0, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Hot Sauce', calories: 3, protein: 0, carbs: 0.6, fats: 0, serving: '1 tsp', category: 'Oils & Condiments' },
  { name: 'Mayonnaise', calories: 94, protein: 0.1, carbs: 0.1, fats: 10, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Light Mayo', calories: 35, protein: 0, carbs: 1, fats: 3.5, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Mustard', calories: 5, protein: 0.3, carbs: 0.3, fats: 0.3, serving: '1 tsp', category: 'Oils & Condiments' },
  { name: 'Salsa', calories: 10, protein: 0.5, carbs: 2, fats: 0, serving: '2 tbsp', category: 'Oils & Condiments' },
  { name: 'Guacamole', calories: 50, protein: 0.6, carbs: 3, fats: 4, serving: '2 tbsp', category: 'Oils & Condiments' },
  { name: 'Tzatziki', calories: 35, protein: 2, carbs: 2, fats: 2.5, serving: '2 tbsp', category: 'Oils & Condiments' },
  { name: 'Ranch Dressing', calories: 73, protein: 0.4, carbs: 1, fats: 8, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Balsamic Vinegar', calories: 14, protein: 0, carbs: 3, fats: 0, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Pesto', calories: 80, protein: 2, carbs: 1, fats: 8, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Teriyaki Sauce', calories: 16, protein: 1, carbs: 3, fats: 0, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Pasta Sauce (Jar)', calories: 70, protein: 2, carbs: 10, fats: 2, serving: '½ cup', category: 'Oils & Condiments' },
  { name: 'Vegemite', calories: 11, protein: 2, carbs: 0.5, fats: 0, serving: '1 tsp', category: 'Oils & Condiments' },
  { name: 'Sriracha', calories: 5, protein: 0.1, carbs: 1, fats: 0, serving: '1 tsp', category: 'Oils & Condiments' },
  { name: 'Fish Sauce', calories: 6, protein: 1, carbs: 0.7, fats: 0, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Oyster Sauce', calories: 9, protein: 0.2, carbs: 2, fats: 0, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Hoisin Sauce', calories: 35, protein: 0.5, carbs: 7, fats: 0.5, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Worcestershire Sauce', calories: 13, protein: 0, carbs: 3, fats: 0, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Caesar Dressing', calories: 78, protein: 0.5, carbs: 0.5, fats: 8, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Italian Dressing', calories: 43, protein: 0, carbs: 2.5, fats: 4, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Aioli', calories: 100, protein: 0.2, carbs: 0.5, fats: 11, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Chutney', calories: 30, protein: 0, carbs: 7, fats: 0, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Relish', calories: 20, protein: 0.1, carbs: 5, fats: 0, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Tahini', calories: 89, protein: 3, carbs: 3, fats: 8, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Coconut Cream', calories: 50, protein: 0.5, carbs: 0.8, fats: 5, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Sugar (1 tsp)', calories: 16, protein: 0, carbs: 4, fats: 0, serving: '1 tsp', category: 'Oils & Condiments' },
  { name: 'Protein Powder (Unflavored)', calories: 110, protein: 25, carbs: 1, fats: 0.5, serving: '1 scoop', category: 'Oils & Condiments' },
  { name: 'Creatine', calories: 0, protein: 0, carbs: 0, fats: 0, serving: '5g', category: 'Oils & Condiments' },

  // ─── BEVERAGES ────────────────────────────────────────────────────────────
  // Protein drinks
  { name: 'Protein Shake (Whey)', calories: 120, protein: 25, carbs: 3, fats: 1, serving: '1 scoop', category: 'Beverages' },
  { name: 'Protein Shake (2 Scoops)', calories: 240, protein: 50, carbs: 6, fats: 2, serving: '2 scoops', category: 'Beverages' },
  { name: 'Casein Shake', calories: 120, protein: 24, carbs: 3, fats: 1, serving: '1 scoop', category: 'Beverages' },
  { name: 'Plant Protein Shake', calories: 130, protein: 20, carbs: 6, fats: 3, serving: '1 scoop', category: 'Beverages' },
  { name: 'Mass Gainer', calories: 650, protein: 30, carbs: 100, fats: 10, serving: '1 serving', category: 'Beverages' },
  { name: 'Protein Smoothie', calories: 280, protein: 30, carbs: 30, fats: 5, serving: '1 large', category: 'Beverages' },
  { name: 'Protein Water', calories: 70, protein: 15, carbs: 0, fats: 0, serving: '1 bottle', category: 'Beverages' },
  // Milk & dairy drinks
  { name: 'Chocolate Milk', calories: 190, protein: 8, carbs: 30, fats: 5, serving: '1 cup', category: 'Beverages' },
  { name: 'Up & Go', calories: 210, protein: 8, carbs: 33, fats: 5, serving: '1 carton', category: 'Beverages' },
  // Juices & soft
  { name: 'Orange Juice', calories: 112, protein: 2, carbs: 26, fats: 0.5, serving: '1 cup', category: 'Beverages' },
  { name: 'Apple Juice', calories: 114, protein: 0.3, carbs: 28, fats: 0.3, serving: '1 cup', category: 'Beverages' },
  { name: 'Green Juice', calories: 60, protein: 1, carbs: 14, fats: 0.3, serving: '1 cup', category: 'Beverages' },
  { name: 'Coconut Water', calories: 46, protein: 1.7, carbs: 9, fats: 0.5, serving: '1 cup', category: 'Beverages' },
  { name: 'Soft Drink (Can)', calories: 140, protein: 0, carbs: 39, fats: 0, serving: '375ml', category: 'Beverages' },
  { name: 'Energy Drink', calories: 110, protein: 0, carbs: 28, fats: 0, serving: '1 can', category: 'Beverages' },
  { name: 'Sugar-Free Energy Drink', calories: 10, protein: 0, carbs: 2, fats: 0, serving: '1 can', category: 'Beverages' },
  { name: 'Sports Drink (Gatorade)', calories: 80, protein: 0, carbs: 21, fats: 0, serving: '350ml', category: 'Beverages' },
  // Coffee & tea
  { name: 'Black Coffee', calories: 2, protein: 0.3, carbs: 0, fats: 0, serving: '1 cup', category: 'Beverages' },
  { name: 'Flat White', calories: 120, protein: 6, carbs: 9, fats: 7, serving: '1 cup', category: 'Beverages' },
  { name: 'Latte', calories: 135, protein: 7, carbs: 10, fats: 7, serving: '1 cup', category: 'Beverages' },
  { name: 'Cappuccino', calories: 80, protein: 4, carbs: 6, fats: 4, serving: '1 cup', category: 'Beverages' },
  { name: 'Long Black', calories: 4, protein: 0.3, carbs: 0, fats: 0, serving: '1 cup', category: 'Beverages' },
  { name: 'Iced Coffee', calories: 200, protein: 6, carbs: 30, fats: 6, serving: '1 cup', category: 'Beverages' },
  { name: 'Mocha', calories: 230, protein: 8, carbs: 28, fats: 10, serving: '1 cup', category: 'Beverages' },
  { name: 'Tea (Black, No Sugar)', calories: 2, protein: 0, carbs: 0.5, fats: 0, serving: '1 cup', category: 'Beverages' },
  { name: 'Tea + Milk', calories: 20, protein: 1, carbs: 2, fats: 1, serving: '1 cup', category: 'Beverages' },
  { name: 'Green Tea', calories: 2, protein: 0, carbs: 0, fats: 0, serving: '1 cup', category: 'Beverages' },
  // Alcohol
  { name: 'Beer (Schooner)', calories: 170, protein: 1.5, carbs: 14, fats: 0, serving: '425ml', category: 'Beverages' },
  { name: 'Light Beer', calories: 100, protein: 0.7, carbs: 5, fats: 0, serving: '375ml', category: 'Beverages' },
  { name: 'Red Wine', calories: 125, protein: 0.1, carbs: 4, fats: 0, serving: '150ml', category: 'Beverages' },
  { name: 'White Wine', calories: 121, protein: 0.1, carbs: 4, fats: 0, serving: '150ml', category: 'Beverages' },
  { name: 'Vodka Soda', calories: 97, protein: 0, carbs: 0, fats: 0, serving: '1 drink', category: 'Beverages' },
  { name: 'Gin & Tonic', calories: 171, protein: 0, carbs: 14, fats: 0, serving: '1 drink', category: 'Beverages' },
  { name: 'Espresso', calories: 5, protein: 0.3, carbs: 0.5, fats: 0, serving: '1 shot', category: 'Beverages' },
  { name: 'Chai Latte', calories: 180, protein: 5, carbs: 28, fats: 5, serving: '1 cup', category: 'Beverages' },
  { name: 'Matcha Latte', calories: 140, protein: 5, carbs: 18, fats: 5, serving: '1 cup', category: 'Beverages' },
  { name: 'Hot Chocolate', calories: 200, protein: 7, carbs: 28, fats: 7, serving: '1 cup', category: 'Beverages' },
  { name: 'Iced Tea', calories: 70, protein: 0, carbs: 18, fats: 0, serving: '1 cup', category: 'Beverages' },
  { name: 'Kombucha', calories: 30, protein: 0, carbs: 7, fats: 0, serving: '1 cup', category: 'Beverages' },
  { name: 'Smoothie (Fruit)', calories: 200, protein: 2, carbs: 46, fats: 1, serving: '1 large', category: 'Beverages' },
  { name: 'BCAA Drink', calories: 10, protein: 2.5, carbs: 0, fats: 0, serving: '1 serve', category: 'Beverages' },
  { name: 'Pre-Workout', calories: 10, protein: 0, carbs: 2, fats: 0, serving: '1 scoop', category: 'Beverages' },
  { name: 'Electrolyte Drink', calories: 20, protein: 0, carbs: 4, fats: 0, serving: '1 serve', category: 'Beverages' },

  // ─── ADDITIONAL FOODS ──────────────────────────────────────────────────────

  // International Cuisine
  { name: 'Chicken Ramen Bowl', calories: 480, protein: 24, carbs: 58, fats: 16, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Tonkotsu Ramen', calories: 550, protein: 22, carbs: 60, fats: 24, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Miso Ramen', calories: 430, protein: 18, carbs: 55, fats: 14, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Sashimi (8 Pieces)', calories: 180, protein: 28, carbs: 0, fats: 7, serving: '8 pieces', category: 'Meals & Combos' },
  { name: 'Salmon Nigiri (2)', calories: 130, protein: 9, carbs: 18, fats: 2, serving: '2 pieces', category: 'Meals & Combos' },
  { name: 'Chicken Teriyaki Don', calories: 520, protein: 30, carbs: 62, fats: 14, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Katsu Curry (Pork)', calories: 650, protein: 26, carbs: 68, fats: 28, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Okonomiyaki', calories: 400, protein: 14, carbs: 42, fats: 18, serving: '1 pancake', category: 'Meals & Combos' },
  { name: 'Takoyaki (6)', calories: 280, protein: 10, carbs: 32, fats: 12, serving: '6 pieces', category: 'Meals & Combos' },
  { name: 'Chicken Tikka Masala + Rice', calories: 580, protein: 30, carbs: 58, fats: 24, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Palak Paneer + Rice', calories: 520, protein: 18, carbs: 56, fats: 24, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Lamb Rogan Josh + Rice', calories: 600, protein: 28, carbs: 58, fats: 26, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Chicken Biryani', calories: 550, protein: 26, carbs: 65, fats: 20, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Samosa (2)', calories: 260, protein: 6, carbs: 30, fats: 14, serving: '2 pieces', category: 'Meals & Combos' },
  { name: 'Onion Bhaji (3)', calories: 210, protein: 4, carbs: 22, fats: 12, serving: '3 pieces', category: 'Meals & Combos' },
  { name: 'Falafel Wrap', calories: 450, protein: 14, carbs: 52, fats: 22, serving: '1 wrap', category: 'Meals & Combos' },
  { name: 'Falafel (4 Pieces)', calories: 220, protein: 8, carbs: 22, fats: 12, serving: '4 pieces', category: 'Meals & Combos' },
  { name: 'Shawarma (Chicken)', calories: 520, protein: 30, carbs: 44, fats: 24, serving: '1 wrap', category: 'Fast Food & Takeaway' },
  { name: 'Paella', calories: 400, protein: 20, carbs: 48, fats: 14, serving: '1 serve', category: 'Meals & Combos' },
  { name: 'Beef Empanadas (2)', calories: 340, protein: 12, carbs: 30, fats: 20, serving: '2 pieces', category: 'Meals & Combos' },
  { name: 'Chicken Adobo + Rice', calories: 500, protein: 28, carbs: 52, fats: 18, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Banh Mi', calories: 420, protein: 20, carbs: 48, fats: 16, serving: '1 sandwich', category: 'Meals & Combos' },
  { name: 'Korean Fried Chicken (5)', calories: 450, protein: 24, carbs: 28, fats: 26, serving: '5 pieces', category: 'Fast Food & Takeaway' },
  { name: 'Japchae', calories: 320, protein: 10, carbs: 48, fats: 10, serving: '1 serve', category: 'Meals & Combos' },
  { name: 'Kimchi Fried Rice', calories: 400, protein: 14, carbs: 52, fats: 14, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Tteokbokki', calories: 350, protein: 8, carbs: 62, fats: 8, serving: '1 serve', category: 'Meals & Combos' },
  { name: 'Bulgogi + Rice', calories: 520, protein: 28, carbs: 58, fats: 18, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Tom Kha Gai', calories: 280, protein: 16, carbs: 12, fats: 20, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Massaman Curry + Rice', calories: 580, protein: 22, carbs: 60, fats: 28, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Chicken Satay Skewers (4)', calories: 320, protein: 28, carbs: 8, fats: 20, serving: '4 skewers', category: 'Meals & Combos' },
  { name: 'Nasi Goreng', calories: 450, protein: 16, carbs: 56, fats: 18, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Moussaka', calories: 380, protein: 18, carbs: 22, fats: 24, serving: '1 serve', category: 'Meals & Combos' },
  { name: 'Spanakopita', calories: 220, protein: 7, carbs: 18, fats: 14, serving: '1 piece', category: 'Meals & Combos' },
  { name: 'Dolma / Stuffed Vine Leaves (5)', calories: 180, protein: 4, carbs: 22, fats: 8, serving: '5 pieces', category: 'Meals & Combos' },
  { name: 'Chicken Souvlaki Plate', calories: 550, protein: 35, carbs: 45, fats: 24, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Ceviche', calories: 150, protein: 18, carbs: 10, fats: 4, serving: '1 serve', category: 'Meals & Combos' },

  // More Protein Sources
  { name: 'Bison Steak', calories: 143, protein: 28, carbs: 0, fats: 2.4, serving: '100g', category: 'Protein' },
  { name: 'Quail (Whole)', calories: 230, protein: 25, carbs: 0, fats: 14, serving: '1 quail', category: 'Protein' },
  { name: 'Bone Broth', calories: 40, protein: 8, carbs: 1, fats: 0.5, serving: '1 cup (240ml)', category: 'Protein' },
  { name: 'Smoked Tofu', calories: 170, protein: 18, carbs: 3, fats: 10, serving: '150g', category: 'Protein' },
  { name: 'Tofu Scramble', calories: 180, protein: 14, carbs: 6, fats: 12, serving: '1 serve', category: 'Protein' },
  { name: 'Lamb Backstrap', calories: 180, protein: 28, carbs: 0, fats: 7, serving: '100g', category: 'Protein' },
  { name: 'Pork Tenderloin', calories: 120, protein: 23, carbs: 0, fats: 3, serving: '100g', category: 'Protein' },
  { name: 'Turkey Bacon (2 Rashers)', calories: 60, protein: 8, carbs: 0, fats: 3, serving: '2 rashers', category: 'Protein' },
  { name: 'Crab Meat', calories: 87, protein: 18, carbs: 0, fats: 1.5, serving: '100g', category: 'Protein' },
  { name: 'Scallops (5)', calories: 100, protein: 20, carbs: 3, fats: 0.8, serving: '5 pieces', category: 'Protein' },
  { name: 'Oysters (6)', calories: 57, protein: 6, carbs: 3, fats: 2, serving: '6 pieces', category: 'Protein' },
  { name: 'Octopus (Grilled)', calories: 140, protein: 25, carbs: 4, fats: 2, serving: '100g', category: 'Protein' },
  { name: 'Chicken Liver', calories: 170, protein: 24, carbs: 1, fats: 7, serving: '100g', category: 'Protein' },
  { name: 'Pepperoni', calories: 140, protein: 6, carbs: 0.5, fats: 13, serving: '28g', category: 'Protein' },
  { name: 'Chorizo', calories: 130, protein: 7, carbs: 1, fats: 11, serving: '28g', category: 'Protein' },
  { name: 'Prosciutto', calories: 80, protein: 8, carbs: 0, fats: 5, serving: '28g', category: 'Protein' },
  { name: 'Salami', calories: 120, protein: 6, carbs: 0.5, fats: 10, serving: '28g', category: 'Protein' },

  // Popular Restaurant/Chain Items
  { name: 'Chipotle Chicken Bowl', calories: 660, protein: 40, carbs: 70, fats: 22, serving: '1 bowl', category: 'Fast Food & Takeaway' },
  { name: 'Chipotle Burrito', calories: 800, protein: 42, carbs: 88, fats: 28, serving: '1 burrito', category: 'Fast Food & Takeaway' },
  { name: 'Subway 6" (Turkey)', calories: 280, protein: 18, carbs: 40, fats: 4, serving: '6 inch', category: 'Fast Food & Takeaway' },
  { name: 'Subway 6" (Tuna)', calories: 390, protein: 16, carbs: 40, fats: 18, serving: '6 inch', category: 'Fast Food & Takeaway' },
  { name: 'Subway 6" (BMT)', calories: 380, protein: 18, carbs: 40, fats: 16, serving: '6 inch', category: 'Fast Food & Takeaway' },
  { name: 'Dominos Pepperoni (1 Sl)', calories: 260, protein: 11, carbs: 28, fats: 12, serving: '1 slice (large)', category: 'Fast Food & Takeaway' },
  { name: 'Dominos Margherita (1 Sl)', calories: 210, protein: 8, carbs: 26, fats: 8, serving: '1 slice (large)', category: 'Fast Food & Takeaway' },
  { name: 'Dominos BBQ Meatlovers (1 Sl)', calories: 290, protein: 14, carbs: 26, fats: 14, serving: '1 slice (large)', category: 'Fast Food & Takeaway' },
  { name: 'Nandos Quarter Chicken', calories: 290, protein: 32, carbs: 2, fats: 17, serving: '¼ chicken', category: 'Fast Food & Takeaway' },
  { name: 'Nandos Half Chicken', calories: 580, protein: 64, carbs: 4, fats: 34, serving: '½ chicken', category: 'Fast Food & Takeaway' },
  { name: 'Nandos Chicken Wrap', calories: 480, protein: 30, carbs: 42, fats: 20, serving: '1 wrap', category: 'Fast Food & Takeaway' },
  { name: 'Nandos Peri Peri Chips', calories: 390, protein: 5, carbs: 48, fats: 20, serving: '1 regular', category: 'Fast Food & Takeaway' },
  { name: 'GYG Burrito', calories: 680, protein: 32, carbs: 72, fats: 28, serving: '1 burrito', category: 'Fast Food & Takeaway' },
  { name: 'GYG Mini Burrito', calories: 440, protein: 22, carbs: 48, fats: 18, serving: '1 mini burrito', category: 'Fast Food & Takeaway' },
  { name: 'GYG Nachos', calories: 720, protein: 28, carbs: 60, fats: 40, serving: '1 serve', category: 'Fast Food & Takeaway' },
  { name: 'KFC Original Recipe (2 Pc)', calories: 480, protein: 36, carbs: 16, fats: 30, serving: '2 pieces', category: 'Fast Food & Takeaway' },
  { name: 'KFC Zinger Box', calories: 1100, protein: 38, carbs: 110, fats: 52, serving: '1 box', category: 'Fast Food & Takeaway' },
  { name: 'Maccas Filet-O-Fish', calories: 340, protein: 15, carbs: 38, fats: 14, serving: '1 burger', category: 'Fast Food & Takeaway' },
  { name: 'Maccas Angus Burger', calories: 650, protein: 38, carbs: 48, fats: 32, serving: '1 burger', category: 'Fast Food & Takeaway' },
  { name: 'Maccas Hotcakes', calories: 560, protein: 12, carbs: 72, fats: 24, serving: '3 hotcakes', category: 'Fast Food & Takeaway' },

  // Gym/Fitness Specific
  { name: 'Quest Bar', calories: 190, protein: 21, carbs: 22, fats: 7, serving: '1 bar (60g)', category: 'Snacks & Convenience' },
  { name: 'ONE Bar', calories: 220, protein: 20, carbs: 24, fats: 8, serving: '1 bar (60g)', category: 'Snacks & Convenience' },
  { name: 'Grenade Carb Killa Bar', calories: 220, protein: 23, carbs: 17, fats: 9, serving: '1 bar (60g)', category: 'Snacks & Convenience' },
  { name: 'RXBAR', calories: 210, protein: 12, carbs: 24, fats: 9, serving: '1 bar (52g)', category: 'Snacks & Convenience' },
  { name: 'Clif Bar', calories: 250, protein: 10, carbs: 44, fats: 6, serving: '1 bar (68g)', category: 'Snacks & Convenience' },
  { name: 'Kind Bar', calories: 200, protein: 6, carbs: 22, fats: 12, serving: '1 bar (40g)', category: 'Snacks & Convenience' },
  { name: 'Protein Cookie', calories: 250, protein: 16, carbs: 28, fats: 10, serving: '1 cookie', category: 'Snacks & Convenience' },
  { name: 'Protein Chips', calories: 140, protein: 18, carbs: 8, fats: 5, serving: '1 bag (32g)', category: 'Snacks & Convenience' },
  { name: 'Protein Brownie', calories: 200, protein: 15, carbs: 22, fats: 8, serving: '1 brownie', category: 'Snacks & Convenience' },
  { name: 'Creatine Gummies (3)', calories: 30, protein: 0, carbs: 7, fats: 0, serving: '3 gummies', category: 'Snacks & Convenience' },
  { name: 'Protein Wafer Bar', calories: 190, protein: 15, carbs: 18, fats: 8, serving: '1 bar', category: 'Snacks & Convenience' },
  { name: 'Collagen Powder', calories: 35, protein: 9, carbs: 0, fats: 0, serving: '1 scoop (10g)', category: 'Snacks & Convenience' },
  { name: 'EAA Drink', calories: 10, protein: 2, carbs: 1, fats: 0, serving: '1 serve', category: 'Beverages' },
  { name: 'Intra-Workout Carbs', calories: 100, protein: 0, carbs: 25, fats: 0, serving: '1 scoop', category: 'Beverages' },
  { name: 'Protein Iced Coffee', calories: 180, protein: 25, carbs: 12, fats: 3, serving: '1 bottle', category: 'Beverages' },
  { name: 'Protein Shake (RTD)', calories: 160, protein: 30, carbs: 6, fats: 2, serving: '1 bottle', category: 'Beverages' },

  // Breakfast Items
  { name: 'Belgian Waffle', calories: 310, protein: 8, carbs: 40, fats: 14, serving: '1 waffle', category: 'Meals & Combos' },
  { name: 'Breakfast Burrito', calories: 450, protein: 22, carbs: 40, fats: 22, serving: '1 burrito', category: 'Meals & Combos' },
  { name: 'Egg Muffin (Homemade)', calories: 180, protein: 12, carbs: 14, fats: 8, serving: '1 muffin', category: 'Meals & Combos' },
  { name: 'Bircher Muesli', calories: 280, protein: 8, carbs: 42, fats: 8, serving: '1 cup', category: 'Meals & Combos' },
  { name: 'Acai Bowl (Small)', calories: 280, protein: 5, carbs: 48, fats: 8, serving: '1 small bowl', category: 'Meals & Combos' },
  { name: 'Smashed Avo + Eggs on Toast', calories: 420, protein: 18, carbs: 28, fats: 28, serving: '1 serve', category: 'Meals & Combos' },
  { name: 'Breakfast Wrap (Bacon & Egg)', calories: 380, protein: 20, carbs: 30, fats: 20, serving: '1 wrap', category: 'Meals & Combos' },
  { name: 'Protein Waffles (2)', calories: 280, protein: 24, carbs: 30, fats: 8, serving: '2 waffles', category: 'Meals & Combos' },
  { name: 'Vegemite Toast (2)', calories: 180, protein: 7, carbs: 30, fats: 2, serving: '2 slices', category: 'Meals & Combos' },
  { name: 'Baked Beans on Toast', calories: 310, protein: 14, carbs: 52, fats: 3, serving: '1 serve', category: 'Meals & Combos' },

  // Healthy Snacks
  { name: 'Seaweed Snacks', calories: 30, protein: 1, carbs: 1, fats: 2.5, serving: '1 pack (5g)', category: 'Snacks & Convenience' },
  { name: 'Kale Chips', calories: 120, protein: 3, carbs: 10, fats: 8, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Trail Mix (Tropical)', calories: 150, protein: 3, carbs: 18, fats: 8, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Trail Mix (High Protein)', calories: 160, protein: 7, carbs: 10, fats: 12, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Dark Chocolate (85%)', calories: 170, protein: 3, carbs: 10, fats: 14, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Dried Mango', calories: 120, protein: 1, carbs: 28, fats: 0.5, serving: '40g', category: 'Snacks & Convenience' },
  { name: 'Dried Apricots (5)', calories: 80, protein: 1, carbs: 20, fats: 0.2, serving: '5 pieces', category: 'Snacks & Convenience' },
  { name: 'Roasted Chickpeas', calories: 130, protein: 6, carbs: 17, fats: 4, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Edamame (Dry Roasted)', calories: 130, protein: 14, carbs: 10, fats: 4, serving: '28g', category: 'Snacks & Convenience' },
  { name: 'Cottage Cheese + Fruit', calories: 150, protein: 14, carbs: 15, fats: 4, serving: '1 serve', category: 'Snacks & Convenience' },
  { name: 'Rice Cake + PB', calories: 130, protein: 4, carbs: 12, fats: 8, serving: '1 cake + 1 tbsp', category: 'Snacks & Convenience' },
  { name: 'Apple + Peanut Butter', calories: 190, protein: 5, carbs: 28, fats: 8, serving: '1 apple + 1 tbsp', category: 'Snacks & Convenience' },
  { name: 'Banana + Almond Butter', calories: 200, protein: 5, carbs: 30, fats: 8, serving: '1 banana + 1 tbsp', category: 'Snacks & Convenience' },
  { name: 'Vegemite Rice Cakes (2)', calories: 80, protein: 3, carbs: 15, fats: 0.5, serving: '2 cakes', category: 'Snacks & Convenience' },

  // Meal Prep Staples
  { name: 'Sushi Rice', calories: 240, protein: 4, carbs: 53, fats: 0.4, serving: '1 cup', category: 'Grains & Carbs' },
  { name: 'Wild Rice', calories: 166, protein: 6.5, carbs: 35, fats: 0.6, serving: '1 cup', category: 'Grains & Carbs' },
  { name: 'Cauliflower Rice', calories: 25, protein: 2, carbs: 5, fats: 0.3, serving: '1 cup', category: 'Grains & Carbs' },
  { name: 'Buckwheat', calories: 155, protein: 6, carbs: 34, fats: 1, serving: '1 cup', category: 'Grains & Carbs' },
  { name: 'Pearl Barley', calories: 193, protein: 4, carbs: 44, fats: 0.7, serving: '1 cup', category: 'Grains & Carbs' },
  { name: 'Polenta', calories: 145, protein: 3, carbs: 32, fats: 0.5, serving: '1 cup', category: 'Grains & Carbs' },
  { name: 'Meal Prep Chicken (Seasoned)', calories: 180, protein: 32, carbs: 1, fats: 5, serving: '150g', category: 'Protein' },
  { name: 'Chicken Breast (Air Fryer)', calories: 170, protein: 32, carbs: 0, fats: 4, serving: '150g', category: 'Protein' },
  { name: 'Quinoa Bowl', calories: 380, protein: 14, carbs: 48, fats: 14, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Sweet Potato Mash', calories: 130, protein: 2, carbs: 28, fats: 2, serving: '1 cup', category: 'Grains & Carbs' },
  { name: 'Lentil Soup', calories: 180, protein: 12, carbs: 28, fats: 2, serving: '1 bowl', category: 'Meals & Combos' },
  { name: 'Chickpea Curry + Rice', calories: 480, protein: 16, carbs: 68, fats: 14, serving: '1 plate', category: 'Meals & Combos' },
  { name: 'Black Bean Tacos (2)', calories: 360, protein: 14, carbs: 48, fats: 12, serving: '2 tacos', category: 'Meals & Combos' },
  { name: 'Tuna Poke Bowl', calories: 420, protein: 28, carbs: 48, fats: 12, serving: '1 bowl', category: 'Meals & Combos' },

  // More Fruits
  { name: 'Dragon Fruit', calories: 60, protein: 1.2, carbs: 13, fats: 0.4, serving: '1 fruit', category: 'Fruits & Vegetables' },
  { name: 'Passion Fruit (3)', calories: 51, protein: 1.2, carbs: 12, fats: 0.4, serving: '3 fruits', category: 'Fruits & Vegetables' },
  { name: 'Lychee (10)', calories: 66, protein: 0.8, carbs: 17, fats: 0.4, serving: '10 fruits', category: 'Fruits & Vegetables' },
  { name: 'Guava', calories: 68, protein: 2.6, carbs: 14, fats: 1, serving: '1 fruit', category: 'Fruits & Vegetables' },
  { name: 'Papaya', calories: 62, protein: 0.7, carbs: 16, fats: 0.4, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Persimmon', calories: 118, protein: 1, carbs: 31, fats: 0.3, serving: '1 fruit', category: 'Fruits & Vegetables' },
  { name: 'Starfruit', calories: 28, protein: 0.9, carbs: 6, fats: 0.3, serving: '1 fruit', category: 'Fruits & Vegetables' },
  { name: 'Pomegranate Seeds', calories: 83, protein: 1.7, carbs: 19, fats: 1.2, serving: '½ cup', category: 'Fruits & Vegetables' },
  { name: 'Fig (2)', calories: 74, protein: 0.8, carbs: 19, fats: 0.3, serving: '2 figs', category: 'Fruits & Vegetables' },
  { name: 'Plum (2)', calories: 60, protein: 0.9, carbs: 15, fats: 0.4, serving: '2 plums', category: 'Fruits & Vegetables' },
  { name: 'Apricot (2)', calories: 34, protein: 1, carbs: 8, fats: 0.3, serving: '2 apricots', category: 'Fruits & Vegetables' },
  { name: 'Jackfruit', calories: 95, protein: 1.7, carbs: 23, fats: 0.6, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Coconut (Fresh)', calories: 160, protein: 1.5, carbs: 7, fats: 15, serving: '50g', category: 'Fruits & Vegetables' },
  { name: 'Frozen Acai Packet', calories: 100, protein: 1, carbs: 6, fats: 7, serving: '1 packet (100g)', category: 'Fruits & Vegetables' },

  // More Vegetables
  { name: 'Bok Choy', calories: 9, protein: 1, carbs: 1.5, fats: 0.1, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Artichoke', calories: 60, protein: 4, carbs: 13, fats: 0.2, serving: '1 medium', category: 'Fruits & Vegetables' },
  { name: 'Fennel', calories: 27, protein: 1, carbs: 6, fats: 0.2, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Leek', calories: 54, protein: 1.3, carbs: 13, fats: 0.3, serving: '1 leek', category: 'Fruits & Vegetables' },
  { name: 'Turnip', calories: 34, protein: 1.1, carbs: 8, fats: 0.1, serving: '1 medium', category: 'Fruits & Vegetables' },
  { name: 'Parsnip', calories: 100, protein: 1.6, carbs: 24, fats: 0.4, serving: '1 medium', category: 'Fruits & Vegetables' },
  { name: 'Daikon', calories: 21, protein: 0.7, carbs: 5, fats: 0.1, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Snow Peas', calories: 26, protein: 2, carbs: 4, fats: 0.1, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Bean Sprouts', calories: 26, protein: 3, carbs: 4, fats: 0.2, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Water Chestnuts', calories: 60, protein: 0.9, carbs: 15, fats: 0.1, serving: '½ cup', category: 'Fruits & Vegetables' },
  { name: 'Bamboo Shoots', calories: 14, protein: 1.8, carbs: 2, fats: 0.2, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Okra', calories: 33, protein: 1.9, carbs: 7, fats: 0.2, serving: '1 cup', category: 'Fruits & Vegetables' },
  { name: 'Radish', calories: 12, protein: 0.5, carbs: 2.5, fats: 0.1, serving: '5 radishes', category: 'Fruits & Vegetables' },
  { name: 'Kimchi', calories: 23, protein: 1.3, carbs: 4, fats: 0.5, serving: '½ cup', category: 'Fruits & Vegetables' },
  { name: 'Sauerkraut', calories: 14, protein: 0.6, carbs: 3, fats: 0.1, serving: '½ cup', category: 'Fruits & Vegetables' },
  { name: 'Roasted Pumpkin', calories: 80, protein: 1.5, carbs: 16, fats: 2, serving: '1 cup', category: 'Fruits & Vegetables' },

  // Condiments and Sauces
  { name: 'Chimichurri', calories: 60, protein: 0.3, carbs: 1, fats: 6, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Miso Paste', calories: 35, protein: 2, carbs: 5, fats: 1, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Gochujang', calories: 40, protein: 1, carbs: 8, fats: 0.5, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Sambal Oelek', calories: 5, protein: 0.2, carbs: 1, fats: 0, serving: '1 tsp', category: 'Oils & Condiments' },
  { name: 'Harissa Paste', calories: 20, protein: 0.5, carbs: 2, fats: 1, serving: '1 tsp', category: 'Oils & Condiments' },
  { name: 'Coconut Aminos', calories: 5, protein: 0, carbs: 1, fats: 0, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Dukkah', calories: 50, protein: 2, carbs: 2, fats: 4, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Nutritional Yeast', calories: 20, protein: 3, carbs: 1, fats: 0, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Apple Cider Vinegar', calories: 3, protein: 0, carbs: 0.1, fats: 0, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Ghee', calories: 112, protein: 0, carbs: 0, fats: 13, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Truffle Oil', calories: 120, protein: 0, carbs: 0, fats: 14, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Satay Sauce', calories: 45, protein: 1.5, carbs: 3, fats: 3, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Curry Paste', calories: 25, protein: 0.5, carbs: 3, fats: 1.5, serving: '1 tbsp', category: 'Oils & Condiments' },
  { name: 'Honey Mustard', calories: 35, protein: 0.2, carbs: 6, fats: 1.5, serving: '1 tbsp', category: 'Oils & Condiments' },

  // More Dairy
  { name: 'Havarti Cheese', calories: 105, protein: 7, carbs: 0.3, fats: 9, serving: '28g', category: 'Dairy' },
  { name: 'Gouda Cheese', calories: 101, protein: 7, carbs: 0.6, fats: 8, serving: '28g', category: 'Dairy' },
  { name: 'Blue Cheese', calories: 100, protein: 6, carbs: 0.7, fats: 8, serving: '28g', category: 'Dairy' },
  { name: 'Goat Cheese', calories: 75, protein: 5, carbs: 0, fats: 6, serving: '28g', category: 'Dairy' },
  { name: 'Burrata', calories: 90, protein: 5, carbs: 1, fats: 7, serving: '28g', category: 'Dairy' },
  { name: 'Paneer', calories: 265, protein: 18, carbs: 4, fats: 20, serving: '100g', category: 'Dairy' },
  { name: 'Kefir', calories: 60, protein: 4, carbs: 7, fats: 1.5, serving: '1 cup', category: 'Dairy' },
  { name: 'Coconut Yogurt', calories: 140, protein: 1, carbs: 14, fats: 9, serving: '170g', category: 'Dairy' },

  // Additional Beverages
  { name: 'Turmeric Latte', calories: 120, protein: 4, carbs: 16, fats: 5, serving: '1 cup', category: 'Beverages' },
  { name: 'Dirty Chai', calories: 200, protein: 5, carbs: 28, fats: 7, serving: '1 cup', category: 'Beverages' },
  { name: 'Cold Brew Coffee', calories: 5, protein: 0.3, carbs: 0, fats: 0, serving: '1 cup', category: 'Beverages' },
  { name: 'Bubble Tea', calories: 280, protein: 1, carbs: 52, fats: 6, serving: '1 regular', category: 'Beverages' },
  { name: 'Mango Lassi', calories: 220, protein: 6, carbs: 38, fats: 5, serving: '1 glass', category: 'Beverages' },
  { name: 'Cranberry Juice', calories: 116, protein: 0, carbs: 30, fats: 0, serving: '1 cup', category: 'Beverages' },
  { name: 'Watermelon Juice', calories: 72, protein: 0.6, carbs: 18, fats: 0.2, serving: '1 cup', category: 'Beverages' },
  { name: 'Protein Hot Chocolate', calories: 160, protein: 20, carbs: 14, fats: 3, serving: '1 cup', category: 'Beverages' },
];
